### ISSUE TITLE
DA Changes for GFS v16.1

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GSI#120]
This issue tracks DA development for the GFS v16.1 implementation.   This work is done in [release/gfsda.v16.1.0](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16.1.0).

**Comment by CatherineThomas-NOAA** [comment]
Development from issue #128 was included in release/gfsda.v16.1.0 through PR #131.

New fix branch DA_GFSv16.1_global_only was created.  The file global_convinfo.txt was modified to turn on the commercial GNSSRO data at revision ccb403da849a8f76b882f8cf7785d9a42a75917d:
`1083 hfe06% git diff global_convinfo.txt`
`diff --git a/global_convinfo.txt b/global_convinfo.txt`
`index 1444535..0aa7ec5 100755`
`--- a/global_convinfo.txt`
`+++ b/global_convinfo.txt`
`@@ -237,8 +237,8 @@`
`  gps      729    0   -1     3.0      0      0      0  0.024  0.024 0.01 10.0  0.000000     0    0.     0.      0    0.     0.    0    0`
`  gps      044    0   -1     3.0      0      0      0  0.024  0.024 0.01 10.0  0.000000     0    0.     0.      0    0.     0.    0    0`
`  gps      005    0    1     3.0      0      0      0  0.024  0.024 0.01 10.0  0.000000     0    0.     0.      0    0.     0.    0    0`
`- gps      265    0   -1     3.0      0      0      0  0.024  0.024 0.01 10.0  0.000000     0    0.     0.      0    0.     0.    0    0`
`- gps      266    0   -1     3.0      0      0      0  0.024  0.024 0.01 10.0  0.000000     0    0.     0.      0    0.     0.    0    0`
`- gps      267    0   -1     3.0      0      0      0  0.024  0.024 0.01 10.0  0.000000     0    0.     0.      0    0.     0.    0    0`
`- gps      268    0   -1     3.0      0      0      0  0.024  0.024 0.01 10.0  0.000000     0    0.     0.      0    0.     0.    0    0`
`- gps      269    0   -1     3.0      0      0      0  0.024  0.024 0.01 10.0  0.000000     0    0.     0.      0    0.     0.    0    0`
`+ gps      265    0    1     3.0      0      0      0  0.024  0.024 0.01 10.0  0.000000     0    0.     0.      0    0.     0.    0    0`
`+ gps      266    0    1     3.0      0      0      0  0.024  0.024 0.01 10.0  0.000000     0    0.     0.      0    0.     0.    0    0`
`+ gps      267    0    1     3.0      0      0      0  0.024  0.024 0.01 10.0  0.000000     0    0.     0.      0    0.     0.    0    0`
`+ gps      268    0    1     3.0      0      0      0  0.024  0.024 0.01 10.0  0.000000     0    0.     0.      0    0.     0.    0    0`
`+ gps      269    0    1     3.0      0      0      0  0.024  0.024 0.01 10.0  0.000000     0    0.     0.      0    0.     0.    0    0`

**Comment by CatherineThomas-NOAA** [comment]
Commit 3a0e1d9 in release/gfsda.v16.1.0 addresses a bug fix that came up during v16 development.  It was committed previously to the v16 branch at bbf0fd6b, but did not make it into operations for reasons unknown.  This bug creates a problem during regression testing but does not cause issues during cycling inside the workflow.

The fix was tested by @KristenBathmann-NOAA and we confirmed that this change does not alter analysis results nor does it alter the gpsro diag files.

**Comment by CatherineThomas-NOAA** [comment]
Commit cfadd3c eliminates the need to define commgpstop in the config files, bringing all the needed commercial RO changes into the GSI repository rather than needing any changes at the global-workflow level.

**Comment by RussTreadon-NOAA** [comment]
The delz increment fix described in issue #117 and pull request #116 has been added to release/gfsda.v16.1.0.  Done at 9f73597.   

The following files are direct copies from [jswhit:fix_delz_inc](https://github.com/jswhit/GSI/tree/fix_delz_inc)
-` src/enkf/gridio_gfs.f90`
- `src/gsi/ncepnems_io.f90`
-  `src/gsi/write_incr.f90 `

File `src/gsi/netcdfgfs_io.f90` in release/gfsda.v16.1.0 includes delz corrections from [jswhit:fix_delz_inc](https://github.com/jswhit/GSI/tree/fix_delz_inc).  It also contains additional changes in response to NCO v16 DA bugzilla ticket [1196](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1196) (see issue #137).

**Comment by RussTreadon-NOAA** [comment]
Mistakes were made in creating PR #168.  Therefore, PR #168 was abandoned (closed).  Branch release/gfsda.v16.1.0_merge was removed from the authoritative repo. 

GFS v16.1 DA changes were captured in fork [RussTreadon-NOAA:master](https://github.com/RussTreadon-NOAA/GSI) at e856871.   PR #169 was created to bring the forked master into the authoritative repo master.
