### ISSUE TITLE
Correcting GSI and Fortran standard issues in GSI master

### ISSUE THREAD

**Issue by MichaelLueken-NOAA** [NOAA-EMC/GSI#13]
There are several coding standard issues with the routines in the GSI.  Have been going through and correcting these issues within the code.  Thus far, issues corrected have included:

- Ensuring proper indentation in all routines.
- Ensuring proper precision is given for all real values.
- Ensuring that integers are given (i_kind) at variable declaration.
- Several routines are full of random capitalization.  Ensure that variables, if, do, while, and other intrinsic functions are lower case through out.
- Replacing .ge., .le., .gt., .lt., and .eq. with >=, <=, >, <, and ==.
- Replacing .F90 with .f90 for routines that don't contain machine logic.

This work was started in the ProdGSI repo, but was ported to NOAA-EMC/GSI.  Have cleared through:

src/gsi/gsi_4dcouplermod.f90

This work can be found in:

https://github.com/MichaelLueken-NOAA/GSI/commits/feature/code_cleanup_2020

**Comment by MichaelLueken-NOAA** [comment]
From 06/15 - 06-19, cleared through src/gsi/intlwcp.f90.  Updated feature/code_cleanup_2020 branch with the latest updates from the master.

**Comment by MichaelLueken** [comment]
Closing obsolete issue.
