### ISSUE TITLE
ConMon time executable problem

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [NOAA-EMC/GSI#136]
The ConMon's time data extraction executable is occasionally encountering a bus error which results in a core dump.  The problem occurs only with uv data from a NetCDF formatted diag file but does not occur with all cycles.

**Comment by RussTreadon-NOAA** [comment]
For which cycle(s) is the bus error most prevalent?   What is the job configuration for ConMon uv time data extraction?

**Comment by EdwardSafford-NOAA** [comment]
It's confined to the 06z and 12z cycles.  I didn't notice this problem before the prod switch so it's entirely possible the issue is something to do with my older ConMon package here on Mars.  I'll update as I learn more.

**Comment by RussTreadon-NOAA** [comment]
OK.   Maybe the problem will go away after the Mars ConMon package is
updated.

**Comment by EdwardSafford-NOAA** [comment]
Got it figured out.  It's a simple OOM issue that's somehow reported as a bus error.  The conmon_time.x executable failed occasionally with the NetCDF formatted uv diag file, which is the largest of the bundled diag files in the cnvstat.  Eventually I determined the problem occurred at the allocation of a pointer (the obs data is arranged in a linked list).  The LSF report said average memory was less than 100MB but max was 898MB.  Requested memory for the job was 900MB.  After bumping the requested memory to 1000MB the job runs to completion.
