### ISSUE TITLE
Implementing direct radar DA capabilities into 'master' branch of NOAA-EMC GSI

### ISSUE THREAD

**Issue by junpark217** [NOAA-EMC/GSI#141]
The purpose of this PR is to implement direct radar DA capabilities into ‘master’ branch of NOAA-EMC GSI.
The major updates in this issue are outlined as follows:  

- Added direct reflectivity DA capabilities using Thompson and Lin observation operators 
- Added capabilities to assimilate column-tilt RW obs 
- Added codes to process observation (dBZ and RW) bufrfiles into GSI supported format 
- Added option to assimilate newvad observation (in prepbufr) around analysis time   
- Modified I/O codes to support WRF and FV3reg domains for Variational and EnKF DA applications.

List of files: (6 added files(gsi), 30 modified files (gsi:23, enkf:6))
        modified:   CMakeLists.txt
        modified:   src/enkf/enkf_obsmod.f90
        modified:   src/enkf/gridinfo_fv3reg.f90
        modified:   src/enkf/gridio_fv3reg.f90
        modified:   src/enkf/gridio_wrf.f90
        modified:   src/enkf/params.f90
        modified:   src/enkf/readconvobs.f90
        modified:   src/gsi/balmod.f90
        modified:   src/gsi/cplr_get_fv3_regional_ensperts.f90
        modified:   src/gsi/cplr_get_wrf_mass_ensperts.f90
        modified:   src/gsi/cplr_read_wrf_mass_guess.f90
        modified:   src/gsi/cplr_wrf_netcdf_interface.f90
        modified:   src/gsi/cplr_wrwrfmassa.f90
        modified:   src/gsi/gsi_rfv3io_mod.f90
        modified:   src/gsi/gsimod.F90
        modified:   src/gsi/intdbz.f90
        modified:   src/gsi/m_berror_stats_reg.f90
        modified:   src/gsi/m_dbzNode.F90
        modified:   src/gsi/obsmod.F90
        modified:   src/gsi/prewgt_reg.f90
        modified:   src/gsi/read_obs.F90
        modified:   src/gsi/read_prepbufr.f90
        modified:   src/gsi/read_radar.f90
        modified:   src/gsi/setupdbz.f90
        modified:   src/gsi/setuprhsall.f90
        modified:   src/gsi/setuprw.f90
        modified:   src/gsi/smoothzrf.f90
        modified:   src/gsi/statsconv.f90
        modified:   src/gsi/stpdbz.f90
        modified:   src/gsi/update_guess.f90
        new file:   src/gsi/directDA_radaruse_mod.f90
        new file:   src/gsi/radaremul_convert2radar.f90
        new file:   src/gsi/radaremul_dualpolepara.f90
        new file:   src/gsi/radaremul_global_module.f90
        new file:   src/gsi/radaremul_interface.f90
        new file:   src/gsi/read_radarref_mosaic_directDA.f90

**Comment by hu5970** [comment]
I have reviewed the code. I can see this PR includes many years of development efforts from CAPS to analyze the radar reflectivity directly and radial velocity on column-tilt coordinate. It is very important to include those functions in the GSI authoritative repository.

I think it is very hard for outside reviewers to go into the details of the code and schemes for those complicated new operators. But as long as the new code does not break the existing applications and still function well based on the tests, we can send the code for community review and merging code into master branch.

I suggest to move the review process forward:

1) Please try to address my comments. Feel free to contact me on my comments
2) Mike can review the code briefly and point out the code changes needed for meeting GSI code standards. I can see most part of the code are well written. But some codes do need some cleanup. 
3) After CAPS improved the code based on the comments, EMC should run regression tests to make sure the code does not break any other applications. DTC also need to run the MPMC test to check the portability of the code.
4) After the code passed all the tests and meet the GSI code standards, CAPS need to make sure the code still work for their test cases.
5)  After test the code with all the cases we have and the results are identical. Send the code for community review.
