### ISSUE TITLE
Problem occurred when building GSI on HERA

### ISSUE THREAD

**Issue by emilyhcliu** [NOAA-EMC/GSI#16]
**Issue found while building GSI from the forked NOAA-EMC:master**

**I followed Kate's e-mail regarding the model update for python and cmake, and updated modules accordingly in GSI/modulefiles/modulefiles.ProdGSI.hera:**
```
# python
module use -a /contrib/anaconda/modulefiles
module load anaconda/2.3.0

module use -a /contrib/cmake/modulefiles
module load cmake/3.9.0
```

**During the build process, I ran into the following error message:**

```
Configuring utility in adderrspec.fd
Configuring utility in adjustps.fd
Configuring utility in calc_increment_ens.fd
Configuring utility in calc_increment_serial.fd
Configuring utility in getnstensmeanp.fd
Configuring utility in getsfcensmeanp.fd
Configuring utility in getsfcnstensupdp.fd
Configuring utility in getsigensmeanp_smooth.fd
Configuring utility in getsigensstatp.fd
 hey, incl dirs are /apps/intel/compilers_and_libraries_2018/linux/mpi/intel64/include/gfortran;/apps/intel/compilers_and_libraries_2018/linux/mpi/intel64/include 
Configuring utility in gribmean.fd
Configuring utility in recenternemsiop_hybgain.fd
Configuring utility in recentersigp.fd
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FRAMEMODULE
    linked by target "global_gsi.x" in directory /scratch1/NCEPDEV/da/Emily.Liu/JEDI-GSI/GSI/src/gsi
FRAMEPACK
    linked by target "global_gsi.x" in directory /scratch1/NCEPDEV/da/Emily.Liu/JEDI-GSI/GSI/src/gsi
IOINT_LIB
    linked by target "global_gsi.x" in directory /scratch1/NCEPDEV/da/Emily.Liu/JEDI-GSI/GSI/src/gsi
WRFNETCDF_LIB
    linked by target "global_gsi.x" in directory /scratch1/NCEPDEV/da/Emily.Liu/JEDI-GSI/GSI/src/gsi

-- Configuring incomplete, errors occurred!
```

**I also checked out GSI master from gerrit:ProdGSI and modified the modulefiles as described above. The GSI build process completed successfully on HERA.**

**I am wondering if I missed something when I tried to build the GSI master checked out from GitHub?**

**Comment by RussTreadon-NOAA** [comment]
Did you clone via "_git clone https://github.com/NOAA-EMC/GSI.git ._"?  

_fix_ and _libsrc_ point to submodules.   Please include "_--recursive_" to clone the submodules.  That is, execute "_git clone --recursive https://github.com/NOAA-EMC/GSI.git ._"

Try executing the following in /scratch1/NCEPDEV/da/Emily.Liu/JEDI-GSI/GSI
"_git submodule update --init --recursive_"

After this "_cd ush_" and execute "_./build_all_cmake.sh_"

Following the above steps in my copy of /scratch1/NCEPDEV/da/Emily.Liu/JEDI-GSI/GSI yielded a complete build on Hera.

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA Thanks a lot. The build works for me now.

**Comment by RussTreadon-NOAA** [comment]
Build works.  Issued closed.
