### ISSUE TITLE
Changes to updating of bias correction variances

### ISSUE THREAD

**Issue by jderber-NOAA** [NOAA-EMC/GSI#170]
While looking at issue 154 (convergence issues), it was noted that in certain cases the convergence was much worse in the second outer iteration than the first.  There is no good reason for this unless there was a large change in the observations used in the outer iteration.  We do not see a large change in the number of observations so there must be another reason.  Looking at the code from one outer iteration to another it was noted that there was a new routine added "reset_predictor_vars".  By resetting the variances an inconsistency between the definition of xhatsave and yhatsave was introduced.  It was also noted that the updating of the variances was confused.  

Modifications were made to the code to remove the call to the reset_predictors_var routine and other changes were made to the updating of the variances.  The code was simplified to:

1. initialize the variances for new observations (new tail numbers, new instruments ) to 10000.  This is basically saying that there is no information in the guess.
2. Update the variances at the beginning of the analysis with consistent factors.  The code updated the variances differently dependent on the number of observations available.  This does not really make sense since the update to the variances is being done because of the uncertainty of the variances from one analysis time to the next.  The number of observations enter into the next step.
3. The number of observations and other values in rstats (and rstats_t)  are used to update the variances in pcinfo.  This routine is called each outer iteration and accounts for changes from one outer iteration to the next for the change in the number of observations used.
4. Default values for the variances are set to 10000.  rather than zero.  A maximum on the variance is also set to 10000.  This says that when insufficient data or zero data are available, the variance is a large number rather than zero.

**Comment by jderber-NOAA** [comment]
Changes are put into branch biasvar.

In occasional cases where the convergence is bad in the second outer iteration, these changes appear to eliminate convergence issues.

**Comment by jderber-NOAA** [comment]
It was also noted that the use of a minimum value in compute_derived and update_guess makes xhatsave and yhatsave inconsistent.  The minimum value for qmin was removed from compute_derived.  In update_guess, the minimum values (qmin and tgmin) were only applied in the last outer iteration (jiter = jiterlast).

**Comment by MichaelLueken** [comment]
Hi @jderber-NOAA.  Looking through the updates made to the authoritative repository, it looks like changes associated with this issue were merged at [d13b3f8](https://github.com/NOAA-EMC/GSI/commit/d13b3f82d1e140f15b248b7c5ea651ec8cd82b80) from PR #242.  Is it safe to close this issue?

**Comment by jderber-NOAA** [comment]
Mike,

Yes!  You are correct this issue can be closed.

John

**Comment by MichaelLueken** [comment]
@jderber-NOAA Thanks for the confirmation!  Will close this issue now.
