### ISSUE TITLE
Built  on Hera, the bufr missing (bmiss) assigned in GSI doesn't match  the actual missing value used by bufr lib

### ISSUE THREAD

**Issue by TingLei-NOAA** [NOAA-EMC/GSI#171]
In obsmod.F90, there is :
`! Set bufr missing value
#ifdef ibm_sp
  real(r_kind), parameter:: bmiss = 1.0e11_r_kind
#else
  real(r_kind), parameter:: bmiss = 1.0e9_r_kind
#endif`
On hera, the second value 1.0e9_r_kind is used, which does not match the actual missing value 1.0e11 used in bufr.  When running oneobtest in debug mode,  GSI would abort in ipks.f of bufr (see Bufr issue: https://github.com/NOAA-EMC/NCEPLIBS-bufr/issues/146) .As Jeff Ator Suggested, it is better to use the bufr intrinsic  function getbmiss to setup the bmiss in GSI (has been tested) or to use bufr setbmiss to make bufr lib use the same missing value.   
 For real data GSI runs, This seems not an issue. Because, 1)as I checked,  for regular GSI runs, it is used in read subroutines and "less than" rather than exact "equal"  relation in association with this missing value is used. 2) for those reading step, the bufr missing value should match the bufr lib generating those observations and the missing values should be consistent with the bufr lib invoked by GSI.   So, another solution is to use the current bmiss in GSI and use bufr intrinsic function setbmiss to force bufr lib linked to GSI to use the same missing value. 
 The changes (if needed)  for bmiss for real data (the whole GSI ) is beyond what this issue is concerned . 

 This issue focuses on oneobtest. Hence, currently, the getbmiss  would be used in oneobtest to get a local variables to be used as the missing value to generate the faked bufr observation.  it will not cause any changes to  bmiss. 
IF GSI developer team agree, I can push back my local modification for oneobtest described above for oneobtest into repository.

**Comment by TingLei-daprediction** [comment]
An update:  
the current version is: https://github.com/TingLei-daprediction/GSI/tree/feature/GSI_oneobtest 
Only regression test rtma  failed for not reproducible issue for difference from tcamt . for details see the attached. 
The rtma could be taken as a good test case to see what caused such a difference.
[Ecm-note-bmiss-failed ctest.docx](https://github.com/NOAA-EMC/GSI/files/6718339/Ecm-note-bmiss-failed.ctest.docx)

**Comment by TingLei-NOAA** [comment]
An update:  with Jacob's help,  some further investigation reveal what caused the rtma regression test fail.  When abs( obs_value - bmiss) < tiny_number is used in either data reading or setup stages to identify the bad obs, the mismatch between bmiss ( on hera, it would be  set as 1E9) and the "actual" missing values used by bufr lib (getbmiss() give 1E11),  the bad obs would pass this screening.  Because of the QC step, those bad obs would not be used in the analysis. However, they would be used in determining how "dense" the observations are , namely, calculation of dup and, hence, affect the observation error tuning and the variational QC  process.  In the rtma regression test, it was found, for tcamt,  the finally accepted obs groups were not the same in the control and update run.  Potentially, this situation could also happen for other observation data.   It will be helpful for RTAM developers take a look into this issue and it can decided if we formally accept the current update run as the new control run
