### ISSUE TITLE
Possible erroneous counts in ConMon

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [NOAA-EMC/GSI#172]
The ConMon has been issuing warnings about low counts from q187 which don't match either the plotted results or the gsistat numbers.  The time series count plots are significantly lower than the gsistat numbers and the warning messagess indicate numbers that are lower still.

**Comment by EdwardSafford-NOAA** [comment]
@RussTreadon-NOAA conducted the initial investigation from the gfs 2021060518 run.  The numbers for q187 observations are:

- 43788 per the gsistat file
- 2810 per the ConMon warning message

I added some debug and re-ran the ConMon for that cycle.  The ConMon reports the q187 numbers as:

- 18230 initial count and
- 2810 after removing duplicates

I ran ncdump to get a count of q187 obs (>ncdump -v Observation_Type -l 10 diag_conv_q_ges.2021060518.nc4 | grep 187 | wc -l):

- 18230 

So two questions.  

1. Why do the cnvstat and gsistat files differ so much for q187 numbers?  
2. Is the ConMon's "remove duplicates" operation too restrictive?

I'll work them in that order.

**Comment by EdwardSafford-NOAA** [comment]
The disparity in total numbers between the diag_conv_q_ges.2021060518.nc4  and the gsistat report seems to be unique.  The total numbers of obs for q, t, and ps types are:

            diag_conv_*_ges.2021060518.nc4                              gsistat
all q                  65901                                                             95526
all t                  207674                                                          207648
all ps                 94318                                                             94318

**Comment by RussTreadon-NOAA** [comment]
Thanks, Ed.   This is very interesting.   I agree with you.  Something isn't right.   We need to examine the GSI code.   I'm adding @XiujuanSu-NOAA , to this issue.   She may have some insights.

**Comment by EdwardSafford-NOAA** [comment]
This is the code block for determining duplicate observations:

` 
match = 10.0e-5

         dlat=abs(duparr(ilat,i)-duparr(ilat,jj))
         dlon=abs(duparr(ilon,i)-duparr(ilon,jj))
         dtime=abs(duparr(itime,i)-duparr(itime,jj))
         dpress=abs(duparr(ipress,i)-duparr(ipress,jj))

         if (dlat < match .and. dlon < match .and. dtime < match &
             .and. dpress < match ) then
! this is a duplicate obs
`

**Comment by EdwardSafford-NOAA** [comment]
Finding nothing obviously wrong with the ConMon I re-ran the script that creates the file of average counts.  Two cycles have now run using that updated count information and q187 has not produced any low count warnings.

**Comment by RussTreadon-NOAA** [comment]
**BUG in setupq.f90**

In setting up a parallel to test TAC to BUFR (T2B) dump files it was discovered that the number of q observations reported in `gsistat` was greater than the number of q observations reported in `enkfstat`.  This is not correct.   

The GSI selects observations to be used by the EnKF update code.   These observations are passed to the EnKF update code via diagnostic files.   GFS v16 writes netcdf diagnostic files.   The EnKF update code reads the netcdf files.   The number of observations read by the EnKF update code should be identical to the number selected by the GSI.   

This consistency was not found in the T2B case examined, 2021061406.   File `gdas.t06z.gsistat.ensmean` reported `7442` q observations selected for assimilation.   File `gdas.t06z.enkfstat` reported `5381` observations read from the netcdf conventional data diagnostic file.  

Examination of `src/gsi/setupq.f90` identified a bug in subroutine `init_netcdf_diag_`.    Logic in the routine checks to see if the output diagnostic file already exists.  If it does, logical flag `append_diag` is set to `.true.`.  This optional argument **_should be passed_** to subroutine `nc_diag_init` to correctly set the file pointer.   The `nc_diag_init` call in `setupq` **_did not include_** the optional argument `append_diag`.

GSI namelist `OBS_INPUT` for GFS v16 lists three sources of q observations

   `prepbufr       q           null        q                   0.0     0     0`
   `prepbufr_profl q           null        q                   0.0     0     0`
   `hdobbufr       q           null        q                   0.0     0     0`

When processing data from multiple bufr files it is necessary to set `append_diag` to `.true.` on subsequent calls to `setupq`.  This does not happen in the current version of `setupq.f90`.

The missing optional argument `append_diag` was added to `nc_diag_init` in `setupq`.  The GSI was recompiled and the 2021061406 case rerun.   File `gdas.t06z.gsistat.ensmean` still reported `7442` q observations.    File `gdas.t06z.enkfstat` also reported `7442` q observations.

A check of other setup routines found a similar error in three other files:  `setupcldtot.F90`, `setuplwcp.f90`, `setupswcp.f90`.   The missing `append_diag` argument was added to the `nc_diag_init` call in these routines.   I do not have data to test if these updated routines now correctly write all observations to netcdf diagnostic files.

This error exists in the operational GFS v16.1.1a package.   A check of archived `gsistat*ensmean` and `enkfstat` files for GFS v15 and v16 implementations indicates that the error originated with GFS v16.   

This bug will also impact ConMon.   The `diag_conv_q` netcdf file read by ConMon will not contain the full set of q observations processed by the GSI (and reported in `gsistat`).

**Comment by RussTreadon-NOAA** [comment]
PR #176 brought the changes to `setupq.f90` described above into the master.  Thus, this issue may be closed.

**Comment by EdwardSafford-NOAA** [comment]
Per Russ' PR [#176](https://github.com/NOAA-EMC/GSI/pull/176) fixing setupq.f90, I'll close this issue.  The few, small changes I had made will be incorporated into issue #62.
