### ISSUE TITLE
GFS DA v16.1.1a

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GSI#173]
GFS v16.1.1a was implemented as an accelerated RFC effective 2021052812.   This ARFC placed all CrIS-FSR NPP channels in monitor mode.   

Details regarding the CrIS-FSR NPP anomaly and the changes implemented as GFS v16.1.1a are provided [Implementation_Instructions_monitor_CrIS_NPP](https://docs.google.com/document/d/1nnhe9H1I0dmJO6zS4CuBeOFWzl6ZRtRnyf1yRVbNMCg/edit).  Please see NESDIS operational message [MSG152202402](https://www.ospo.noaa.gov/data/messages/2021/MSG152202402.html) for additional details regarding the instrument anomaly along with an event timeline.  

The CrIS-FSR NPP ARFC  also updated satinfo files used by the HRRR (Alaska domain only), HWRF, and RAP.   This issue does **_NOT_** address these DA systems.  This issue is limited to the GFS.  

This issue only documents creation of GFS DA tag gfsda.v16.1.1a with the updated global_satinfo.txt file.

**Comment by RussTreadon-NOAA** [comment]
Tag [gfsda.v16.1.1a](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.1.1a) will be used in global-workflow [release/gfsv16.1.2](https://github.com/NOAA-EMC/global-workflow/tree/release/gfsv16.1.2).   See global-workflow [PR #335](https://github.com/NOAA-EMC/global-workflow/pull/335) for additional details.

**Comment by MichaelLueken-NOAA** [comment]
The updated global_satinfo.txt file and new gfsv16_historical/global_satinfo.txt.2021052118 to the authoritative repo at 18afa96.  Closing this issue.

**Comment by RussTreadon-NOAA** [comment]
The RFC Memo for 6/11/2021 mentions the CrIS-FSR NPP ARFC.   This text is included below for the sake of completeness.

_RFC 8260 - On WCOSS, placed CrIS NPP channels in monitor mode for the GFS,
HRRR, HWRF, and RAP models. This was done to minimize possible degraded
analyses due to the CrIS NPP data anomaly/outage that began on May 21, 2021.
Implemented on May 28 at 1145Z._
