### ISSUE TITLE
Port to S4

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/GSI#177]
The GSI should be ported to SSEC's S4 cluster to support UFS and DA research efforts on that system.

**Comment by DavidHuber-NOAA** [comment]
I have committed a set of changes to update support for the GSI on S4, based on [9c1fc15d](https://github.com/NOAA-EMC/GSI/commit/9c1fc15d42573b398037319bbf8d5143ad126fb6)  These changes have been tested on S4 by running the global workflow for a test case running from 2020073118 through 2020081000 @192/96 resolution.  The logs and data are available on Orion:
logs - /work/noaa/nesdis-rdo2/dhuber/s4_logs/test_dev
comrot (for 2020081000 only) - /work/noaa/nesdis-rdo2/dhuber/s4_data/comrot/test_dev
archive - /work/noaa/nesdis-rdo2/dhuber/s4_data/archive/test_dev

A 4-day test run from 2020073118 through 2020080400 at 384/192 resolution has started.

@MichaelLueken-NOAA Before proceeding with a PR, are there any data you would like to have attached for this issue or any other test cases you would like to see?  I can upload the 384/192 data and logs when the test run is complete if needed.  S4 is not capable of running the 768/384 resolution workflow.

Note that I am unable to run the regression tests on S4 as the CASES contain restricted data, which are not allowed on S4.  If there is a non-restricted version of these test cases, could you please forward a location to me?  If not, then I can remove S4 from the regression test scripts, either under this issue or another, whichever you prefer.

Once these tests are complete, I will merge in the current NOAA-EMC master branch and perform a test build.  I'm not sure if the global-workflow can support this version of the GSI, but I can try running a short test case if you think that's needed.

**Comment by MichaelLueken-NOAA** [comment]
@DavidHuber-NOAA There are no special data or test cases that I need to see uploaded to this issue before creating a PR for this work.

Unfortunately, there are no non-restricted versions of the regression test canned cases.  If restricted isn't allowed on S4, it will probably be fine to remove S4 from the regression test scripts.
