### ISSUE TITLE
Port GSI (tag: gfsda.v16.0.0) for GEFS v12 to Acorn/WCOSS2

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/GSI#183]

**Comment by MichaelLueken-NOAA** [comment]
@XianwuXue-NOAA The necessary changes to allow the GSI to compile on Acorn can be found in:

https://github.com/MichaelLueken-NOAA/GSI/tree/feature/ACORN_port

specifically, hash 917f6f8.

**Comment by XianwuXue-NOAA** [comment]
Thanks Mike. I found you also ported it to Acorn. I just sent an email to you about that. I am wondering, did you count the issues during the porting? Because some libs missed IN4 and LIB4.

    export SIGIO_INC4=$SIGIO_INC
    export SIGIO_LIB4=$SIGIO_LIB
    export GFSIO_INC4=$GFSIO_INC
    export GFSIO_LIB4=$GFSIO_LIB
    export SFCIO_INC4=$SFCIO_INC
    export SFCIO_LIB4=$SFCIO_LIB

**Comment by MichaelLueken-NOAA** [comment]
@XianwuXue-NOAA No, I don't encounter the issue with INC4 and LIB4.  The changes I made with respect to cmake/Modules/setHOST.cmake and platforms/Acorn.cmake get around these issues.  Are the changes in:

https://github.com/XianwuXue-NOAA/GSI/tree/feature/gfsda.v16.0.0_port2acorn

Meant to be for gfsda.v16.0.0, gfsda.v16.1.0, or gefs_v12?

If it is for gefs_v12, then I'd recommend creating your feature branch off of the authoritative repository's release/gefs_v12.  If it is for gfsda.v16.0.0, we are past that.  The new release branch, release/gfsda.v16.1.0, in the authoritative repository, should be what you use (since this is what is currently in operations).

**Comment by XianwuXue-NOAA** [comment]
I ported GSI for GEFS based on the tag "gfsda.v16.0.0", instead of branches. However, I don't know why we use the tag "gfsda.v16.0.0" instead of release/gefs_v12. I will compare the branches.

**Comment by XianwuXue-NOAA** [comment]
@MichaelLueken-NOAA I checked the GSI using in GEFSv12.1.1 on nwprod, and it does not have the the six common_grads_* files. So my compilation should be OK on Acorn and generated same files. However, I tried to use your changes in your branch and it failed again. After I add "module load curl/7.72.0" and  the statements below and it can be built successfully.
       export SIGIO_INC4=$SIGIO_INC
 	export SIGIO_LIB4=$SIGIO_LIB
 	export SFCIO_INC4=$SFCIO_INC
 	export SFCIO_LIB4=$SFCIO_LIB

**Comment by XianwuXue-NOAA** [comment]
I also tried merge the release/gefsv12 into my branch and it has a lot of conflict. If we must create a new branch, I think we should use another name instead of the original release/gefsv12. In fact, GEFS only uses three programs from GSI: getsigensmeanp_smooth.x, getsfcensmeanp.x and calc_increment_ens_ncio.x, and I compared  the master with tag "gfsda.v16.0.0", it seems that there is only minor/no changes for these three programs. Therefore, I may try to use the master to see whether it can work.

**Comment by MichaelLueken-NOAA** [comment]
@XianwuXue-NOAA If the master works for GEFSv12.1.1 work, then I can create a new release branch for you in the authoritative repository, using the master branch.  Please let me know and I can set this up for you.

**Comment by XianwuXue-NOAA** [comment]
@MichaelLueken-NOAA I checked your GSI repo and the EMC/master, and found there are a lot of code changes which NCO does not want to have too many codes changes for this WCOSS2 code transition. I also checked the tag: gfsda.v16.0.0, and found it was updated from commit: 89f85ed on Oct 6, 2020 to commit: 6361a30976 on Jan 25 2021 with some code changes. So could you create a new branch "release/gefs_v12" based on commit: 89f85ed which is used by the current GEFS v12.1.3 on production? Then I will submit a PR to merge my changes to this branch for the next GEFS v12.2.0 on WCOSS2. Thanks a lot in advance.

**Comment by MichaelLueken-NOAA** [comment]
@XianwuXue-NOAA I have created release/gefs_v12 from 89f85ed and pushed it to the authoritative repo.  Once you have finished porting to WCOSS2, I will approve your to update this new release branch.

**Comment by XianwuXue-NOAA** [comment]
@MichaelLueken-NOAA Thank you very much for your consideration. I double checked the production and found the commit id should be "4b29d045" on Nov 9 2020. "89f85ed" was the commit ID for tag: gfsda.v16.0.0 when I built global-workflow for development use. I am sorry for the confusion.

**Comment by MichaelLueken-NOAA** [comment]
@XianwuXue-NOAA  I have remove release/gefs_v12 and replaced it with another created from hash 4b29d045 and pushed to the authoritative repo.

**Comment by XianwuXue-NOAA** [comment]
@MichaelLueken-NOAA Awesome. Thank you very much for your consideration and help.
