### ISSUE TITLE
feature/files_for_jedi

### ISSUE THREAD

**Issue by emilyhcliu** [NOAA-EMC/GSI#19]
@CoryMartin-NOAA I have cloned branch feature/files_for_jedi_aop20 from your feature/files_for_jedi.
I made some changes and additions in ffiles_for_jedi_aop20.   Could you take a look at the changes in the branch?  I will merge the changes back to feature/files_for_jedi once you give an OK.  

The changes I made compare to feature/files_for_jedi can be found from the following link:
https://github.com/NOAA-EMC/GSI/compare/feature/files_for_jedi...emilyhcliu:feature/files_for_jedi_aop20

**Comment by CoryMartin-NOAA** [comment]
Emily,

We need to have a discussion probably about who will house the files_for_jedi branch, as I believe all non-release branches will be removed from the main GSI repository soon. Do you want to own the forked branch, or should I? I'm happy with letting your emilyhcliu:feature/files_for_jedi_aop20 be the "master" repository/branch for this purpose.

**Comment by emilyhcliu** [comment]
@CoryMartin-NOAA 
I would like you to house the feature/files_for_jedi if you do not object.  I will add my changes and addition through files_for_jedi_aop20 and then merge back to feature/files_for_jedi.  I will do the work.  You just sit back and look at the changes/addition and give me some feedback.

As EMC getting more involved in UFO development, more EMC people will also make contributions to feature/files_for_jedi.  It is better to have an EMC person like you to watch over the development.  How about that you house the feature/files_for_jedi, and I will check issues from people related to feature/files_for_jedi and make sure the changes do not break the branch and then merge?

The following is just a thought, not something we would face soon.  
The current feature/files_for_jedi is for current operational configuration.  I am wondering if we should create another files_for_jedi for v16 for people who want to make sure their implementation can be transitioned to UFO correctly, or maybe the v16 will be operational soon.  Do you think it is easy to update the current feature/files_for_jedi to master?  It is way behind the master/.

**Comment by CoryMartin-NOAA** [comment]
Hi @emilyhcliu , please submit a pull request to this branch in my forked repository:
https://github.com/CoryMartin-NOAA/GSI/tree/feature/files_for_jedi

I will house the JEDI master branch for GSI for the time being.

What do you mean about creating another for v16? Do you mean to support netCDF backgrounds? If I merge in the master then it (should) support v16 and v15.

**Comment by emilyhcliu** [comment]
@CoryMartin-NOAA Thanks.  I will submit a PR today.
OK, I see.  We can merge the master into feature/files_for_jedi when it is necessary.
