### ISSUE TITLE
Add external declarations to source code to allow the GSI and EnKF to compile in debug mode without warning messages on Acorn

### ISSUE THREAD

**Issue by MichaelLueken** [NOAA-EMC/GSI#192]
While compiling in debug mode on Acorn, there are warning messages regarding not declaring EXTERNALS in the GSI and EnKF.  I am working through the code and adding external declarations to all GSI and EnKF routines that are flagged with this warning message.

**Comment by MichaelLueken-NOAA** [comment]
08/02/2021 - 08/06/2021

Updated modulefiles/modulefile.ProdGSI.acorn and ush/build_all_cmake.sh to work with the latest changes made to the modules on Acorn.

The code compiles in debug mode through 51% of total compilation.  Completed through src/gsi/calctends_tl.f90.

**Comment by MichaelLueken-NOAA** [comment]
08/09/2021 - 08/13/2021

Pushed commit 13ddc62, which completed the declaration of externals for the GSI and began declaring externals for the EnKF.  Will complete EnKF declarations next week.
