### ISSUE TITLE
GSI code fix to handle the new in situ (ships) bufr subsets in nsstbufr observation data file

### ISSUE THREAD

**Issue by XuLi-NOAA** [NOAA-EMC/GSI#208]
A ObsProc upgrade was implemented at 2021180600 GFS cycle. This introduced three new ships data, NC001013, NC001101 and NC001113, into sfcshp and therefore nsstbufr data file. The GSI code can handle the known (by GSI decoder) subsets correctly, but not for the unknown (new) subsets. The code, read_nsstbfr.f90, needs to be modified to handle the new subsets. Otherwise, as shown in GFS production, the NSST analysis can be degraded since some bad (not the true observation) data can be assimilated. The significant impact occurred over North Sea area (by UK), the foundation temperature becomes too cold by up to 6+ degree after about one week of the OpsProc upgrade implementation. 

The modification of read_nsstbufr.f90 is straightforward, just add those three subsets. 

The cycling run, starting from 2021083118, with the operational version of GFS, v16.1.2.1, at C768, is running. From the 12 cycles already done, it shows the too cold Tf analysis over North Sea is getting warmer, it may take about one week cycling run to become normal.

**Comment by MichaelLueken-NOAA** [comment]
These changes were merged to release/gfsda.v16.1.3 at 972d545.  Closing issue.
