### ISSUE TITLE
Port RadMon to wcoss2

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [NOAA-EMC/GSI#226]
Port RadMon DA package to wcoss2.

**Comment by EdwardSafford-NOAA** [comment]
I have the RadMon build working now.  Somehow my local copy of modulefiles/modulefile.ProdGSI.wcoss2 contained these two lines:
`module load hdf5-hdf5_parallel/1.10.6
module load netcdf-hdf5_parallel/4.7.4`

I can't remember now where/how I got that file.  But if I change those two lines to:
`module load hdf5/1.10.6
module load netcdf/4.7.4`

then the build works.

**Comment by MichaelLueken-NOAA** [comment]
@EdwardSafford-NOAA None of the WCOSS2 port work should be merged to the authoritative master at this time.  I will create a new wcoss2 release branch off of release/gfsda.v16.1.5 and we will apply all changes to this release branch, tag it once everything is worked out, then merge the release branch to the master.
