### ISSUE TITLE
Fix indexing issues with correlated error in V16.x

### ISSUE THREAD

**Issue by KristenBathmann** [NOAA-EMC/GSI#233]
A recent update to release/gfsda.v16.x allowed for flexibility in channel selection in the satinfo while preserving correlated error. Testing with GDAS was successful, but testing with GFS failed. This is because the gfsanal and gdasanal use different channel indices. The gfsanal completely ignores monitored channels and generates a satinfo file that does not contain them. 

Each covariance file is generated as 
open(26,file=trim(cov_file),form='unformatted')
write(26) nch_active, nctot, reclen
write(26) indR
write(26) Rcov
close(26)
nch_active is the number of active channels, for example 174 for IASI
nctot is the total number of channels, for example 616 for IASI
indR are satinfo relative indices, for example 1, 5, 9, 11... for IASI. These would correspond to channels 16, 38, 49 and 51.
Rcov is the covariance matrix. 

The correlated obsmod in the master has logic in various routines to handle the inconsistency in channel indexing between the gfsanal and the gdasanal. The update to the set_routine in correlated_obsmod.F90 build a covariance matrix from the file based on the channels in the satinfo. Because of the way the channel indices are specified in the covariance file (1,5,9,11 rather than 16,38,49,51) there is no way for set_ to know which channel has been removed or added in the satinfo, and won't know which entries in Rcov to use. Fixing this issue will therefore require changing the indices in the covariance file (to 16,38,49,51,...), changing correlated_obsmod.F90 and updating the covariance utility util/Correlated_Obs to write the files correctly.

To make matters more complicated, GMAO does not have this indexing issue in their code, and the logical GMAO_ObsErrorCov will need to be used in set_.

**Comment by KristenBathmann** [comment]
This work is being done in my fork KristenBathmann/GSI, in release/gfsda.v16.x
The util/Correlated_Obs directory in here is very out of date with the master. Care will need to be taken when merging this code into the master.

**Comment by ADCollard** [comment]
So just so I am clear what you are suggesting, Russ.

Should we 
1) Merge the master into v16.x
2) Merge 16.x back into the master
3) Introduce the latest changes that Kristen has introduced today into the master at this point?

I will work on Step #3 once the other two are complete.

**Comment by RussTreadon-NOAA** [comment]
Test rerun with Rcov files from `/gpfs/dell2/emc/modeling/noscrub/Kristen.Bathmann/GSI/fix/`.     Now see the following in stdout
```
Rcov(Evals) for Instrument: iasi_metop-b:sea  cond=      6.8648778493E+01
Rcov(Evals) for Instrument: iasi_metop-b:land  cond=      1.5388534575E+02
Rcov(Evals) for Instrument: cris-fsr_n20:sea  cond=      3.6394468822E+01

```

The updated Rcov files need to be committed.

**Comment by KristenBathmann** [comment]
Using my updated fork copy requires the updated Rcov files, and this *should* work for both gdas and gfs. Using the current authoritative release/gfsda.v16.x requires the old Rcov files, but will only work for gdas.

**Comment by KristenBathmann** [comment]
Yes, you should expect the differences that you observed. If you rerun the gdasanal with the authoritative release/gfsda.v16.x and the old Rcov files, the result should be identical to using my fork with the new covariance files.

**Comment by ADCollard** [comment]
There's one difference not from Kristen.  John added an extra line to genqsat.f90 that is not in Kristen's branch.  And I'm guessing that might be more likely to produce the change we've seen.

Should I just go ahead and add it and then you can rerun?

**Comment by RussTreadon-NOAA** [comment]
Just to confirm that with the `genqsat.f90` change @ADCollard noted, Kristen's [release/gfsda.v16.x](https://github.com/KristenBathmann/GSI/tree/release/gfsda.v16.x) at 9a41e68 reproduces analysis increments from the authoritative  [release/gfsda.v16.x](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16.x) at 23abb36 for 2021101600 gdas.   For example, here is a `compare_ncfile.py` difference for `siginc.nc`:

```
/gpfs/dell2/ptmp/emc.glopara/tmp766> compare_ncfile.py kristen_gdas.2021101600.update_genqsat/siginc.nc gfsda.v16.x_gdas.2021101600/siginc.nc
lon min/max 1=0.0,359.766 min/max 2=0.0,359.766 max abs diff=0.0000000000
lat min/max 1=-89.8207,89.8207 min/max 2=-89.8207,89.8207 max abs diff=0.0000000000
lev min/max 1=1.0,127.0 min/max 2=1.0,127.0 max abs diff=0.0000000000
pfull min/max 1=1.0,127.0 min/max 2=1.0,127.0 max abs diff=0.0000000000
ilev min/max 1=1.0,128.0 min/max 2=1.0,128.0 max abs diff=0.0000000000
hyai min/max 1=1.0,128.0 min/max 2=1.0,128.0 max abs diff=0.0000000000
hybi min/max 1=1.0,128.0 min/max 2=1.0,128.0 max abs diff=0.0000000000
u_inc min/max 1=-39.3891,22.8589 min/max 2=-39.3891,22.8589 max abs diff=0.0000000000
v_inc min/max 1=-33.1067,20.7991 min/max 2=-33.1067,20.7991 max abs diff=0.0000000000
delp_inc min/max 1=-13.2386,15.8484 min/max 2=-13.2386,15.8484 max abs diff=0.0000000000
delz_inc min/max 1=-158.188,147.85 min/max 2=-158.188,147.85 max abs diff=0.0000000000
T_inc min/max 1=-14.6978,13.852 min/max 2=-14.6978,13.852 max abs diff=0.0000000000
sphum_inc min/max 1=-0.0090915,0.00732401 min/max 2=-0.0090915,0.00732401 max abs diff=0.0000000000
liq_wat_inc min/max 1=0.0,0.0 min/max 2=0.0,0.0 max abs diff=0.0000000000
o3mr_inc min/max 1=-2.29021e-06,2.19059e-06 min/max 2=-2.29021e-06,2.19059e-06 max abs diff=0.0000000000
icmr_inc min/max 1=0.0,0.0 min/max 2=0.0,0.0 max abs diff=0.0000000000
```
