### ISSUE TITLE
An NSST update package for GFSv16.x

### ISSUE THREAD

**Issue by XuLi-NOAA** [NOAA-EMC/GSI#235]
A few updates, addition of two VIIRS radiances, reduction of the thinning box size for AVHRR and VIIRS radiances, the use of Rossby radius of deformation as the correlation length, and the exclusion of the partly-clear AVHRR radiance, have been tested with GFSv15.2 at the full resolution and GFSv16.0 at C384.

**Comment by XuLi-NOAA** [comment]
The results of the experiment with GFSv15.2 at C768: 

[NSST_for_V16.2.pptx](https://github.com/NOAA-EMC/GSI/files/7643225/NSST_for_V16.2.pptx)

**Comment by MichaelLueken-NOAA** [comment]
@XuLi-NOAA, do you want this issue to be closed?  If it is related to PR #261, it should stay open until those changes have been merged to the master.
