### ISSUE TITLE
Port GFSv16.1.5 to WCOSS2

### ISSUE THREAD

**Issue by MichaelLueken-NOAA** [NOAA-EMC/GSI#246]
The feature/gfsda.v16.1.5_wcoss2_port was created from release/gfsda.v16.1.5 at 7c5af91.  All necessary changes to allow the GSIv16.1.5 implementation to compile and run on WCOSS2 will be applied to this feature branch.

**Comment by MichaelLueken-NOAA** [comment]
Currently, two more issues:

#225
#228

need to be completed before this work can be tagged for the GFSv16 WCOSS2 implementation (issue NOAA-EMC/global-workflow#398).

**Comment by EdwardSafford-NOAA** [comment]
@MichaelLueken-NOAA I don't think #228 needs to be completed prior to tagging the GFSv16 WCOSS2 implementation.  The ConMon is not yet in operations (I double checked gfs.v16.1.5).

**Comment by MichaelLueken-NOAA** [comment]
@EdwardSafford-NOAA Thanks for letting me know that #228 isn't required before the GFS v16.1.5 code can be tagged.  Hopefully WCOSS2 sys admins can add List:MoreUtils to WCOSS2 so that #225 can be wrapped up.

**Comment by MichaelLueken-NOAA** [comment]
Updated setHOST.cmake to find Dogwood and added the noexternal keyword to the -warn compiler options for WCOSS2 at 1c7c83f.

**Comment by RussTreadon-NOAA** [comment]
After replacing `ksh` with `bash`, the following for loop in `exglobal_atmos_analysis.sh` no longer works
```
      npe_m1="$(($npe_gsi-1))"
      for pe in {0..$npe_m1}; do
        pedir="dir."$(printf %04i $pe)
        mkdir -p $DIAG_DIR/$pedir
        $NLN $DIAG_DIR/$pedir $pedir
      done
```
Execution of the above loop in on Dogwood yields
```
2 + npe_m1=767
2 + for pe in {0..$npe_m1}
22 + printf %04i '{0..767}'
/lfs/h2/emc/da/noscrub/Russ.Treadon/git/global-workflow/feature-ops-wcoss2/scripts/exglobal_atmos_analysis.sh: line 621: printf: {0..767}: invalid number
2 + pedir=dir.0000
2 + mkdir -p /lfs/h2/emc/ptmp/Russ.Treadon/comrot/v16test/gdas.20210824/00/atmos/gsidiags/dir.0000
2 + /bin/ln -sf /lfs/h2/emc/ptmp/Russ.Treadon/comrot/v16test/gdas.20210824/00/atmos/gsidiags/dir.0000 dir.0000
```
Only directory `dir.0000` is created.   This is not correct.   Directories from 0000 up to 0767 should be created.

This problem affects both the gdas anal and eobs.    The error was discovered when eupd failed due to problems with the diagnostic files is read from eobs.

The for statement in the above loops is replaced with
```
      npe_m1="$(($npe_gsi-1))"
      for pe in $(seq 0 $npe_m1); do
        pedir="dir."$(printf %04i $pe)
        mkdir -p $DIAG_DIR/$pedir
        $NLN $DIAG_DIR/$pedir $pedir
      done
```
This was tested on Dogwood and works.  
```
2 + npe_m1=767
22 + seq 0 767
2 + for pe in $(seq 0 $npe_m1)
22 + printf %04i 0
2 + pedir=dir.0000
2 + mkdir -p /lfs/h2/emc/ptmp/Russ.Treadon/comrot/v16test/gdas.20210824/00/atmos/gsidiags/dir.0000
2 + /bin/ln -sf /lfs/h2/emc/ptmp/Russ.Treadon/comrot/v16test/gdas.20210824/00/atmos/gsidiags/dir.0000 dir.0000
2 + for pe in $(seq 0 $npe_m1)
22 + printf %04i 1
2 + pedir=dir.0001
2 + mkdir -p /lfs/h2/emc/ptmp/Russ.Treadon/comrot/v16test/gdas.20210824/00/atmos/gsidiags/dir.0001
2 + /bin/ln -sf /lfs/h2/emc/ptmp/Russ.Treadon/comrot/v16test/gdas.20210824/00/atmos/gsidiags/dir.0001 dir.0001
```
This change was committed to `feature/gfsda.v16.1.5_wcoss2_port` at 86c9753.

**Comment by MichaelLueken-NOAA** [comment]
Kate found an issue with bash treating the value, 08, as an octal in jobs/JGDAS_ENKF_FCST.  George and Russ came up with a fix that works for sh, ksh, and bash, replacing:

`export ENSEND=$((NMEM_EFCSGRP * ENSGRP))`

with:

`export ENSEND=$((NMEM_EFCSGRP * 10#${ENSGRP}))`

This change was committed and pushed to feature/gfsda.v16.15_wcoss2_port at 0fdf0d4

**Comment by MichaelLueken** [comment]
These changes were merged to the authoritative develop branch at [ad2a3c0](https://github.com/NOAA-EMC/GSI/commit/ad2a3c081e295c89a9c66aa3385f8e4c4779ff1a) and [1d475c8](https://github.com/NOAA-EMC/GSI/commit/1d475c88ed381f19e596c83bfa7f949ced789329).  Closing issue.
