### ISSUE TITLE
Port the ConMon to S4 and Jet

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/GSI#268]
The conventional monitor should be ported to S4 and Jet.

**Comment by DavidHuber-NOAA** [comment]
@EdwardSafford-NOAA @MichaelLueken-NOAA During the testing of this ConMon port I found a few bugs that I have fixed.  Most importantly, in `plot_horz.sh` and `plot_horz_uv.sh`, both scripts recompress the contents of the `tankdir` `ges` and `anl` subdirectories.  Since `plot_horz.sh` finishes first, this caused `plot_horz_uv.sh` to plot empty maps from that point onward.  I've thus removed the compression from `plot_horz.sh`.  Now that `plot_horz_uv.sh` takes the time to finish plotting, it requires more time to complete, so I've updated the requested time to 90 minutes.  I have not tested this on Hera and I don't have access to WCOSS to perform testing there.  Should this be tested and modified before opening a PR or can I go ahead?

**Comment by EdwardSafford-NOAA** [comment]
@DavidHuber-NOAA @MichaelLueken-NOAA I'm good with opening a PR now.   I'll follow up on hera and wcoss once it's in master; I've got a few items to take care of anyway and I'll add this to my list.  Are you good with that Mike?

**Comment by EdwardSafford-NOAA** [comment]
@DavidHuber-NOAA I had some time so I checked out your branch and ran your changes on wcoss and hera.  I had to change the wall time on the plot_horz_uv job on wcoss.  On hera it ran to completion as is.  The change I made locally was to the mk_horz_hist.sh script, line 105, changing the wall time from 00:20 to 01:00.  

Thanks very much for your work on this.

**Comment by DavidHuber-NOAA** [comment]
Great!  Thanks for checking @EdwardSafford-NOAA.  I've made the change and will go ahead with the PR.
