### ISSUE TITLE
Add capability to assimilate Saildrone, Argo & Glider  observation in GSI: NSST

### ISSUE THREAD

**Issue by XuLi-NOAA** [NOAA-EMC/GSI#270]
This issue is to add the capability to assimilate Saildrone, Argo and Glider sea water temperature observation in the NCEP GFS NSST. 
Background

1. Saildrone observation
    A new data in NC001120
2. Argo and Glider observation
    The data in NC031005 or subpfl, which include Argo and Glider.  
    Argo data used to be in Tesac and used in GFS NSST, but was removed from Tesac and put into a new data file, subpfl, and not used in GFS anymore since then. 
    Glider data is new.
3. GSI code change
    Only one file, read_nsstbufr.f90 needs to be modified.
    No scripts or fix files need to be updated. 
4. Observation preparation for GFS cycle
    ObsProc scripts needs to be updated.

**Comment by XuLi-NOAA** [comment]
The two cycling runs described as above have been done 4 cycles. 00Z, 06Z, 12 Z and 18 Z, Jan. 16, 2022. 

![Saildrone_Coverage_vomb1_stat1_v16nst5_190_anl_Global_all_used_00Z16Jan2022_00Z16Jan2022](https://user-images.githubusercontent.com/55100838/150867130-47dccf2b-365f-4de3-a689-dff6df2f7f5c.png)

**Comment by XuLi-NOAA** [comment]
![Argo_Glider_Coverage_vomb1_stat1_v16nst5_199_anl_Global_all_used_00Z16Jan2022_00Z16Jan2022](https://user-images.githubusercontent.com/55100838/150867174-e628fc1e-220c-40f9-8e5d-672419e34e2d.png)

**Comment by XuLi-NOAA** [comment]
![Tf_diff_Global_v16nst5_v16nst4_map_00Z16Jan2022_p1](https://user-images.githubusercontent.com/55100838/150867206-1f066d34-fb67-4c47-beac-5ce99f1ea939.png)

**Comment by XuLi-NOAA** [comment]
![Tf_diff_Global_v16nst5_v16nst4_map_18Z16Jan2022_p1](https://user-images.githubusercontent.com/55100838/150867228-a03285a9-50e4-43dd-90c8-fa9b6df8213a.png)

**Comment by XuLi-NOAA** [comment]
@ MichaelLueken-NOAA

The regression tests (on hera) have been done and three of them failed:
The following tests FAILED:
          6 - global_fv3_4denvar_C192 (Failed)
         13 - hwrf_nmm_d2 (Failed)
         14 - hwrf_nmm_d3 (Failed)

I can see the runtime
*  Too long for hwrf_nmm_d2  and hwrf_nmm_d3
* Nonreproducible results for global_fv3_4denvar_C192, this is expected. 

How to move ahead?

**Comment by MichaelLueken-NOAA** [comment]
@XuLi-NOAA 

So long as the nonreproducible results for global_fv3_4denvar_C192 are expected, then you are done, unless a reviewer or me asks for changes to be made to the code.
