### ISSUE TITLE
Enhance non-var cloud analysis 

### ISSUE THREAD

**Issue by hu5970** [NOAA-EMC/GSI#282]
In past several years, several improvements to the non-var cloud analysis have been made by GSL and EMC for RAP/HRRR, 3DRTMA, and RRFS:

1) more options to decide how to do T/Q adjustment based on the cloud information.
2) check and adjust Qr/qs/qg and Qnr for each vertical profile to reduce the background reflectivity ghost in final analysis
3) Add function to build a vertical depended cloud range for METAR cloud observations. 

More options to build q innovation based on the cloud information. This is not part of non-var cloud analysis but is closely related.

**Comment by StanBenjamin** [comment]
Ming,  Are all of these changes introduced with namelist options so that the effect of the original code can be replicated?   I think that is needed?   And if/when you have that option, can you add graphics for a 3-way comparison:  1) original code, 2) new code with namelist set to give effect of original code, 3) new code with namelist variations to show new effect?

**Comment by hu5970** [comment]
Stan,
Yes, all of the changes introduced with the namelist options. Mike has run the regression suite (including RAP/HRRR cases) for this new code and got identical results. I think the regression tests satisfy the 1 and 2 to make sure the new code does not impact the original functions.

The enhanced functions listed in this issue and PR includes all the cloud analysis related developments in the past one or two years. Those code are from the GSL/GSI development branch, which are used for 3DRTMA, RRFS, and some RAP/HRRR development after operation. This PR is to sync the GSL/GSI develop branch with EMC master to give us a new base for future GSI development for RRFS. If we need to recheck and tune those new function, we need to work with GSL/GSI develop branch after sync with master branch.
