### ISSUE TITLE
Thinning box size definition for EnKF in config.eobs

### ISSUE THREAD

**Issue by MichaelLueken-NOAA** [NOAA-EMC/GSI#296]
From issue [#595](https://github.com/NOAA-EMC/global-workflow/issues/595) in global-workflow, created by Xu:

In config.eobs,

there is a line

export OBSINPUT_INVOBS="dmesh(1)=225.0,dmesh(2)=225.0,"

to set the thinning box size to be 225 km, for dmesh(1) and dmesh(2).

However, there will be four defined thinning box sizes, including dmesh(3)=100 (km) and dmesh(4)= 70 in exglobal_atmos_analysis.sh,

dmesh(3) is applied to amsr2_gcom-w1, gmi_gpm and saphir_methat
dmesh(4) is applied to 4 avhrr and 2 viirs.

It is necessary to set dmesh(3) and dmesh(4) in config.eobs.

For demsh(4), avhrr & viirs, 100 km should be set.
I don't know the value of dmesh(3) for amsr2_gcom-w1, gmi_gpm and saphir_methat.

**Comment by aerorahul** [comment]
@XuLi-NOAA @ADCollard Is this issue still relevant?  I believe it was fixed in the global workflow.
If so, please close.
Regardless, these jobs are now in the global-workflow.  If the issue persists, please open/move this issue to global-workflow

**Comment by XuLi-NOAA** [comment]
It was closed by Mike in February.
