### ISSUE TITLE
Convert Hera/Orion modulefiles to lua for DA GFSv16.2.0

### ISSUE THREAD

**Issue by MichaelLueken-NOAA** [NOAA-EMC/GSI#298]
Work is underway to convert Hera and Orion modulefiles to lua format (please see global-workflow issue [#639](https://github.com/NOAA-EMC/global-workflow/issues/639)) for the WCOSS2 port of GFSv16.1.5 (GFSv16.2.0).

Two new modulefiles will be created:

modulefiles/modulefile.ProdGSI.hera.lua
modulefiles/modulefile.ProdGSI.orion.lua

and ush/build_all_cmake.sh will be updated to use the new modulefiles.

**Comment by MichaelLueken-NOAA** [comment]
While attempting to compile on Hera, it was noted that the minimum required version of CMake was set to 3.16.2.  The version of CMake currently used on Hera for the GSI is 3.16.1.  So, the minimum required version of CMake was changed from 3.16.2 to 3.16.1.  The code successfully compiled following this update.

**Comment by MichaelLueken-NOAA** [comment]
Changed ush/sub_hera to accept new lua format modulefile.

**Comment by MichaelLueken-NOAA** [comment]
The Hera/Orion lua modulefile updates were merged to [feature/gfsda.v16.1.5_wcoss2_port](https://github.com/NOAA-EMC/GSI/tree/feature/gfsda.v16.1.5_wcoss2_port) at [225d400](https://github.com/NOAA-EMC/GSI/commit/225d400b976b15200839db839de4175549635ba2).  This issue can now be closed.

**Comment by MichaelLueken-NOAA** [comment]
Reopening ticket for feedback from Kate on issues she might encounter while using the new tag.

**Comment by MichaelLueken-NOAA** [comment]
@KateFriedman-NOAA I have merged the necessary changes to allow updated Hera and Orion lua modulefiles to compile and run to the feature/gfsda.v16.1.5_wcoss2_port branch at [225d400](https://github.com/NOAA-EMC/GSI/commit/225d400b976b15200839db839de4175549635ba2) and created the new tag [gfsda.v16.2.1](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.2.1).  Please let me know if you encounter any issues while building the DA components on the two machines, and I will make the updates and recut the tag.  Thanks!

**Comment by MichaelLueken** [comment]
These changes were merged to the authoritative develop branch at [ad2a3c0](https://github.com/NOAA-EMC/GSI/commit/ad2a3c081e295c89a9c66aa3385f8e4c4779ff1a) and [1d475c8](https://github.com/NOAA-EMC/GSI/commit/1d475c88ed381f19e596c83bfa7f949ced789329).  Closing issue.
