### ISSUE TITLE
Investigate units of vegetation area fraction

### ISSUE THREAD

**Issue by fmahebert** [NOAA-EMC/GSI#306]
The CRTM expects its input "Vegetation Fraction" as a unitless fraction in [0,1], per conversations in the comments of https://github.com/JCSDA-internal/ufo/issues/1894

While comparing CRTM radiance H(x) across GSI vs FV3-JEDI, I've found some concerns about the GSI units for this quantity:

- In a geoval file generated for me by @CoryMartin-NOAA using GSI (for amsua n19 obs), I see "vegetation area fraction" has min/mean/max = 0.0/7.8/98, consistent with the units being percentage in [0,100]
- For JEDI to match GSI radiance H(x) over land, I find I need to multiply the JEDI vegetation fraction by 100x (so that it also lies in the incorrect range [0,100]). This suggests that GSI may be passing the incorrectly-scaled vegetation fraction as input to the CRTM.

Am I misinterpreting the GSI geoval and H(x)? Or is there perhaps a units bug?

As I'm no expert in how GSI uses CRTM, I leave these observations here in the hopes an EMC expert can weigh in.

(edited for clarity)

**Comment by CoryMartin-NOAA** [comment]
I'm 90% sure the value of vegetation fraction written out by the modified GSI is directly what goes into CRTM. 
```
call nc_diag_metadata("Vegetation_Fraction",   sngl(surface(1)%vegetation_fraction) )
```
Tagging @ADCollard and @emilyhcliu for awareness/comment.

**Comment by emilyhcliu** [comment]
@fmahebert I am a bit confused.  I thought the CRTM expects the input vegetation fraction as % ranging from 0 to 100.   But the first statement in the description (above) indicated that CRTM expect vegetation fraction range from [0-1], and this is also inconsistent with the information documented in issue https://github.com/JCSDA-internal/ufo/issues/1894

I will run the GSI single cycle run to check the value of vegetation fraction.

**Comment by fmahebert** [comment]
@emilyhcliu, in the discussion in this UFO issue, it became clear that the CRTM User Guide was misleading and the CRTM actually expects a unitless fraction in [0,1].

**Comment by emilyhcliu** [comment]
I just ran a single-cycle run and confirmed that the vegetation field read from our surface file (sfcanl.nc) has the range from 0 to 100.  And I print out the vegetation fields that GSI passes to CRTM.  Those values also range from 0 to 100. 

The CRTM actually requires that the vegetation fraction to be between 0 and 1. (https://github.com/JCSDA-internal/ufo/issues/1894)

So, this is a bug in GSI!!
We should run single-cycle runs to check the impact (with vs. without the bug).

**Comment by fmahebert** [comment]
Additional info: in fv3-jedi, the vegetation area fraction is used straight from the background file, where the variable "vfrac" is in range [0,1]. The inconsistency may come from what is written to history vs restart files?
