### ISSUE TITLE
nonphysical increments produced by serial filter on Hera

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GSI#323]
Running the serial filter with EFSOI cycling (and also without at times) produces on some cycles non-physical increments, example following:

[Andrew.Eichmann@v71a1 atmos]$ grep increment gdas.t12z.enkfstat
[0] ens. mean anal. increment min/max  u   -107693.046875        29170.9941406    
[0] ens. mean anal. increment min/max  v   -45611.8164062        44759.7421875    
[0] ens. mean anal. increment min/max  tv   -9793.13574219        13133.6269531    
[0] ens. mean anal. increment min/max  q   -1219.31628418        6754.96484375    
[0] ens. mean anal. increment min/max  oz  -0.825550232548E-04   0.365831547242E-04
[0] ens. mean anal. increment min/max  ps   -1780.73510742        3868.44970703    
...

This is while running on WCOSS, and the result is the ensemble forecast crashing. In this run it is apparently so far the only time in 13 model days, to judge by grepping the remaining enkfstats produced with the serial filter. This particular problem (or this manifestation of it) has appeared before while running on Orion, after merging the GSI master of Jan 10 into the EFSOI fork, but then was resolved after merging from the Jan 25 hash of GSI master. Is there a standard approach to resolving this kind of problem?

The comrot and particular subdirectory is /gpfs/dell1/ptmp/Andrew.Eichmann/baily/efsoigdas.20211212/12/atmos (I've tarred the contents, minus the ensemble members, and left it on noscrub so it doesn't get purged; let me know if I should tar the members as well)
expdir: /gpfs/dell2/emc/modeling/save/Andrew.Eichmann/para/baily

Thank you!

**Comment by AndrewEichmann-NOAA** [comment]
@jswhit2 Have you seen this come up before?

**Comment by jswhit** [comment]
That's disturbing - no I haven't seen that before.

**Comment by jswhit** [comment]
Is it reproducible (in other words does it happen again if you just run the whole cycle over again, including the GSI observer step?)

**Comment by TingLei-NOAA** [comment]
@AndrewEichmann-NOAA  could you reproduce this case on hera?    Thanks to @JacobCarley-NOAA for letting us notice this issue.  We (including our collaborators) had similar cases on hera.   However, when I tried to use "theoretically " the same setup to repeat that run on hera, the problem was not reproduced.  So, I suspect there is a certain issue in the environmental setup.   If you could have a test on hera to reproduce the issue, I will like to have some digging on this.  Of course, if you couldn't reproduce it on hera, that already means some issues on the environmental side (though we may expect enkf could give some warning/error messages in those situations).

**Comment by TingLei-NOAA** [comment]
The similar behavior reported in a run on hera was reported by Liaofan.lin@noaa.gov at GSL.

**Comment by TingLei-NOAA** [comment]
Update at Mar, 7,2022,
Finished debugging/testing of the new function for the IO of GSI EnKF for  FV3-LAM  when l_fv3reg_filecombined=. false. , while the FV3-LAM restart files in their original forms with atmospheric fields in the core and tracer files separately and submitted a PR at EMC GSI  https://github.com/NOAA-EMC/GSI/pull/328.
Review and help in a couple of GSI PR or prospect PR for FGAT and dual resolution function for FV3-LAM  from HAFS developers.

**Comment by AndrewEichmann-NOAA** [comment]
@jswhit  @TingLei-NOAA 

Also, I should note that when it happened earlier, it didn't happen on every cycle, rather every other cycle.

**Comment by AndrewEichmann-NOAA** [comment]
The problem on Hera is similar. The blow up happens on the second full cycle and manifests like so - I'm not sure it's the same problem:

```
-bash-4.2$ grep inflation gdas.t12z.enkfstat 
 0:  using multiplicative inflation based on Pa/Pb
 0:  performing RTPS inflation...
 0:  inflation stats, time level:            1
 0:  NH mean ps posterior standard deviation (before inflation)=   7.6643115E+12
 0:  NH mean ps posterior standard deviation (after inflation) =   7.6643115E+12
 0:  NH mean ps inflation =    2.232555    
 0:  SH mean ps posterior standard deviation (before inflation)=   0.1834124    
 0:  SH mean ps posterior standard deviation (after inflation) =   0.4051266    
 0:  SH mean ps inflation =    2.394090    
 0:  TR mean ps posterior standard deviation (before inflation)=    4.374268    
 0:  TR mean ps posterior standard deviation (after inflation) =    4.381375    
 0:  TR mean ps inflation =    2.076503    
 0:  inflation stats, time level:            2
 0:  NH mean ps posterior standard deviation (before inflation)=   5.6584994E+12
 0:  NH mean ps posterior standard deviation (after inflation) =   5.6584994E+12
 0:  NH mean ps inflation =    2.296985    
 0:  SH mean ps posterior standard deviation (before inflation)=   0.1913134    
 0:  SH mean ps posterior standard deviation (after inflation) =   0.4364663    
 0:  SH mean ps inflation =    2.455696    
 0:  TR mean ps posterior standard deviation (before inflation)=    10.00796    
 0:  TR mean ps posterior standard deviation (after inflation) =    10.01149    
 0:  TR mean ps inflation =    2.109882    
 0:  inflation stats, time level:            3
 0:  NH mean ps posterior standard deviation (before inflation)=   1.6313861E+12
 0:  NH mean ps posterior standard deviation (after inflation) =   1.6313861E+12
 0:  NH mean ps inflation =    2.240654    
 0:  SH mean ps posterior standard deviation (before inflation)=   0.2090012    
 0:  SH mean ps posterior standard deviation (after inflation) =   0.4732363    
 0:  SH mean ps inflation =    2.400422    
 0:  TR mean ps posterior standard deviation (before inflation)=    10.00067    
 0:  TR mean ps posterior standard deviation (after inflation) =    10.00497    
 0:  TR mean ps inflation =    2.092380    
-bash-4.2$
```

I tried rewinding everything back to eobs and running again and got the same result.  The above is from the enkfstat in 
/scratch1/NCEPDEV/stmp4/Andrew.Eichmann/abacus/enkfgdas.20220201/12/atmos
expdir here:
/scratch1/NCEPDEV/da/Andrew.Eichmann/para_gfs/abacus

**Comment by TingLei-NOAA** [comment]
@AndrewEichmann-NOAA  do you have a run dir on hera , and, point  me to the original background ensemble , and hence I can try running a regular EnKF ?

**Comment by AndrewEichmann-NOAA** [comment]
@TingLei-NOAA 
Everything is on Hera - the comrot is
/scratch1/NCEPDEV/stmp4/Andrew.Eichmann/abacus

**Comment by TingLei-NOAA** [comment]
@AndrewEichmann-NOAA , Thanks.  It seems all rundir (DATA) had automatically been deleted in your jobs. 
 @LiaofanLin-NOAA is trying to create a clean test case (for fv3-lam) to reproduce the behavior. By "clean", I mean the job could be directly run from the rundir using a existing sbatch script   to reproduce the issue.  We will keep updating here about our investigating of this issue.

**Comment by AndrewEichmann-NOAA** [comment]
@TingLei-NOAA Sorry, I misunderstood. I'll rerun with  KEEPDATA="YES".

**Comment by TingLei-NOAA** [comment]
@AndrewEichmann-NOAA , Thanks.

**Comment by LiaofanLin-NOAA** [comment]
Yes, I saw the same EnKF issue with the regional workflow.  The issue could happen at a random cycle, meaning that its previous cycles are fine with EnKF.  At /scratch1/BMC/zrtrr/llin/220101_rrfs_dev1/STMP/tmpnwprd/RRFS_CONUS_13km_case13/2021091309, I have three scenarios:

1) enkfupdt_20220203: with abnormal analyses.  This was originally produced via the workflow at /scratch1/BMC/zrtrr/llin/220101_rrfs_dev1/expt_dirs/case13.  

2) enkfupdt_20220203_test01: with normal analyses.  This case uses the background data, namelist, anavinfo, and so on from 1).  The EnKF was launched via testorg.sh, a self-contained case.  This case uses the same enkf_fv3reg.x and module file as 1).  

3) enkfupdt_wflow_20220309: with abnormal analyses.  This case was produced by rocotorewind and rocotorun the enkf task via the workflow at /scratch1/BMC/zrtrr/llin/220101_rrfs_dev1/expt_dirs/case13, same as 1).  

More investigation is needed to see if something else happens in the workflow, leading to the different results in 2) and 3).

**Comment by TingLei-NOAA** [comment]
@LiaofanLin-NOAA  Thanks for clarification of this.  My questions are: you meant run 2 and run 1 use the same modules and executable, but run 1 is as you mentioned from the earlier runs by rocoto with the workflow, so, seems they were using different modules and executables to me .  Would you please further clarify  on this ?  And, do you think you could have a self contained case as in 2 to reproduce the issue?

**Comment by LiaofanLin-NOAA** [comment]
@TingLei-NOAA 

To your 1st question: I used the same modules and executable in 1) and 2), as following

`source /scratch1/BMC/zrtrr/llin/220101_rrfs_dev1/ufs-srweather-app_20220119/env/build_hera_intel.env_DA
cp /scratch1/BMC/zrtrr/llin/220101_rrfs_dev1/ufs-srweather-app_20220119/bin/enkf_fv3reg.x enkf.x`

However, the same that I am not 100% sure is whether the workflow loads other modules in addition to build_hera_intel.env_DA.  

To your 2nd question: No.  My self-contained case could not reproduce the issue, based on the current script in testorg.sh.

**Comment by TingLei-NOAA** [comment]
@LiaofanLin-NOAA  Thanks. Yes, they were using different modules like about netcdf , though maybe, it is irrelevant.
A self-contained case reproducing the issue would be very helpful

**Comment by AndrewEichmann-NOAA** [comment]
@TingLei-NOAA The RUNDIRS should be available now:
/scratch1/NCEPDEV/stmp2/Andrew.Eichmann/RUNDIRS/abacus/2022020112/gdas

**Comment by TingLei-NOAA** [comment]
@AndrewEichmann-NOAA  could you point me to the log filel for the enkf update corresponding to the run dir (/scratch1/NCEPDEV/stmp2/Andrew.Eichmann/RUNDIRS/abacus/2022020112/gdas/eupd.175489/)?  I will see if I could repeat the issue using a "self contained "  setup from this rundir.

**Comment by AndrewEichmann-NOAA** [comment]
@TingLei-NOAA 
The log file should be here:
/scratch1/NCEPDEV/stmp4/Andrew.Eichmann/abacus/logs/2022020112/gdaseupd.log

**Comment by TingLei-NOAA** [comment]
@AndrewEichmann-NOAA , a question, in the global run, the background are updated in place or the analysis were output in the increment files?  I want to make sure I am using the original background ensemble.  Thanks.

**Comment by AndrewEichmann-NOAA** [comment]
@TingLei-NOAA I don't know. Aside from using the serial filter, everything is a standard global-workflow setup. I was under the impression that nothing was overwritten, if that addresses your concern.

**Comment by TingLei-NOAA** [comment]
@AndrewEichmann-NOAA Yes ,the files like /scratch1/NCEPDEV/stmp4/Andrew.Eichmann/abacus/enkfgdas.20220201/06/atmos/mem001/gdas.t06z.atmf003.nc is with a older time stamp, not updated in place.  I will let you if I can reproduce that issue using your case.

**Comment by TingLei-NOAA** [comment]
@AndrewEichmann-NOAA  A question, in your run, there was like "/bin/ln -sf /scratch1/NCEPDEV/stmp4/Andrew.Eichmann/abacus/enkfgdas.20220201/12/atmos/mem001/gdas.t12z.atmi003.nc incr_2022020112_fhr03_mem001
"    and, after the EnKF , seems those increment files were updated in place.   Is that right?  If so, are initial fields in those original files were used in the EnKF and, hence, to repeat your run, I need to use the original version rather than the current ones?  Thanks.

**Comment by AndrewEichmann-NOAA** [comment]
@TingLei-NOAA My understanding was that that link is made before the increment is written out, so that when it is written out, it gets written to the rotdir even though the working directory (ie the run directory) is elsewhere. So I believe you can use what is in the rundir.  @MichaelLueken-NOAA , do I have that correct?

**Comment by MichaelLueken-NOAA** [comment]
@TingLei-NOAA @AndrewEichmann-NOAA While porting the GSI and EnKF to WCOSS2, this the nonphysical increments were an issue.  Working with GDIT, the answer was to set:

export MPICH_COLL_OPT_OFF=1

In EnKF scripts.  It would be interesting to see if this setting corrects the nonphysical increments on other machines as well.

When it comes to symbolic links,

**Comment by TingLei-NOAA** [comment]
Mike
Great you have a solution for that.  We will see if this could
help @LiaofanLin-NOAA's issue on Hera.

______________________________

Ting Lei

IMSG at NOAA/NWS/NCEP/EMC

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.***

301-683-3624

**Comment by LiaofanLin-NOAA** [comment]
@AndrewEichmann-NOAA Yes, you are correct.  My issue is only with the unphysical increment values.

**Comment by jswhit2** [comment]
@AndrewEichmann-NOAA there was a fix in https://github.com/NOAA-EMC/GSI/commit/44fa0ec87861f1beebaca76245b1161e2403e47a (unitialized values for covinflatenh,covinflatesh,covinflatetr namelist parameters) - are you including this update in your experiments?

**Comment by AndrewEichmann-NOAA** [comment]
@jswhit2  Ah, no. In my current experiment I'm using the standard global-workflow with a62dec63aef126afa2e49b91e9dcf8a944583023 from Dec 14. I'll make the appropriate adjustments.

**Comment by AndrewEichmann-NOAA** [comment]
@jswhit2 @TingLei-NOAA I ran an experiment with the serial filter on Hera over the weekend using the March 10 global-workflow (d758e8b227fca7b5a3320adc43c29ba492c3bfe9) and the March 9 GSI (47ee70b090c85c98733a0aa46b3d6fa93fc40727) and got the blowup that appears in the inflation (in the NH):

> -bash-4.2$ grep inflation enkfgdas.20220201/12/atmos/gdas.t12z.enkfstat
>  0:  using multiplicative inflation based on Pa/Pb
>  0:  performing RTPS inflation...
>  0:  inflation stats, time level:            1
>  0:  NH mean ps posterior standard deviation (before inflation)=   3.7326619E+12
>  0:  NH mean ps posterior standard deviation (after inflation) =   3.7326619E+12
>  0:  NH mean ps inflation =    2.232490    
>  0:  SH mean ps posterior standard deviation (before inflation)=   0.1825601    
>  0:  SH mean ps posterior standard deviation (after inflation) =   0.4048391    
>  0:  SH mean ps inflation =    2.420063    
>  0:  TR mean ps posterior standard deviation (before inflation)=    4.371480    
>  0:  TR mean ps posterior standard deviation (after inflation) =    4.378648    
>  0:  TR mean ps inflation =    2.132602    
>  0:  inflation stats, time level:            2
>  0:  NH mean ps posterior standard deviation (before inflation)=   2.8525873E+12
>  0:  NH mean ps posterior standard deviation (after inflation) =   2.8525873E+12
>  0:  NH mean ps inflation =    2.298732    
>  0:  SH mean ps posterior standard deviation (before inflation)=   0.1904309    
>  0:  SH mean ps posterior standard deviation (after inflation) =   0.4362382    
>  0:  SH mean ps inflation =    2.483025    
>  0:  TR mean ps posterior standard deviation (before inflation)=    10.35956    
>  0:  TR mean ps posterior standard deviation (after inflation) =    10.36299    
>  0:  TR mean ps inflation =    2.168968    
>  0:  inflation stats, time level:            3
>  0:  NH mean ps posterior standard deviation (before inflation)=   9.9059433E+11
>  0:  NH mean ps posterior standard deviation (after inflation) =   9.9059420E+11
>  0:  NH mean ps inflation =    2.243503    
>  0:  SH mean ps posterior standard deviation (before inflation)=   0.2082622    
>  0:  SH mean ps posterior standard deviation (after inflation) =   0.4734592    
>  0:  SH mean ps inflation =    2.426660    
>  0:  TR mean ps posterior standard deviation (before inflation)=    9.543962    
>  0:  TR mean ps posterior standard deviation (after inflation) =    9.548471    
>  0:  TR mean ps inflation =    2.149277    
> -bash-4.2$ 
> 

rotdir /scratch1/NCEPDEV/stmp4/Andrew.Eichmann/crumpet
expdir /scratch1/NCEPDEV/da/Andrew.Eichmann/para_gfs/crumpet

**Comment by AndrewEichmann-NOAA** [comment]
@jswhit2 On the way

**Comment by AndrewEichmann-NOAA** [comment]
@jswhit2

Rundir is in /scratch1/NCEPDEV/stmp2/Andrew.Eichmann/RUNDIRS/crumpet/2022020112/gdas/eupd.176003

**Comment by jswhit** [comment]
Thanks @AndrewEichmann-NOAA I am trying to reproduce now

**Comment by jswhit** [comment]
The unphysical increments go away if `modelspace_vloc=.false.` in enkf.nml.  So, this is a bug in the model-space localization implementation for the serial filter.    We've only really used model-space localization in the LETKF (since it is very slow for the serial filter).  I'll try to find some time later this week to see what's going on.

**Comment by AndrewEichmann-NOAA** [comment]
Good to know. I've been experiencing long runtimes with the serial filter - is there a large impact on the results from using model-space localization?

**Comment by AndrewEichmann-NOAA** [comment]
Unfortunately not for now. The reason is the lack of an observation-space analysis in our LETKF, which is needed for EFSOI. 

Do you still need my experiment on Hera? Otherwise I will delete it to release the storage.

**Comment by jswhit** [comment]
You could re-run the GSI observer on the 4D analysis states produced by the LETKF, no?  Even with the cost of the extra observer it would still be much faster than running the serial filter (with model-space localization). I'm running a couple more tests to see if I can fix the problem with unphysical values in the serial filter with model space localization, but you can delete the experiment by COB today.

**Comment by RussTreadon-NOAA** [comment]
@AndrewEichmann-NOAA , can this issue be closed?

**Comment by AndrewEichmann-NOAA** [comment]
sure
