### ISSUE TITLE
Port OznMon to wcoss2

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [NOAA-EMC/GSI#347]
Port the non-operational portions of the OznMon package to wcoss2, including package install, dev data extraction scripts, image generation scripts, and file transfer scripts.

Note that the operational portions of the package were ported to wcoss2 in #227 .

**Comment by aerorahul** [comment]
@EdwardSafford-NOAA Is this issue still relevant here? or can it be moved to GSI-Monitor?
If not, could you please close it?

**Comment by EdwardSafford-NOAA** [comment]
With the GSI-monitor reorder this issue is no longer relevant.  Closing issue.
