### ISSUE TITLE
GNSS RO algorithm changes for GFS v16.x

### ISSUE THREAD

**Issue by ADCollard** [NOAA-EMC/GSI#353]
The issue concerns the inclusion of changes to the GFS to include the following changes to the use of GNSS RO data:

- Turn on PAZ assimilation and add Sentinel-6 capability
- Improvements to QC procedures (improved super-refraction QC, remove Jacobian QC etc.)
- Bug fixes
- Code optimization

More details including impacts are shown [here](https://github.com/NOAA-EMC/GSI/files/8410449/LC-EMC_02-15-2022.pptx)

**Comment by ADCollard** [comment]
@MichaelLueken-NOAA I have added the fix file changes to the branch.

The fix branch is RO_Updates_Fix.  There are only two lines to change:

--- a/global_convinfo.txt
+++ b/global_convinfo.txt

- gps      044    0   -1     3.0      0      0      0  10.0  10.0   1.0  10.0  0.000000     0    0.     0.      0    0.     0.    0    0
+ gps      044    0    1     3.0      0      0      0  10.0  10.0   1.0  10.0  0.000000     0    0.     0.      0    0.     0.    0    0

+ gps      066    0    1     3.0      0      0      0  10.0  10.0   1.0  10.0  0.000000     0    0.     0.      0    0.     0.    0    0

**Comment by MichaelLueken** [comment]
@ADCollard The authoritative develop branch has been updated this morning to [114ed31](https://github.com/NOAA-EMC/GSI/commit/114ed3116919ae9a00acb7214f75df093d68b9bd).  This should now conclude the work associated with this issue.
