### ISSUE TITLE
Adding EFSOI to CMakeLists.txt

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GSI#358]
This change would make the necessary additions to CMakeLists.txt to compile the EFSOI executable in the master branch.

**Comment by MichaelLueken** [comment]
@AndrewEichmann-NOAA Rahul has been working on a CMake refactor which will be also be adding EFSOI to CMakeLists.txt.  This refactor will have priority, after the updates for GFS v16.x have been reviewed and merged to the authoritative repository.  Please see PR #327 for details.

**Comment by AndrewEichmann-NOAA** [comment]
EFSOI now being compiled in develop
