### ISSUE TITLE
Update RadMon html generation

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [NOAA-EMC/GSI#367]
Recently several minor changes have been made to the html code on emcrzdm.  These changes need to be added to the RadMon's html generation scripts.

**Comment by EdwardSafford-NOAA** [comment]
Work is complete and tested.  The only changes are to the RadMon's html customization and installation, which isn't operational code.

@MichaelLueken-NOAA would you like me to issue a new PR for this or can I amend #366 and add these changes to it?

**Comment by MichaelLueken** [comment]
@EdwardSafford-NOAA Since both modifications are to the RadMon package, I think it would be fine to amend #366 in order to get these changes in quicker.
