### ISSUE TITLE
problem with assigning COMIN_OBS and COMIN_GES_OBS in jobs scripts on Orion

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GSI#377]
I have eupd tasks failing on Orion, which seems to lead back to the following error in ediag:

> 0 + export GSUFFIX=.ensmean.nc
> 0 + GSUFFIX=.ensmean.nc
> 0 + export ASUFFIX=.nc
> 0 + ASUFFIX=.nc
> 0 + '[' emc = nco -o YES = YES ']'
> 00 + compath.py prod/obsproc/
> 
> *************************************************************
> ** FATAL ERROR: [compath] Unable to find /gpfs/?p2, are you on WCOSS?
> ** ABNORMAL EXIT at Tue May 10 15:33:33 CDT 2022 on Orion-02-33
> *************************************************************

This is from the following if-then block jobs/JGDAS_ENKF_DIAG, the lines of which were introduced with the WCOSS2 port :

```
if [ $RUN_ENVIR = "nco" -o ${ROTDIR_DUMP:-NO} = "YES" ]; then
    export COMIN_OBS=${COMIN_OBS:-$(compath.py ${envir}/obsproc/${obsproc_ver})/$RUN.$PDY/$cyc/$COMPONENT}
    export COMIN_GES_OBS=${COMIN_GES_OBS:-$(compath.py ${envir}/obsproc/${obsproc_ver})/$GDUMP.$gPDY/$gcyc/$COMPONENT}
else
    export COMIN_OBS="$DMPDIR/$CDUMP.$PDY/$cyc"
    export COMIN_GES_OBS="$DMPDIR/$GDUMP.$gPDY/$gcyc"
fi

```

The rotdir is here
/work/noaa/stmp/aeichman/comrot/eaglet
The expdir here
/work/noaa/da/aeichman/para/eaglet

**Comment by AndrewEichmann-NOAA** [comment]
analcalc, analdiag, anal, eobs, and vrfy all have the same problem. Trying reverting everything under jobs

**Comment by MichaelLueken** [comment]
@AndrewEichmann-NOAA Out of curiosity, what branch of global-workflow are using?  If you haven't tried using [dev_v16](https://github.com/NOAA-EMC/global-workflow/tree/dev_v16), please try again using this branch.  This is the branch that includes the global-workflow changes for WCOSS2 that should work on Hera and Orion.

**Comment by AndrewEichmann-NOAA** [comment]
@MichaelLueken-NOAA What I'm using is based on the develop branch, last merged mid-March, since last I heard cycling isn't working. I'll try what you suggest.

**Comment by AndrewEichmann-NOAA** [comment]
@MichaelLueken-NOAA Would you expect dev_v16 to work with the latest GSI develop?

**Comment by MichaelLueken** [comment]
@AndrewEichmann-NOAA I've never been on Orion, but I would expect that the dev_v16 branch to work using the latest GSI develop.  I believe that @KateFriedman-NOAA has made changes to the dev_v16 branch in the global-workflow project to allow changes for GFS v16.2.0 (WCOSS2 implementation) to work on the R&D machines (Hera and Orion).  I wouldn't expect the current global-workflow develop branch to work using the updated for WCOSS2 JJOBS and scripts that are currently in the GSI develop branch.

**Comment by KateFriedman-NOAA** [comment]
The global-workflow dev_v16 branch is not yet ready for use on Orion (or Hera). Work is still in progress and currently delayed by on-going WCOSS2 ops tasks. An announcement will be made when dev_v16 is ready for use on WCOSS2, Hera, and Orion.

**Comment by AndrewEichmann-NOAA** [comment]
@MichaelLueken-NOAA FWIW changing the jobs scripts seems to do the trick

**Comment by AndrewEichmann-NOAA** [comment]
Now I'm adding these lines to the end of config.base, though it is not the most general solution:


```
export COMPONENT=${COMPONENT:-atmos}
GDATE=$($NDATE -$assim_freq $CDATE)
gPDY=$(echo $GDATE | cut -c1-8)
gcyc=$(echo $GDATE | cut -c9-10)
GDUMP=${GDUMP:-"gdas"}

export COMIN_OBS=${COMIN_OBS:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
export COMIN_GES_OBS=${COMIN_GES_OBS:-$ROTDIR/$GDUMP.$gPDY/$gcyc/$COMPONENT}



```

**Comment by RussTreadon-NOAA** [comment]
@AndrewEichmann-NOAA , can this issue be closed?

**Comment by RussTreadon-NOAA** [comment]
@AndrewEichmann-NOAA , may this issue be closed?

**Comment by AndrewEichmann-NOAA** [comment]
@RussTreadon-NOAA yes, sorry for missing it
