### ISSUE TITLE
impacts of recent file location and name changes

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GSI#387]
I'm running with a gsi build merged with GSI develop hash 524527b38caed344429d3dfc358a01c5faf6b632  (May 18th) and an older global-workflow d758e8b227fca7b5a3320adc43c29ba492c3bfe9 (Mar. 10), due to the current problem with cycling. The relocation of the executables to GSI/install/bin/ breaks global-workflow/sorc/link_workflow.sh, which expects them to be in GSI/exec, with downstream task failures due to not finding the executables. Also global-workflow/sorc/build_gsi.sh expects to run build_all_cmake.sh instead of build.sh in GSI/ush. 

I presume this going to be changed global-workflow, but with the current state of cycling in global-workflow, it will require manual changes in currently running builds for cycling.

**Comment by AndrewEichmann-NOAA** [comment]
Making the appropriate change to global-workflow/sorc/link_workflow.sh, and then creating gsi.fd/exec and ls -s ../install/bin/* into it works so far

**Comment by AndrewEichmann-NOAA** [comment]
The link needs an absolute path, not a relative one, and there are some changes in name filenames between the root files and the links

**Comment by RussTreadon-NOAA** [comment]
@AndrewEichmann-NOAA , can this issue be closed?

**Comment by AndrewEichmann-NOAA** [comment]
good grief yes
