### ISSUE TITLE
Tree conflict between develop and release branch gfsda.v16.3.0

### ISSUE THREAD

**Issue by emilyhcliu** [NOAA-EMC/GSI#422]
I cloned GSI develop from GSI repository and then tried to checked the release/gfsda.v16.3.0 branch:

git clone --recursive https://github.com/NOAA-EMC/GSI.git
git checkout release/gfsda.v16.3.0

The following error message occurred while checking out the release branch:
```
[Emily.Liu@hfe12 gfsda.v16.3.0_test]$ git checkout release/gfsda.v16.3.0
error: The following untracked working tree files would be overwritten by checkout:
	src/ncdiag/CMakeLists.txt
	src/ncdiag/cmake/FindNetCDF.cmake
	src/ncdiag/cmake/PackageConfig.cmake.in
	src/ncdiag/cmake/ncdiag_compiler_flags.cmake
	src/ncdiag/cmake/ncdiag_compiler_flags_GNU_Fortran.cmake
	src/ncdiag/cmake/ncdiag_compiler_flags_Intel_Fortran.cmake
Please move or remove them before you switch branches.
Aborting
```

This prevented me from checkout the release/gfsda.v16.3.0. 
Is there a way to get around this?

**Comment by MichaelLueken** [comment]
Hi @emilyhcliu ,

Unfortunately, the go to answer:

`git checkout -f release/gfsda.v16.3.0`

will keep the submodule and add in the missing components from the `release/gfsda.v16.3.0` branch (not very pretty and might cause issues in the future).  To get around this issue, please use:

```
rm -rf src/ncdiag
git checkout release/gfsda.v16.3.0
```

This will allow you to properly checkout the proper version of `ncdiag` associated with `release/gfsda.v16.3.0` and let the GSI build.

**Comment by emilyhcliu** [comment]
@MichaelLueken-NOAA Thanks for the solution.

**Comment by MichaelLueken** [comment]
@emilyhcliu Another option would be to use:

`git clone --recursive git@github.com:NOAA-EMC/GSI.git -b release/gfsda.v16.3.0`

This will clone and checkout the release branch all in one go, so you don't need to worry about removing `src/ncdiag` to checkout `release/gfsda.v16.3.0`.
