### ISSUE TITLE
TDR and 88D code changes for HWRF 

### ISSUE THREAD

**Issue by lbi2018** [NOAA-EMC/GSI#46]
This issue refs the HWRF GSI code changes for TDR and 88D thinning from Jason and OU.

**Comment by TingLei-NOAA** [comment]
The developments in this PR look good.  One, maybe irrelevant, question is about the documentation on the block-following line 683 in setuprw.f90, which adjust the observation errors.  That will be very helpful for the understanding and possible further developments on this part if the author could explain the scheme or point to a reference.
