### ISSUE TITLE
read VAD wind bug fix

### ISSUE THREAD

**Issue by ShunLiu-NOAA** [NOAA-EMC/GSI#467]
Russ found gsi.x s aborts in read_prepbufr.f90 with the "-check all" compiler option. This issue has been traced to the code section of reading in VAD wind. The observation counter "iout" is not properly incremented. This causes the "-check all" gsi.x to fail. A potential fix to the issue is to move the VAD wind check prior to incrementing "iout".

**Comment by RussTreadon-NOAA** [comment]
@ShunLiu-NOAA , can this issue be closed?

**Comment by ShunLiu-NOAA** [comment]
I think we can close this issue. If it becomes an issue in future, we can work on a fix for this.
