### ISSUE TITLE
GSI license

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/GSI#476]
This project doesn't seem to have a license, can you add the correct one please?

**Comment by RussTreadon-NOAA** [comment]
The GSI Handling Review team is going through open GSI issues.  May this issue be closed?

**Comment by climbfuji** [comment]
@RussTreadon-NOAA Does GSI have a license nowadays?

**Comment by RussTreadon-NOAA** [comment]
No, I am not aware of the GSI having a license.  I am not aware of any plans for the GSI to obtain or add a license.

**Comment by climbfuji** [comment]
My recommendation would be to fix that. Here is the legal statement (from https://www.synopsys.com/blogs/software-security/unlicensed-open-source-scenarios.html#:~:text=This%20means%20that%20no%20one,permission%20to%20use%20the%20software.):
> A license is a grant of rights. To use a piece of software, whether it’s open source or commercial, you need some grant of rights. In the U.S. and many other places, creative work (including software) is protected by exclusive copyright by default. This means that no one can legally use, copy, distribute, or modify that software without explicit permission from the creator/author. This permission comes in the form of a license that grants the right to do so. Without that license, the baseline assumption is that you do not have permission to use the software.

**Comment by RussTreadon-NOAA** [comment]
Thank you @climbfuji .  Since we no longer have a GSI code manager, let me refer this to others in EMC for their consideration.   To help me explain this request to other staff, why does GSI need a license?  It's been around for years and is widely used by many.  What impact does adding a license have on current users? What impact will it have on future users? Is there a standard template license used by codes accessible from [NOAA-EMC](https://github.com/NOAA-EMC)?

**Comment by climbfuji** [comment]
I believe (but not 100% sure, not a legal expert) that the Federal Government / DOC / NOAA require any software that is developed to have an open source license that satisfies certain requirements. There's a lot of complicated legal language out there, check https://resources.data.gov/open-licenses. Most EMC software projects have a [GNU Lesser General Public License 3.0](https://www.gnu.org/licenses/lgpl-3.0.en.html) (LGPL) license, so I would go with that one unless that is not possible for GSI.

For spack-stack, for example, we had to go for a Creative Commons Zero license, since JCSDA cannot do LGPL3 (we can only do Creative Commons Zero and Apache2), but the Federal Government cannot do Apache2. It's complicated ...

**Comment by climbfuji** [comment]
But independent of all of that, having a software license is considered best practice because it gives users and developers clear guidelines on what they are supposed/allowed to do and what not.

**Comment by RussTreadon-NOAA** [comment]
Thank you @climbfuji for patiently explaining this to me.  I reached out to EMC staff to see how to move forward in a manner consistent with EMC practice.

**Comment by RussTreadon-NOAA** [comment]
@ShunLiu-NOAA , @CoryMartin-NOAA , and @hu5970 :  what's the path forward with this issue?

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA I think we need to ask EMC management to confirm what software license we can/should use

**Comment by RussTreadon-NOAA** [comment]
I'll reinitiate this conversation with EMC management.

**Comment by hu5970** [comment]
We used to have community version of GSI, which is under "GPL-3.0 license".

https://github.com/comgsi/GSI.git

**Comment by RussTreadon-NOAA** [comment]
This is good to know.  Thank you @hu5970 for sharing this information.  I'll relay this to EMC management.

**Comment by climbfuji** [comment]
I would be very careful with GPLv3. It's not compatible with software using Apache (such as JEDI etc). Apache projects cannot link to/use GPLv3 software. Look at fv3atm - this is LGPL (no version specified), which works for the federal government and can be used by Apache 2 projects.

https://github.com/NOAA-EMC/fv3atm/blob/develop/LICENSE.md

**Comment by RussTreadon-NOAA** [comment]
Thank you @climbfuji for your input.

**Comment by RussTreadon-NOAA** [comment]
NOAA-EMC [g-w](https://github.com/NOAA-EMC/global-workflow), [ufs_utils](https://github.com/ufs-community/UFS_UTILS), [wxflow](https://github.com/NOAA-EMC/wxflow), & [NCEPLIBS](https://github.com/NOAA-EMC/NCEPLIBS) use GNU Lesser General Public License v3.0.  Is this license compatible with Apache?

**Comment by climbfuji** [comment]
As far as NOAA or JEDI-folks are concerned, yes. License compatibility is a one-way street. Apache 2 projects like JEDI can link to "lgpl 2.1 or later" software, but not the other way round.

**Comment by RussTreadon-NOAA** [comment]
Work for this issue will be done in [RussTreadon-NOAA:feature/license](https://github.com/RussTreadon-NOAA/GSI/tree/feature/license)

**Comment by RussTreadon-NOAA** [comment]
Copy global-workflow [`LICENSE.md`](https://github.com/NOAA-EMC/global-workflow/blob/develop/LICENSE.md) to [feature/license](https://github.com/RussTreadon-NOAA/GSI/tree/feature/license).  Done at [`e609cbe`](https://github.com/RussTreadon-NOAA/GSI/commit/e609cbe6ad0921cf080736dbfd302db56c8d96de)

**Comment by RussTreadon-NOAA** [comment]
@climbfuji , I followed the lead of [global-workflow](https://github.com/NOAA-EMC/global-workflow) and copied their `LICENSE.md` into [feature/license](https://github.com/RussTreadon-NOAA/GSI/tree/feature/license).

GSI PR #745 has been opened to merge the license into `develop`.  I added you to PR #745 as a reviewer.
