### ISSUE TITLE
Potential divide-by-zero error in setupw.f90 for LNVD check

### ISSUE THREAD

**Issue by BrettHoover-NOAA** [NOAA-EMC/GSI#477]
The LNVD check in `setupw.f90` is used to quality control satellite winds of Type 244, 247, and 257–260. The check involves computing a ratio of the OmF residual to the log of the wind speed, and checking that ratio against a threshold value. If larger than the threshold value, the observation is rejected. e.g. `setupw.f90` [L 993–1002](https://github.com/NOAA-EMC/GSI/blob/develop/src/gsi/setupw.f90#L993-L1002):
```
        LNVD_wspd = spdob
        LNVD_omb = sqrt(dudiff*dudiff + dvdiff*dvdiff)
        LNVD_ratio = LNVD_omb / log(LNVD_wspd)
        LNVD_threshold = 3.0_r_kind
        if( .not. wrf_nmm_regional) then   ! LNVD check not use for CAWV winds in HWRF
           if(LNVD_ratio >= LNVD_threshold .or. &      ! LNVD check
              (presw > prsfc-110.0_r_kind .and. isli /= 0))then ! near surface check 110 ~1km
              error = zero
           endif
        endif
```

This check has the potential to generate a divide-by-zero error if `LNVD_wspd`, the observed wind speed, is exactly 1.0 m/s. To my knowledge this has not happened in practice, but the potential for a 1.0 m/s satwind to cause the GSI to crash needs to be addressed.

This check is formulated slightly differently in the JEDI Unified Forward Operator (UFO) in the `SatWindsLNVDCheck` ObsFunction. [L 68–73](https://github.com/NOAA-EMC/ufo/blob/develop/src/ufo/filters/obsfunctions/SatWindsLNVDCheck.cc#L68-L73):
```
      if ((u[jj]*u[jj] + v[jj]*v[jj]) > 1.01f) {
        out[0][jj] = sqrt((u[jj]-um[jj])*(u[jj]-um[jj]) + (v[jj]-vm[jj])*(v[jj]-vm[jj]))
                    / log(sqrt(u[jj]*u[jj] + v[jj]*v[jj]));
      } else {
        out[0][jj] = sqrt((u[jj]-um[jj])*(u[jj]-um[jj]) + (v[jj]-vm[jj])*(v[jj]-vm[jj]));
      }
```

In `SatWindsLNVDCheck`, the denominator of `LNVD_ratio` is automatically set to a value of 1.0 if the wind speed is less than 1.01 m/s, which avoids the divide-by-zero problem entirely. I would propose a similar fix to the GSI in `setupw.f90` to fix this problem, introducing an `if`-statement to assert a denominator value of 1.0 if the wind speed is less than 1.0 m/s, e.g.:
```
        if(LNVD_wspd > 1.0_r_kind) then
           LNVD_ratio = LNVD_omb / log(LNVD_wspd)
        else
           LNVD_ratio = LNVD_omb
        endif
```

I have a fork of the GSI develop branch with this fix in-place in the three locations where `LNVD_ratio` is defined for various satwind observation types, which is viewable [here](https://github.com/BrettHoover-NOAA/GSI). If this seems like a satisfactory fix, I can initiate a PR.

**Comment by RussTreadon-NOAA** [comment]
@BrettHoover-NOAA , the GSI Handling Review team is going through old issues to see which, if any, may be closed.  May we close this issue or is this still a problem?

**Comment by BrettHoover-NOAA** [comment]
Hi Russ - I don’t believe a PR was ever put through to fix this, but since
satwinds seem to have a minimum allowable wind speed the problem has never
been expressed. Since that is unlikely to change and this issue is resolved
in UFO already, I think it’s safe to close this issue without any code
changes.
