### ISSUE TITLE
Merge PM2.5 data assimilation for RRFS-SMOKE

### ISSUE THREAD

**Issue by hongli-wang** [NOAA-EMC/GSI#480]
Merge GSI PM2.5 data assimilation development for RRFS-SMOKE at GSL.

**Comment by RussTreadon-NOAA** [comment]
@hongli-wang , is this the issue associated with PR #482?

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA I believe it is, but before closing we should wait for confirmation from @hongli-wang

**Comment by hongli-wang** [comment]
@RussTreadon-NOAA Yes, it is associated with PR #482. Thanks.

**Comment by RussTreadon-NOAA** [comment]
@hongli-wang , thank you for the confirmation.   

Future development requires a more detailed issue.   The issue should be opened at the start of development and document all your commits.   Once development is ready to be considered for merger into `develop`, a PR can be opened.  The PR should reference the issue.   Merging and closing the PR will then automatically close the issue.

I will manually close this issue.

**Comment by hongli-wang** [comment]
> @hongli-wang , thank you for the confirmation.
> 
> Future development requires a more detailed issue. The issue should be opened at the start of development and document all your commits. Once development is ready to be considered for merger into `develop`, a PR can be opened. The PR should reference the issue. Merging and closing the PR will then automatically close the issue.
> 
> I will manually close this issue.

@RussTreadon-NOAA Sure. I will fellow your guidance on the issues documenting. Thanks.
