### ISSUE TITLE
Turn off VIIRS radiance data in gfsda.v16.3.0

### ISSUE THREAD

**Issue by emilyhcliu** [NOAA-EMC/GSI#486]
We need to turn off VIIRS radiance data and set it to monitoring mode in gfsda.v16.3.0
The only file change is in fix/global_sainto.txt.

The change in GSI fix is done in branch fix_gfsda.v16.3.0

```
 viirs-m_npp            12  -1    0.500    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_npp            13  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_npp            14  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_npp            15  -1    0.580    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_npp            16  -1    0.620    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_j1             12  -1    0.500    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_j1             13  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_j1             14  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_j1             15  -1    0.580    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_j1             16  -1    0.620    0.000    6.000   10.000    0.000      1     -1     -1
```

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA Could you merge the updated global_saitnfo.txt for gfsda.v16.3.0?

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu, once you have the updated satinfo file(s) in the repo and open a PR, I can approve it, merge, and create a new tag.

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA I have the [PR](https://github.com/NOAA-EMC/GSI/pull/487) ready.

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , please see PR #488 for questions regarding historical satinfo file(s).

**Comment by RussTreadon-NOAA** [comment]
Close this issue with merger of PR #488 into `release/gfsda.v16.3.0`    Tag [`gfsda.v16.3.0`](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.0) has been recreated.   Done at [3fb30e4](https://github.com/NOAA-EMC/GSI/commit/3fb30e4caeedb30591fbdc2224930c516c2ca74a).
