### ISSUE TITLE
access to 'fix' files

### ISSUE THREAD

**Issue by dkokron** [NOAA-EMC/GSI#495]
I am a new hire with GDIT working with Pete Johnsen.  My main focus will be performance optimization of NCEP applications.  I don't have access to the NCEP systems yet as I am still going through the security investigation.

I have built the HAFS application suite on my home system and run a few of the forecast test cases.  Now I've turned to getting GSI working.  I have GSI running to the point where it fails due to missing 'fix' files (specifically global_anavinfo.l127.txt).  I don't have permission to access the 'fix' module under the EMC-GSI repository (fix @ 023f81d).  What is the procedure for gaining access to these files?
Dan

**Comment by RussTreadon-NOAA** [comment]
@dkokron , we created a tarball for EMC-GSI fix @ 023f81d and uploaded it to an anonymous ftp server.  To download fix, 

1. anonymous ftp to `ftp.emc.ncep.noaa.gov`
2. `cd unaff/gsi`
3. `binary`
4. `get fix_023f81d.tar`
5. `quit`

**Comment by dkokron** [comment]
Got it.   Thanks

**Comment by RussTreadon-NOAA** [comment]
Great!  Closing issue.
