### ISSUE TITLE
The issue with RRFS (FV3-LAM) GSI EnKF runs on the north american domain.  

### ISSUE THREAD

**Issue by TingLei-daprediction** [NOAA-EMC/GSI#500]
The RRFS (FV3-LAM based ) hybrid GSI DA  is targeting to run on the 3km north american domain (model grids: 3950X2700X65) . Current tests show that make necessary  further ,sometimes significant, optimization of codes to handle the resulted large memory requirements.  This issue would document the issues/problems found so far for current EnKF runs. 
The current EnKF would abort with 5 control variables (even one control) variables with 30 or 2 ensembles.  Investigation with EnFK built with debug mode give the following information:
the program would fail for sendbuf in loadbal.f90 . 
The issue was found to potentially come from two: 1 . the size of senbuf is beyond the recognition of the (i_kind) integer (also for int64 integer) 2. such "large " index access to the sendbuf arrays. 
The attached is a discussion among us with more details 
^^

     In running Shun's NA EnKF case. with debug mode, it points to the line 403         in loadbal.f90
          ^^
              sendbuf(n) = grdin(indxproc(np,i),nn,nb,ne)
          VV
      Further tracing points to the definition of sendbuf 
            ^^
                allocate(sendbuf(numproc*nanals_per_iotask*npts_max*ncdim))
            VV
            The numproc, , nanals_per_iotask, npts_max, ncdim are , in this case,                160,1,66792,326,
            in which 160*66792 approximately equal to the total number of grid
            points in the horizontal dir for one member. 
            Hence, it could n't be changed by more cpu/nodes or smaller ensemble sizes.
           Their multiplication gets a big number beyond what the i_kind type
           format  integer could recognize. 
           However, It seems the allocation still works .
           But the problem would occur in the above line
           when the n became so large that can't be recognized too  and, "large:                  index access to array would also cause segmentation error.  
          I have a small test code for you to play with 
             ^^
                    program test
                        integer nn
                       real,allocatable :: ar (:)

                      nn=160*66792*326
                      allocate(ar(160*66792*326)). !ok
                      ar(160*66792*326)=1.0 ! segmentation error
                       write(6,*)'nn is' ,n.  !  a wrong number (negavie value) is given
                       end 
                 VV
VVVV
This issue would document the issues and solutions in progress , which has been worked on by a few EMC developers, collaborators and WCOSS2 help experts.  I would cc here some of them: @jswhit2  @ShunLiu-NOAA @hu5970  @JacobCarley-NOAA @dtkleist

**Comment by TingLei-NOAA** [comment]
An update:  thanks to @jswhit 's PR https://github.com/NOAA-EMC/GSI/pull/501#event-7934938266, using this version, on hera, a EnKF on NA using 2 ensemble members had been successfully run (4 nodes for 4 MPI tasks).   This version is being used on wcoss2 now to realize  EnKF runs on NA meeting the operational requirement or to reveal further optimization needed for the former.

**Comment by TingLei-daprediction** [comment]
An update:  Using the current EMC GSI EnFK including the @jswhit 's  PR #501 , I just finished an EnKF of 30 members on the 3km north American domain in 10 min using 80 tasks on 10 nodes following GDIT expert P. Johnson's job setup on grouping of threads and so on.  This performance of EnKF is totally acceptable/satisfactory.   This issue could be closed.  Thanks to @RussTreadon-NOAA taking care of this issue and  PR #501 .
