### ISSUE TITLE
lwrite_peakwt=false in GSI prevents randiances from being assimilated with ENKF

### ISSUE THREAD

**Issue by paocorrales** [NOAA-EMC/GSI#51]
I'm using GSI (v3.7) as an observer operator in combination with ENKF (v1.3) to assimilate radiances from several sensors/satellites. 

Doing some initial test I discovered that the ENKF (letkf version) wasn't incorporating any observation and traced back the error to the observation level pressure which was different from the level pressure defined at the GSI step. 

I solved it turn it on the `lwrite_peakwt` argument to **true** in the GSI namelist to save the correct observation level pressure in the diag files so the letkf can use that information later. 

I didn't find any mention of this requirement in the documentation or the code but would be great to add it in a future version. Is there a way to contribute to that? 
Thanks!

**Comment by jswhit** [comment]
The documentation is maintained by NCAR/DTC
https://dtcenter.org/community-code/ensemble-kalman-filter-system-enkf
I suggest sending a proposed doc change to
https://dtcenter.org/community-code/ensemble-kalman-filter-system-enkf/contact-enkf-help
