### ISSUE TITLE
GFS v16.3.5 implementation

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GSI#511]
This issue is opened after the fact to document changes in PR #510.   This PR updated `global_convinfo.txt` and `global_satinfo.txt` in [`release/gfsda.v16`](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16) for the GFS v16.3.5 implementation in early January 2023.

Specifically, the following changes are made to the indicated GSI fix files:
- `global_satinfo.txt`
   - Turn on VIIRS radiances from NPP and J1 for channels 12, 15, and 16
- `global_convinfo.txt`
   - Turn off GOES-17 (271) AMV winds for types: 245 (IRLW), 246 (WVCT), and 247(WVCA) due to deteriorating conditions
   - Turn on GOES-18 (272) AMV winds for types: 245 (IRLW), 246 (WVCT), and 247(WVCA)

**Comment by RussTreadon-NOAA** [comment]
**Creation of tag gfsda.v16.3.5**

The following steps were taken to create tag [`gfsda.v16.3.5`](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.5):
1. [`release/gfsda.v16`](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16) originated as a copy of [`release/gfsda.v16.3.0`](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16.3.0) at [7d9a408](https://github.com/NOAA-EMC/GSI/commit/7d9a408a3e1cb91ccead4c96a0b8a5e128522042). 

2. PR #510 was merged into `release/gfsda.v16` at [b3aa8c5](https://github.com/NOAA-EMC/GSI/commit/b3aa8c5a869cffa8dce811c680e495d25f883cba).

3. Tag [`gfsda.v16.3.5`](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.5) was created as a snapshot of `release/gfsda.v16` at [b3aa8c5](https://github.com/NOAA-EMC/GSI/commit/b3aa8c5a869cffa8dce811c680e495d25f883cba).

**Comment by ADCollard** [comment]
@RussTreadon-NOAA Thank you!

**Comment by RussTreadon-NOAA** [comment]
@ADCollard, tag [`gfsda.v16.3.5`](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.5) is ready.

**Comment by RussTreadon-NOAA** [comment]
Recreated tag [gfsda.v16.3.5](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.5) as copy of [release/gfsda.v16](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16) at [8c36097](https://github.com/NOAA-EMC/GSI/commit/8c360974de29d5e3d1f87d46b8fecb14c4972170).

**Comment by RussTreadon-NOAA** [comment]
@ADCollard , we need to get GFS v16.3.5 DA changes (script & fix) into the appropriate NOAA-EMC repositories.    

Did the v16.3.5 changes to `exglobal_atmos_analysis.sh` make it into the version of `exglobal_atmos_analysis.sh` in g-w `develop`?    Tagging @KateFriedman-NOAA since she probably knows.

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA @ADCollard The v16.3 GSI script updates were initially brought into global-workflow `develop` by @lgannoaa in https://github.com/NOAA-EMC/global-workflow/pull/1158 but then reverted due to a mismatch with the crtm version https://github.com/NOAA-EMC/global-workflow/pull/1238. 

I have an issue open to update global-workflow to use `crtm/2.4.0` but it needs the GSI `develop` and UPP hash from ufs-weather-model to update to `crtm/2.4.0` to be fully complete: https://github.com/NOAA-EMC/global-workflow/issues/1233. I have been running tests with varying levels of the system changing to `crtm/2.4.0`, hope to post those results in that issue today.

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA , `crtm/2.4.0` entered operations with GFS v16.3.4.   GSI issue [#520](https://github.com/NOAA-EMC/GSI/issues/520) has been opened to bring GFS DA v16.3.4 changes into NOAA-EMC/GSI `develop`.   @emilyhcliu is working on [#520](https://github.com/NOAA-EMC/GSI/issues/520).  Closure of #520 will also close GSI issue [#518](https://github.com/NOAA-EMC/GSI/issues/518).

**Comment by RussTreadon-NOAA** [comment]
@ADCollard , since we updated the fix submodule which NOAA-EMC/GSI `develop` points at we need to open a GSI-fix [issue](https://github.com/NOAA-EMC/GSI-fix/issues) to get the updated GFS v16.3.5 ASCII GSI fix files into [NOAA-EMC/GSI-fix](https://github.com/NOAA-EMC/GSI-fix).   I outlined the procedure ([click here](https://github.com/NOAA-EMC/GSI/issues/520#issuecomment-1402084932)) in GSI issue #520.

**Comment by KateFriedman-NOAA** [comment]
> `crtm/2.4.0` entered operations with GFS v16.3.4. GSI issue [#520](https://github.com/NOAA-EMC/GSI/issues/520) has been opened to bring GFS DA v16.3.4 changes into NOAA-EMC/GSI `develop`. @emilyhcliu is working on [#520](https://github.com/NOAA-EMC/GSI/issues/520). Closure of #520 will also close GSI issue [#518](https://github.com/NOAA-EMC/GSI/issues/518).

@RussTreadon-NOAA Noted, will see how this GSI work completion aligns with the ufs-weather-model hash updating to use a version of UPP that uses `crtm/2.4.0` and whether we update the workflow in advance. Will put updates in issue #1233.

**Comment by RussTreadon-NOAA** [comment]
As @ADCollard pointed out, I am wrong.   

Operational GFS v16.3.5 ASCII fix files are already in NOAA-EMC/GSI-fix with the exception of `/lfs/h1/ops/prod/packages/gfs.v16.3.5/sorc/gsi.fd/fix/global_anavinfo.l127.txt`.   This file, however, did not change in GFS v16.3.5.   GFS v16.3.4 changed `global_anavinfo.l127.txt`.   

So there is nothing more to bring into NOAA-EMC/GSI fix from GFS v16.3.5.   Instead, GFS v16.3.4 needs to add `global_anavinfo.l127.txt` to NOAA-EMC/GSI-fix.

Sorry @ADCollard for the false alarm.   I'll close this issue.

**Comment by ADCollard** [comment]
Thanks @RussTreadon-NOAA .  Less work for me!
