### ISSUE TITLE
Update CRTM to 2.4.0 in modulefile and CI

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/GSI#518]
https://github.com/NOAA-EMC/GSI/blob/861cbfc38dd48194de1a5c8a4c7f2bd343681b14/modulefiles/gsi_common.lua#L17
https://github.com/NOAA-EMC/GSI/blob/861cbfc38dd48194de1a5c8a4c7f2bd343681b14/ci/spack.yaml#L21

The CRTM version was updated to 2.4.0.  
Should the version in the modulefile and CI be updated?  Are there other places this needs an update within the scope of the GSI-applications.

**Comment by RussTreadon-NOAA** [comment]
Thank you, @aerorahul , for opening this issue.   

GFS v16.3.4 moved the GSI to `crtm/2.4.0`.   This and likely other changes in the release branch for GFS v16.3.4 DA need to be merged into NOAA-EMC/GSI `develop`.    

@emilyhcliu , this issue echoes email inquires regarding the status of getting GFS v16.3.4 DA changes into develop.    GFS v16.3.4 DA changes need to be merged into `develop` for various repos:  NOAA-EMC/GSI, global-workflow, and GSI-Monitor as well as gerrit:GSI-fix.     

GSI issue #517 documents efforts to get GFS v16.3.4 and v16.3.5 fix files changes into GSI `develop`.   @EdwardSafford-NOAA Ed opened GSI-Monitor issue [#66](https://github.com/NOAA-EMC/GSI-Monitor/issues/66) to get global DA monitor changes into GSI-Monitor `develop`.  g-w issues have also been opened to get GFS v16.3.4 and v16.3.5 changes into g-w `develop`.

Would you please open a GSI issue to document the inclusion of GFS v16.3.4 DA changes into GSI `develop`?

**Comment by emilyhcliu** [comment]
> Thank you, @aerorahul , for opening this issue.
> 
> GFS v16.3.4 moved the GSI to `crtm/2.4.0`. This and likely other changes in the release branch for GFS v16.3.4 DA need to be merged into NOAA-EMC/GSI `develop`.
> 
> @emilyhcliu , this issue echoes email inquires regarding the status of getting GFS v16.3.4 DA changes into develop. GFS v16.3.4 DA changes need to be merged into `develop` for various repos: NOAA-EMC/GSI, global-workflow, and GSI-Monitor as well as gerrit:GSI-fix.
> 
> GSI issue #517 documents efforts to get GFS v16.3.4 and v16.3.5 fix files changes into GSI `develop`. @EdwardSafford-NOAA Ed opened GSI-Monitor issue [#66](https://github.com/NOAA-EMC/GSI-Monitor/issues/66) to get global DA monitor changes into GSI-Monitor `develop`. g-w issues have also been opened to get GFS v16.3.4 and v16.3.5 changes into g-w `develop`.
> 
> Would you please open a GSI issue to document the inclusion of GFS v16.3.4 DA changes into GSI `develop`?

@RussTreadon-NOAA Yes.  I opened a [GSI issue](https://github.com/NOAA-EMC/GSI/issues/520) for merging GFS v16.3.4 DA changes into GSI develop.

**Comment by RussTreadon-NOAA** [comment]
Thank you, @emilyhcliu

**Comment by KateFriedman-NOAA** [comment]
@emilyhcliu @RussTreadon-NOAA Are there any updates on this? Thanks!

**Comment by RussTreadon-NOAA** [comment]
> @emilyhcliu @RussTreadon-NOAA Are there any updates on this? Thanks!

None that I am aware of.

**Comment by emilyhcliu** [comment]
@KateFriedman-NOAA @RussTreadon-NOAA 
I am running the regression test on the merged branch again.  Once it completes without any problem, I will turn [PR #526](https://github.com/NOAA-EMC/GSI/pull/526) from a draft to a real one tonight.
