### ISSUE TITLE
Remove processing of GMI in release branch

### ISSUE THREAD

**Issue by ADCollard** [NOAA-EMC/GSI#522]
There is an array overflow in the reading of GMI data which is being monitored in observations.   This issue updates [release/gfsda.v16](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16) to remove the processing of GMI bufr data, thus avoiding a code change in operations.

**Comment by RussTreadon-NOAA** [comment]
Create tag [`gfsda.v16.3.6`](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.6) as a copy of `release/gfsda.v16` at [`e268acf`](https://github.com/NOAA-EMC/GSI/commit/e268acf909e7ea0daaa88b93299168bd654eed99)

**Comment by RussTreadon-NOAA** [comment]
Close this issue.  The associated PR, #523, has been merged into [`release/gfsda.v16`](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16).   Done at [`e268acf`](https://github.com/NOAA-EMC/GSI/commit/e268acf909e7ea0daaa88b93299168bd654eed99).
