### ISSUE TITLE
Fix SEGFAULT in read_gmi.f90

### ISSUE THREAD

**Issue by ADCollard** [NOAA-EMC/GSI#524]
[read_gmi.f90](https://github.com/NOAA-EMC/GSI/blob/develop/src/gsi/read_gmi.f90) is causing a seg fault, at least on hera, when GMI data are read in.  It appears to be because the number of FOVs in the BUFR dump exceeds the number specified in `maxobs`:

```
integer(i_kind) :: jc,bufsat,n    
integer(i_kind),dimension(5):: iobsdate
integer(i_kind):: method,iobs,num_obs
integer(i_kind),parameter   :: maxobs=4000000
!-- integer(i_kind),parameter   :: nscan=74       ! after binning ifov, 221/3 + 1
integer(i_kind),parameter   :: nscan=221
```

We should review this read routine to determine whether it is working as expected as the format for these data changed on 20220628.  

From [here](https://amt.copernicus.org/articles/10/745/2017/amt-10-745-2017.pdf) we have
```
Orbital period 5554 s
Scans per orbit 2963
Scan direction Counterclockwise
Scan period 1.874 s
Scan range 152.6◦
Pixels per scan 221
```
So the number of FOVs in six hours should be `Pixels per scan` *  `Scans per orbit` * `Seconds per 6 hours` /  `Orbital period`
= `221 * 2963 * 21600 / 5554` = `2546664`

So 4000000 should be enough.

Maybe we are counting the S1 and S2 FOVs separately?  We need to review.

There is documentation on the data format [here](https://gpmweb2https.pps.eosdis.nasa.gov/pub/stout/helpdesk/filespec.GPM.V7.pdf), but I am not sure how helpful this is.

Adding @emilyhcliu and @ilianagenkova for awareness.

**Comment by ilianagenkova** [comment]
Running a script on January 2023's gmi1cr dumps, the max number of obs shows as _**5,083,442**_. Tag me if you'd like me to get counts for Dec 2022,

**Comment by RussTreadon-NOAA** [comment]
@ADCollard , may we close this issue?

**Comment by ADCollard** [comment]
@RussTreadon-NOAA Yes this was fixed in the dump. Please close.
