### ISSUE TITLE
openmp based parallelization enhancement to   FV3-LAM interface of GSI EnKF 

### ISSUE THREAD

**Issue by TingLei-NOAA** [NOAA-EMC/GSI#530]
The test of EnKF on the 3 km north american domain reveals the obvious benefits using multiple threads (8,16 and 32).  Hence, openmp based enhancement of the current fv3-lam interface of EnKF will help a lot to further accelerate the EnKF runs , like, on the north american domains. 
The prospect enhancement includes two aspect:
1) many loops for passing between stacked EnKF array-grdin and the read-in/write-out 3d fv3-lam variables. Improvements from this is certain though not sure how much speeding up we can get. 
2) to explore the openmp based multiple thread IO of different part of the same netcdf file.  If it could be done still need more digging and tests.  If it could be done, it is expected significant speeding up could be achieved for EnKF on large domains like the north american domain. 
This issue will document the status of work on this efforts and provide a place to share questions/comments/suggestions among interested/involved developers.

**Comment by TingLei-NOAA** [comment]
An update:  the openmp based parallel IO for netcdf 4 is still not doable according to https://github.com/Unidata/netcdf-fortran/discussions/392, because the IO is not thread safe.  So, this optimization will be on the first item above. 
Update on Feb.17,2023.  Use of soft links may help resolving the thread-safe issue in reading which is suspected by the netcdf developer to work  (also in the above QA github issue). Hence, some further exploration on this is to be done.

**Comment by RussTreadon-NOAA** [comment]
@TingLei-NOAA , can this issue be closed?

**Comment by TingLei-NOAA** [comment]
Additional openmp enhancements in the fv3-lam interface haven't caused obvious speeding up.  Further investigation/optimization are needed but it is not current priority.  So this issue will be closed and, could be re-opened in the future when work on this is resumed.
