### ISSUE TITLE
openmp based parallelization enhancement to FV3-LAM interface of GSI 

### ISSUE THREAD

**Issue by TingLei-NOAA** [NOAA-EMC/GSI#535]
This issue is for the similar motivation with the issue https://github.com/NOAA-EMC/GSI/issues/530.   openmp based parallelization is expected to significantly improve the performance of FV3-LAM IO process ( including the conversion between model grids /analysis grids) when multiple threads are being used as in the current RRFS runs .

**Comment by RussTreadon-NOAA** [comment]
@TingLei-NOAA , can this issue be closed?

**Comment by TingLei-NOAA** [comment]
For the same reason as with https://github.com/NOAA-EMC/GSI/issues/530,  this issue is closed.
