### ISSUE TITLE
Errors in adjtest

### ISSUE THREAD

**Issue by jderber-NOAA** [NOAA-EMC/GSI#548]
While preparing update to GSI, errors in adjtest were noted.  They all resulted from not considering that the routines control2*.f90 and bias correction are global routines, not local to the processor.

Two main issues.

1. When the random numbers are used to fill the control vector, different values are put into the bias correction terms on different processors.  This is not consistent with the usage in the GSI where these values should be the same on all processors.  Because of this, the test is incorrect on all processors except one where the dotproduct calculates the contribution from the bias correction term.

2. The test does not account for the uv and balance routines being global (interacting with other processors).  All calculations are done locally on a single processor.

In my tests, with the uv and balance routines used only 8 digits are the same.  Removing the uv and balance routines from the test resulted in 14 digits of consistency.

Note that because of the local nature of the calculations, results from the high resolution and low resolution tests should be different (different domains).  If done globally results from low resolution and high resolution should be very similar.

This bug should not impact the actual results of the GSI, only the ADTEST results.

To completely resolve these 2 issues would require the addition of 2 global communications.  Because of the repeated calls to this routine, the addition of the global communications probably would result in significant computational increase.  For the pcgsoi minimization, this routine is not used.  I have not made the necessary changes because of the increased cost and will allow others to determine how this issue will be handled.

**Comment by RussTreadon-NOAA** [comment]
@jderber-NOAA , may we close this issue?
