### ISSUE TITLE
Reprodutivity issue on output netcdf restart files of FV3LAM on Orion

### ISSUE THREAD

**Issue by shoyokota** [NOAA-EMC/GSI#549]
I confirmed the file reproductivity issue on Orion:/work2. The FV3LAM netcdf restart files output by GSI (fv3_dynvars, fv3_tracer, and fv3_phyvars), which should match on re-running, sometimes does not match. Only the netcdf files are different, and there is no difference of the cost function and resulting analysis increment written in the log file (stdout). This issue creates slight (not so large) difference of FV3LAM forecasts. Somehow, this issue has occurred only on Orion:/work2 and not been found on Orion:/work.

This issue was found in my retro test of RRFS being developed. Empirically, it frequently occurs in inputting regional ensemble forecasts as the background errors. This issue has not been confirmed in the current regression tests, but if we set directory in /work2 as ptmp and input same first guess and ensemble forecast files as those used in my RRFS retro test, this issue occurred even in the RRFS regression test with the current GSI develop branch.

At this moment, the cause of this issue has not been clarified yet. I asked helpdesk of Orion to investigate it, but they have no idea of why this issue only happens on /work2 and they gave up investivation. They think this issue is caused not by the system but by the code, but it is not clear. This issue has not necessarily been confirmed by many developers because it occurs only sometimes on Orion:/work2 and does not occur except in the setting of RRFS.

**Comment by CatherineThomas-NOAA** [comment]
Thanks for documenting this issue, @shoyokota.  To see if a similar problem occurred within the GFS, I ran the global GSI on Orion using the global workflow scripts (v16-like).  I first compiled and ran the GSI/gdasanal step on work and then compiled and ran on work2.  I ran three times consecutively on each work and work2.  All six cases had identical gsistats and identical atminc netcdf files.

**Comment by shoyokota** [comment]
Thank you for testing it with the global GSI on Orion. Whether or not this issue occurs depends on the input files, so it may not occur except with the restart files of FV3LAM. I could reproduce the occurrance of this issue in the regression test of RRFS with the following setting on Orion. I'd be grateful if someone would confirm this issue.

<details>
<summary>difference from the original setting</summary>

```diff
diff --git a/regression/regression_namelists.sh b/regression/regression_namelists.sh
index 824c6f07..c2963cb4 100755
--- a/regression/regression_namelists.sh
+++ b/regression/regression_namelists.sh
@@ -1410,7 +1410,7 @@ export gsi_namelist="
    newpc4pred=.true.,adp_anglebc=.true.,angord=4,
    passive_bc=.true.,use_edges=.false.,emiss_bc=.true.,
    diag_precon=.true.,step_start=1.e-3,
-   l4densvar=.false.,nhr_obsbin=3,
+   l4densvar=.false.,ens_nstarthr=1,nhr_obsbin=3,
    use_gfs_nemsio=.false.,use_gfs_ncio=.true.,reset_bad_radbc=.true.,
    netcdf_diag=.false.,binary_diag=.true.,
    l_obsprvdiag=.false.,
@@ -1532,9 +1532,9 @@ OBS_INPUT::
    aniso_a_en=.false.,generate_ens=.false.,
    n_ens=${nummem},
    beta_s0=0.15,s_ens_h=110,s_ens_v=3,
-   regional_ensemble_option=1,
+   regional_ensemble_option=5,
    pseudo_hybens = .false.,
-   grid_ratio_ens = 3,
+   grid_ratio_ens = 1,
    l_ens_in_diff_time=.true.,
    ensemble_path='',
    i_en_perts_io=1,
diff --git a/regression/regression_namelists_db.sh b/regression/regression_namelists_db.sh
index 59962a58..e01a5389 100755
--- a/regression/regression_namelists_db.sh
+++ b/regression/regression_namelists_db.sh
@@ -490,7 +490,7 @@ export gsi_namelist="
    newpc4pred=.true.,adp_anglebc=.true.,angord=4,
    passive_bc=.true.,use_edges=.false.,emiss_bc=.true.,
    diag_precon=.true.,step_start=1.e-3,
-   l4densvar=.false.,nhr_obsbin=3,
+   l4densvar=.false.,ens_nstarthr=1,nhr_obsbin=3,
    use_gfs_nemsio=.false.,use_gfs_ncio=.true.,reset_bad_radbc=.true.,
    netcdf_diag=.false.,binary_diag=.true.,
    l_obsprvdiag=.false.,
@@ -612,9 +612,9 @@ OBS_INPUT::
    aniso_a_en=.false.,generate_ens=.false.,
    n_ens=${nummem},
    beta_s0=0.15,s_ens_h=110,s_ens_v=3,
-   regional_ensemble_option=1,
+   regional_ensemble_option=5,
    pseudo_hybens = .false.,
-   grid_ratio_ens = 3,
+   grid_ratio_ens = 1,
    l_ens_in_diff_time=.true.,
    ensemble_path='',
    i_en_perts_io=1,
diff --git a/regression/regression_param.sh b/regression/regression_param.sh
index a2808ddf..b35c0b68 100755
--- a/regression/regression_param.sh
+++ b/regression/regression_param.sh
@@ -150,8 +150,8 @@ case $regtest in
             topts[1]="0:15:00" ; popts[1]="20/1/"  ; ropts[1]="/1"
             topts[2]="0:15:00" ; popts[2]="20/2/"  ; ropts[2]="/1"
         elif [[ "$machine" = "Orion" ]]; then
-            topts[1]="0:15:00" ; popts[1]="20/1/"  ; ropts[1]="/1"
-            topts[2]="0:15:00" ; popts[2]="20/2/"  ; ropts[2]="/1"
+            topts[1]="0:30:00" ; popts[1]="24/8/"  ; ropts[1]="/1"
+            topts[2]="0:30:00" ; popts[2]="24/16/"  ; ropts[2]="/1"
         elif [[ "$machine" = "Jet" ]]; then
             topts[1]="0:15:00" ; popts[1]="4/4/"  ; ropts[1]="/1"
             topts[2]="0:15:00" ; popts[2]="6/6/"  ; ropts[2]="/1"
diff --git a/regression/regression_var.sh b/regression/regression_var.sh
index 250317f4..22f5113c 100755
--- a/regression/regression_var.sh
+++ b/regression/regression_var.sh
@@ -97,7 +97,7 @@ case $machine in
       if [[ "$cmaketest" = "false" ]]; then
          export basedir="/work/noaa/da/$LOGNAME/gsi"
       fi
-      export ptmp="${ptmp:-/work/noaa/stmp/$LOGNAME/$ptmpName}"
+      export ptmp="${ptmp:-/work2/noaa/stmp/$LOGNAME/$ptmpName}"

       export fixcrtm=${CRTM_FIX:-/apps/contrib/NCEPLIBS/orion/fix/crtm_v2.3.0}
       export casesdir="/work/noaa/da/rtreadon/CASES/regtest"
diff --git a/regression/rrfs_3denvar_glbens.sh b/regression/rrfs_3denvar_glbens.sh
index af5da511..20f14dfd 100755
--- a/regression/rrfs_3denvar_glbens.sh
+++ b/regression/rrfs_3denvar_glbens.sh
@@ -76,6 +76,7 @@ echo "$VERBOSE" "default bkpath is $bkpath"
 echo "$VERBOSE" "background type is is $BKTYPE"

 ifhyb=.false.
+regional_ensemble_option=5
 if  [[ ${regional_ensemble_option:-1} -eq 1 ]]; then #using GDAS
   #-----------------------------------------------------------------------
   # Make a list of the latest GFS EnKF ensemble
@@ -93,6 +94,21 @@ if  [[ ${regional_ensemble_option:-1} -eq 1 ]]; then #using GDAS
     echo "$VERBOSE" " Hybrid needs at least ${HYBENSMEM_NMIN} ${memname} ensembles, only ${nummem} available"
   fi

+elif  [[ ${regional_ensemble_option:-1} -eq 5 ]]; then
+  rrfs_3denvar_fv3lam_ens=/work/noaa/da/syokota/rrfs/test/rrfs_b_SDL_PR/rrfs.v0.3.2/RRFS_CONUS_3km_00_ens/ptmp/nwges/para/rrfs_b/2022092915/
+  ifhyb=.true.
+  nummem=30
+  imem=1
+  while [[ $imem -le ${nummem} ]];do
+    memcharv0=$( printf "%03d" $imem )
+    memchar=mem$( printf "%04d" $imem )
+    restart_prefix="20220929.160000."
+    bkpathmem=${rrfs_3denvar_fv3lam_ens}/${memchar}/fcst_fv3lam_spinup/RESTART
+    ln -snf ${bkpathmem}/${restart_prefix}fv_core.res.tile1.nc       fv3SAR01_ens_mem${memcharv0}-fv3_dynvars
+    ln -snf ${bkpathmem}/${restart_prefix}fv_tracer.res.tile1.nc     fv3SAR01_ens_mem${memcharv0}-fv3_tracer
+    ln -snf ${bkpathmem}/${restart_prefix}phy_data.nc                fv3SAR01_ens_mem${memcharv0}-fv3_phyvars
+    (( imem += 1 ))
+  done
 fi

 #-----------------------------------------------------------------------
@@ -105,8 +121,9 @@ fi
 #           radar_tten converting code.
 #-----------------------------------------------------------------------

-ln -snf ${bkpath}/fv3_akbk                     fv3_akbk
-ln -snf ${bkpath}/fv3_grid_spec                fv3_grid_spec
+bkpathgrid=/work/noaa/da/syokota/rrfs/test/rrfs_b_SDL_PR/rrfs.v0.3.2/RRFS_CONUS_3km/fix_gsi/RRFS_CONUS_3km
+ln -snf ${bkpathgrid}/fv3_akbk                     fv3_akbk
+ln -snf ${bkpathgrid}/fv3_grid_spec                fv3_grid_spec

 if [ ${BKTYPE} -eq 1 ]; then  # cold start uses background from INPUT
   ln -snf ${bkpath}/phis.nc               phis.nc
@@ -118,11 +135,12 @@ if [ ${BKTYPE} -eq 1 ]; then  # cold start uses background from INPUT

   fv3lam_bg_type=1
 else                          # cycle uses background from restart
-  timestring=${YYYYMMDD}.${HH}0000
-  cp ${bkpath}/${timestring}.fv_core.res.tile1.nc             fv3_dynvars
-  cp ${bkpath}/${timestring}.fv_tracer.res.tile1.nc           fv3_tracer
-  cp ${bkpath}/${timestring}.sfc_data.nc                      fv3_sfcdata
-  cp ${bkpath}/${timestring}.phy_data.nc                      fv3_phyvars
+  bkpathges=/work/noaa/da/syokota/rrfs/test/rrfs_b_SDL_PR/rrfs.v0.3.2/RRFS_CONUS_3km/ptmp/nwges/para/rrfs_b/2022092915/fcst_fv3lam_spinup/RESTART
+  timestring=20220929.160000
+  cp ${bkpathges}/${timestring}.fv_core.res.tile1.nc             fv3_dynvars
+  cp ${bkpathges}/${timestring}.fv_tracer.res.tile1.nc           fv3_tracer
+  cp ${bkpathges}/${timestring}.sfc_data.nc                      fv3_sfcdata
+  cp ${bkpathges}/${timestring}.phy_data.nc                      fv3_phyvars
   fv3lam_bg_type=0
 fi
```

</details>

**Comment by shoyokota** [comment]
The Orion administrator concluded this issue was caused by "Hot Pool" and "File Striping" used on Orion:/work2. After the Hot Pool is disabled on April 6, this issue has not confirmed. The follows are emails from the Orion administrator.

<details>
<summary>Email on March 23, 2023</summary>

An issue with the /work2 filesystem associated with the orion cluster has been uncovered that could cause reproducibility issues with some jobs output.

Confirmation against one project has been verified and a bug report submitted to the storage vendor.
This issue occurs when both the Hot Pool (solid state data caching layer) and the File Striping (improved I/O performance for large files) features are being used for the output directory.
It is unclear how long this issue has existed or when it was introduced.

Hot Pools have been disabled for all of /work2 so this issue should not present a problem at this time.

The /work file system does not experience this issue as it uses a different architecture.
</details>

<details>
<summary>Email on March 24, 2023</summary>

IMPORTANT: /work2 filesystem issues remain.

The vendor has amended their statement that disabling Hot Pools would eliminate the reproducibility issues of concern.
/work does not exhibit this issue and can be utilized.

If /work2 is utilized, it is recommend that any new data be written to a newly created directory and the following command issued for that directory.

lfs setstripe -S 2M -c 1 -E 1G -c 4 -E eof -c 16 <dir>

The vendor is expected to apply changes Monday to correct this issue.
</details>

<details>
<summary>Email on April 6, 2023</summary>

IMPORTANT: Orion /work2 is usable.

The hot pools are now disabled, and any reproducibility issues should now be resolved.

You no longer need to stripe your directories to avoid the Hot Pools, as was addressed in the previous announcement.

One minor issue does remain that some users may notice.  During the clean-up process, some root-owned files are left behind.  The vendor is aware of the non-removable files, and a remedy is being prepared. The fix is expected to be transparent to the users of the filesystem.
</details>

@RussTreadon-NOAA @ShunLiu-NOAA If it is no problem, could you close this issue?

**Comment by RussTreadon-NOAA** [comment]
@shoyokota , may we close this issue?
