### ISSUE TITLE
Inclusion of MTG IRS data

### ISSUE THREAD

**Issue by jderber-NOAA** [NOAA-EMC/GSI#553]
This issue is for the inclusion of Meteosat Third Generation (MTG) InfraRed Sounder (IRS) data in the GSI.  The inclusion differs from the inclusion of some of the other types of data in that 1. The data comes into NCEP in the form of Principle Components (PCs).  Then in the obsproc data processing, several things are done to the data (e.g., thinning, conversion to radiances, use of a Hamming-apodization) before it is output as BUFR data and then eventually fed into the GSI.  While the obsproc part of the data processing is not technically part of the GSI, it does have implications for the use of the data.  Also, note that there is currently no real data from this instrument because the data has not yet been launched.

We decided to use the NWP-SAF code for preprocessing the data (with some modifications).  This code should not be redistributed without permission of the NWP-SAF.  No redistribution of these BUFR files is planned (except for GSI research purposes).  Attached to this write-up is the initial documentation from the NWP-SAF.  Also attached are the release notes for version 1.1.

[NWPSAF-MO-UD-053-IRSPP_User_Manual.pdf](https://github.com/NOAA-EMC/GSI/files/11019945/NWPSAF-MO-UD-053-IRSPP_User_Manual.pdf)

[Release_note_IRSPP_v1.2.pdf](https://github.com/NOAA-EMC/GSI/files/11019957/Release_note_IRSPP_v1.2.pdf)

Important Items/Issues from preprocessing.

1. Currently preprocessing uses NETCDF, HDF5 and LAPACK.  The use of eccodes has been removed.  The conversion to use the libraries currently on the ncep machines of netcdf, hdf5 and LAPACK have been unsuccessful and will have to await someone else smarter than me.
2. Current version allows selection of warmest FOV to make it more likely to select clear FOVs out of 10x10 thinning array.
3. Output of the radiances has been modified to use the NCEP BUFR routines.  Note that the PCs were not output in the current version (could be done, but could not think of any use for them).  There are 2 local descriptors (the same as for the NWP-SAF) code (CSSQ and CDSQ) which are 2 quality tables.

Contents of BUFR file

! SAID   001007 satelliteIdentifier (CCT C-5)
! OGCE   001033 centre (CCT C-1)
! GSES   001034 subCentre (CCT C-12)
! SIID   002019 satelliteInstruments (CCT C-8)
! SCLF   002020 satelliteClassification (334 = MTG?)
!
! YEAR   004001  Year
! MNTH   004002  Month
! DAYS   004003  Day
! HOUR   004004  Hour
! MINU   004005  Minute
! SECO   004006  Second
! FOVN    005043 fieldOfViewNumber (1 to 25600 - 160x160)
! SLNM    005041 scanLineNumber
! FORN    005045 fieldOfRegardNumber (dwell)
! RDTF    002165 radianceTypeFlags (4=apodized, 5=unapodized)
! SELV    007001 heightOfStation (m, to nearest 100m, geostationary height range)
! CLATH   005001 High resolution latitude
! CLONH   006001 High resolution longitude
! SAZA    007024 satelliteZenithAngle
! BEARAZ  005021 bearingOrAzimuth
! SOZA    007025 solarZenithAngle
! SOLAZI  005022 solarAzimuth
! CHSF    025142 channelScaleFactor
! SMRA    014047 scaledMeanAvhrrRadiance (imager mode, 3x3 pixels)
! SSDR    014048 scaledStandardDeviationAvhrrRadiance
! CONFLG  025187 confidenceFlag (0=valid, 1=invalid, 15=missing)
! SQFA    040026 scoreQuantizationFactor
! RRIB    040016 residualRmsInBand
! CHNM    005042 channelNumber
! SRAD    014044 channelRadiance
! TOBD    008076 band  (2=LW 3=MW)

! CSSQ : Quality flags:
!  spatial_sample_quality, 13-bit (bit 1 defined here as most significant)
!   Bit  Meaning
!    1-4 reserved
!    5   solar_straylight_correction_warning
!    6   solar_straylight_warning
!    7   noisy_detector_sample_warning
!    8   undersaturated_detector_sample_warning
!    9   saturated_detector_sample_warning
!   10   dust
!   11   cloudy
!   12   limb_view
!   13   space_view
!
! CDSQ detector_sample_quality, 4-bit (bit 1 defined here as most significant)
!   Bit  Meaning
!    1   excluded_detector_sample
!    2   noisy_detector_sample
!    3   undersaturated_detector_sample
!    4   saturated_detector_sample

With the creation of the new BUFR files for the MTG IRS data, modifications were made to process this data within the GSI.

Two major issues.

1. The initial CRTM coefficients are not yet available from NESDIS, so testing of the use of this data ended at the point these coefficients were necessary.
2.  Since real data is not available, the quality control is not yet developed.

In the current version the satellite is referred to as MTG1 and the instrument as IRS.  Future satellites would be MTG2,...

There are currently produced 198 channels.  Please see documentation from NWPSAF for details.  Note that the Longwave (LW) and Mid-Wave (MW) are included together, not as separate groups as in the input PCs.

**Comment by RussTreadon-NOAA** [comment]
@jderber-NOAA , may we close this issue?

**Comment by RussTreadon-NOAA** [comment]
@jderber-NOAA and @ADCollard , may this issue be closed?

**Comment by jderber-NOAA** [comment]
Russ,

Last I heard they were going to wait until Jedi to work on this one.  So it can be closed unless Andrew wants it kept open.

Removed myself from assignees.

**Comment by RussTreadon-NOAA** [comment]
Thank you, @jderber-NOAA , for the feedback.  

@ADCollard , would you like this GSI issue to remain open or shall we open a new issue in GDASApp, JEDI-T20, or the appropriate JEDI repo?

**Comment by ADCollard** [comment]
@RussTreadon-NOAA Please close this issue.
