### ISSUE TITLE
Excessive "Load the cloud coefficients" print out in gsi.x built with crtm/2.4.0

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GSI#556]
@jderber-NOAA noticed that when we run `gsi.x` on Hera with crtm/2.4.0 we find
```
Load the cloud coefficients:
...Cloud model: CRTM
...CloudCoeff file: ./crtm_coeffs/CloudCoeff.bin
```
written to stdout hundreds to times.   This is also true on Orion.   This printout is **not** in the operational global crtm/2.4.0 gsi.x job log files.

A check of Orion `/apps/contrib/NCEP/hpc-stack/src/hpc-stack/pkg/crtm-v2.4.0/libsrc/CRTM_LifeCycle.f90` finds
```
    ! Load the cloud coefficients
    IF ( Local_Load_CloudCoeff ) THEN
      WRITE(*, '("Load the cloud coefficients: ") ')
      WRITE(*, '("...Cloud model: ", a) ') TRIM(Default_Cloud_Model)
      WRITE(*, '("...CloudCoeff file: ", a) ') TRIM(Default_CloudCoeff_File)
      err_stat = CRTM_CloudCoeff_Load( &
```
Hera `/scratch2/NCEPDEV/nwprod/hpc-stack/src/v1.2.0/pkg/crtm/libsrc/CRTM_LifeCycle.f90` contains
```
    ! Load the cloud coefficients
    IF ( Local_Load_CloudCoeff ) THEN
!!$      WRITE(*, '("Load the cloud coefficients: ") ')
!!$      WRITE(*, '("...Cloud model: ", a) ') TRIM(Default_Cloud_Model)
!!$      WRITE(*, '("...CloudCoeff file: ", a) ') TRIM(Default_CloudCoeff_File)
      err_stat = CRTM_CloudCoeff_Load( &
```
The above Hera copy of `CRTM_LifeCycle.f90` is dated Dec 18 2021.   The crtm/2.4.0 include files and library are dated Jun 14 2022.   It seems the Hera crtm/2.4.0, like Orion, was built with the load cloudcoeff writes active.   

We should turn off this printout in crtm/2.4.0 on Orion and Hera.    

Are the crtm/2.4.0 versions installed on Hera, Orion, and WCOSS2 identical?

**Comment by RussTreadon-NOAA** [comment]
Tagging @emilyhcliu , @ADCollard , and @HaixiaLiu-NOAA .

**Comment by emilyhcliu** [comment]
The repeated messages are indeed coming from CRTM 2.4.0 EMC installation.  
I did not find this in JEDI crtm2.4..0 build.
I think the crtm/2.4.0 on Orion and Hera are identical.
We asked them to pull the crtm/2.4.0 from the JCSDA official site to build.

**Comment by DavidHuber-NOAA** [comment]
I would like to mimic this build on S4.  Is there a particular repository or branch of the CRTM that has these print statements removed?

**Comment by emilyhcliu** [comment]
> I would like to mimic this build on S4. Is there a particular repository or branch of the CRTM that has these print statements removed?

The [CRTM-2.4.0_emc](https://github.com/JCSDA/crtm/tree/release/REL-2.4.0_emc) from JCSDA CRTM official GitHub repository.
