### ISSUE TITLE
A quick enhancement for clipping negative Q in the analysis of EnKF for fv3-lam

### ISSUE THREAD

**Issue by TingLei-NOAA** [NOAA-EMC/GSI#566]
In the current FV3-LAM EnKF,  negative values in the hydrometers wold be replaced with the minimum positive values available in the running of this program.   But this clipping is not applied to the moisture (sphum ). The negative values would cause issues for the following modeling/forecast if the model wouldn't use clipping on its' own, that is the case found by @JiliDong-NOAA    
Hence,  a quick adding of such clipping for sphum (q) in the fv3-lam EnKF is to be done.

**Comment by ShunLiu-NOAA** [comment]
David and Chunhua,

Could you please review Ting's changes? We want to implement the change in rrfs v0.5.
Thank you.
