### ISSUE TITLE
Update GSI_BINARY_SOURCE_DIR paths in modulefiles

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/GSI#579]
The GSI fix set was recently updated on disk and within global-workflow (see https://github.com/NOAA-EMC/global-workflow/issues/1550). It was later noticed that there is a path in the GSI modulefiles (`GSI_BINARY_SOURCE_DIR` variable) that needs a matching update (see https://github.com/NOAA-EMC/global-workflow/issues/1550#issuecomment-1550337199).

Example in Hera modulefile: https://github.com/NOAA-EMC/GSI/blob/develop/modulefiles/gsi_hera.intel.lua#L29

The `GSI_BINARY_SOURCE_DIR` paths in the Hera, Orion, Jet, and WCOSS2 modulefiles need to be updated to use the newer `20230112` fix set.

Also, consider accepting `gsi_ver` from global-workflow `fix.ver` file to define the version in the path when run within GFS/global-workflow. See https://github.com/NOAA-EMC/global-workflow/blob/develop/versions/fix.ver#L14.

- [ ] Update the GSI hash in global-workflow `develop` after update is made (open global-workflow issue to make update).

**Comment by RussTreadon-NOAA** [comment]
This issue is related to #580.   Most of the work requested in this issue is covered by #580.

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA , how do you suggest implementing the idea 

_accepting gsi_ver from global-workflow fix.ver file to define the version in the path when run within GFS/global-workflow. See https://github.com/NOAA-EMC/global-workflow/blob/develop/versions/fix.ver#L14._

in NOAA-EMC/GSI `develop`?

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA , how do you suggest implementing the idea _accepting gsi_ver from global-workflow fix.ver file to define the version in the path when run within GFS/global-workflow. See https://github.com/NOAA-EMC/global-workflow/blob/develop/versions/fix.ver#L14._ in NOAA-EMC/GSI `develop`?

My initial thought would be similar to how the module versions get set. Something like this:
```
local gsi_ver=os.getenv("gsi_ver") or "20230112"
pushenv("GSI_BINARY_SOURCE_DIR", pathJoin("/scratch1/NCEPDEV/global/glopara/fix/gsi/" .. os.getenv("gsi_ver")))
```
^ this would need to be tested, I parsed it together in this comment based on how we're doing similar things in global-workflow with incoming changes to add the initial capability to use version variables like we do in ops, example: https://github.com/KateFriedman-NOAA/global-workflow/blob/feature/version-files/modulefiles/module_base.hera.lua#L35.

The `gsi_ver` variable in the GSI modulefiles could be `gsi_fix_ver` here but it's `gsi_ver` at the workflow level from `fix.ver` currently so one would need to grab that from the environment (`os.getenv`) as `gsi_ver` first.

**Comment by RussTreadon-NOAA** [comment]
Thank you @KateFriedman-NOAA for outlining what you have in mind.   We may need to defer this until you or someone else has time to work on this.  We do not have a GSI code manager to make and, more importantly, test the change.
