### ISSUE TITLE
Regression Tests Crash When Compiled with GNU

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/GSI#582]
Running the regression tests with hera.gnu compilers crashes for the following tests in the `ncdiag` module ncdw_metadata.f90, line 34 or 26 with an `invalid memory reference` seg fault or with an error that a netCDF file is locked and cannot be written to: `global_3dvar`, `global_4dvar`, and `global_4denvar`.

Also, the `hwrf_nmm_d2` test fails with an invalid pointer error.  The exact line for this error isn't clear from the backtrace, but may be located near setupbend:242, setupbend:743, setupbend:255.  IntelMKL is also a possibility.

These were discovered during the testing of #571.  It's possible that the `hwrf_nmm_d2` test will be fixed by that PR, but not the global tests.

Also, the GNU build should be performed with OpenBLAS rather than Intel MKL.

**Comment by RussTreadon-NOAA** [comment]
@DavidHuber-NOAA , the GSI Handling Review team is going through GSI issues to see which, if any, may be closed.  Do you know if this issue can be closed?

**Comment by DavidHuber-NOAA** [comment]
The tests still crash with GNU when compiled against spack-stack, so this is still an issue.  Addressing this will likely fix some bugs in the code, so it may be worth keeping open.

**Comment by RussTreadon-NOAA** [comment]
Thank you @DavidHuber-NOAA for your reply.  We can keep this issue open for the time being.

**Comment by RussTreadon-NOAA** [comment]
@DavidHuber-NOAA , what is the status of this issue?

**Comment by DavidHuber-NOAA** [comment]
I don't think I will have time to work on this -- I expect it to be a lengthy endeavor similar to the Intel 2020+ upgrade.  However, I will try to address the GNU compiler warnings when upgrading to the Intel LLVM compilers.  I will try running the GNU tests at that time and seeing if it resolves the issue.

**Comment by RussTreadon-NOAA** [comment]
Thank you @DavidHuber-NOAA for the update.  I'll close this issue with a note added to GSI issue #665.
