### ISSUE TITLE
Adding the MPI parallelization based functions for EnKF IO for fv3-lam 

### ISSUE THREAD

**Issue by TingLei-daprediction** [NOAA-EMC/GSI#583]
The openmp based enhancement for EnKF IO interface for fv3-lam hasn't shown significant speeding up . 
Hence, the MPI parallelization based development for FV3-LAM EnKF IO  is to be implemented and tested. It is built on top of parallel netcdf capability and is similar to what is implemented in GSI IO for fv3-lam.  However, for being now, the parallelization would only be done over vertical levels not over variables.  By doing so, we will  have less refactoring and, at the same time, in combination with the existing IO parallelization over the members,  we still can have an rather efficient usage of the MPI processes. For example, if the number of vertical levels is 60 and the number of the ensemble member 30,  totally 60X30=1800 MPI processes would be used for IO. 
The stats from tests/evaluation of this scheme will be updated here.

**Comment by RussTreadon-NOAA** [comment]
@TingLei-NOAA , can we close this issue?

**Comment by TingLei-NOAA** [comment]
An prelimilary version  of MPI-based EnKF IO for fv3-lam has been created. But, no significant speeding up is achieved as expected.  Further investigation/optimization are needed and it is not current priority.  Hence, this issue will be closed and is able to be re-opened if needed.

**Comment by TingLei-NOAA** [comment]
@Russ Treadon - NOAA Federal ***@***.***>  Thanks for sorting
out those issues.  I had taken actions in response to your inquiries.
 Please let me know if you have further questions.

______________________________

Ting Lei

Physical Scientist, Contractor with Lynker in support of

EMC/NCEP/NWS/NOAA

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.***

301-683-3624

**Comment by RussTreadon-NOAA** [comment]
@TingLei-NOAA , no questions.  We are trying to clean out old GSI issues as we pivot away from GSI and move toward JEDI.  Thank you for checking your issues and closing several.
