### ISSUE TITLE
Does not detect Cheyenne with full hostname

### ISSUE THREAD

**Issue by BruceKropp-Raytheon** [NOAA-EMC/GSI#595]
The script ush/detect_machine.sh does not find a match for Cheyenne. It tries to match a entry using 'hostname -f', but on Cheyenne this returns something of the form chadmin3.ucar.edu . There is no pattern that matches this, so this script exits with MACHINE_ID="" .

**Comment by BruceKropp-Raytheon** [comment]
Steps to reproduce (for branch 'develop'  and for PR#571):
+ source /glade/scratch/epicufsrt/jenkins/workspace/sandbox/emc-gsi-build/gsi/ush/detect_machine.sh
++ case $(hostname -f) in
+++ hostname -f
++ MACHINE_ID=
++ '[' = hera ']'
/glade/scratch/epicufsrt/jenkins/workspace/sandbox/emc-gsi-build/gsi/ush/detect_machine.sh: line 43: [: =: unary operator expected
++ '[' = cheyenne ']'
/glade/scratch/epicufsrt/jenkins/workspace/sandbox/emc-gsi-build/gsi/ush/detect_machine.sh: line 43: [: =: unary operator expected
+ echo MACHINE_ID=
MACHINE_ID=

**Comment by DavidHuber-NOAA** [comment]
I see now that the hostname is incorrect for chadmin nodes inside detect_machine.sh.  A new line should be added after line 30 of detect_machine.sh:

`30   chadmin[1-6].ib0.cheyenne.ucar.edu)  MACHINE_ID=cheyenne ;; ### cheyenne1-6`
`31   chadmin[1-6].cheyenne.ucar.edu)  MACHINE_ID=cheyenne ;; ### cheyenne1-6`

I don't have access to the chadmin nodes on Cheyenne.  Could you test this solution?

**Comment by BruceKropp-Raytheon** [comment]
platform=cheyenne
hostname=chadmin3.ucar.edu
COMPILER=intel
+ hostname
chadmin3
+ hostname -f
chadmin3.ucar.edu

**Comment by RussTreadon-NOAA** [comment]
The GSI Handling Review team is going through open issues to see which, if any, may be closed.  Can this issue be closed?

**Comment by DavidHuber-NOAA** [comment]
Yes, this was fixed and merged with #571.
