### ISSUE TITLE
Optimization of multiscale regional runs

### ISSUE THREAD

**Issue by jderber-NOAA** [NOAA-EMC/GSI#607]
Code is in converge4 (branch optimize6) in my github repository

Shun Liu reported unexpected slow run times using the multiscale ensemble RRFS North American domain testing.  Runtimes when using dbz observations and conventional observations are reported to be about  943s.

The I/O for the ensembles was the first candidate for optimization.  After looking at it, it appears that this is done about as well as it can be done.  However, it is not clear why there are 2 different methods.  Looks like the slower and more complicated of the two should/could be removed.  Perhaps something for the future.

From there we went on to look at the observation I/O and initial processing.  The first thing that was noted was that there were many arrays allocated without a corresponding deallocate.  Adding these allocates significantly reduced the memory and page faults.

The read_satwnd routine appeared to be one of the slowest.  This is the one that was worked on first with significant changes.  It was noted that the subset (e.g., 'NC005099' ) was tested for every observation multiple times.  This really only needs to be tested once for each message (multiple observations).  The test was changed to be done on messages and the information was communicated to every observation through the tab array (istype).

Also in the satwnd, it was noted that there were 2  pmot options. "0." which passed on all observations which were not removed by the thinning and option "1." that includes all observations including thinned observations.   With the changes described in the following few paragraphs this capability was expanded to 4 options, included in other routines that do thinning and the process optimized.  

As part of the above changes, the convthin routines were modified to use less memory, two of the 4 thinning routines were removed and the algorithm simplified.  The simplified algorithm included removing the setting of the iloc array and set a bit flag in the rthin array if the data was flagged for thinning.  The data were not removed by the thinning if the option save_all was set to true (pmot=1 or 3).  This allows the data to be saved later in the diagnostic file (see new pmot options below). If save_all was false (pmot=0 or 2), some of the thinned data is removed within the convthin routines and the rest removed in the reading routine.  The removal of some of the thinned data in the convthin routines was done to increase the number of data that can be used and reduce computations.  Within the read_ routines that were modified, both the remaining rthin data and rusage data (data that does not pass QC but currently passed to the diagnostic files) may be removed based on the pmot options. 

In the read_ routines which used thinning, the code was modified to to include the pmot option currently in the read_satwnd routine.  Also, there were two new options added for pmot (see below).  

pmot = 0. Pass on all observations that fail the setup quality control, but not those that are thinned.
pmot = 1. Pass on all observations that fail the setup quality control and the obs that are thinned.
pmot = 2. Pass on only the observations that do not fail the quality control and are not thinned.
pmot = 3. Pass on only the observations that do not fail the quality control plus the obs that are thinned.

For pmot=1. and pmot=0. the same processing is used as is done now in read_satwnd.  The input pmot values from the convinfo file could/should be changed to integers, but I did not do this so that working scripts would not fail.

Note that in the above definitions, the "quality control" refers to only the quality control contained in the read routines that currently retains observations for the setup routines.  The idea of expanding to the 4 values of the pmot variable is primarily to include the pmot = 2. option.  In this case, the minimum number of observations will be passed from the read_ routines that would produce the same results.  This would decrease the size of the diagnostic files and decrease the number of observations passed to the setup routines every time they are called and hopefully speed up the code.  The pmot = 2. routine is consistent with what is done for the AVN analysis and the reduce_diag option.  Also, if the reduce_diag option is set and pmot is less than 2 (0. or 1.) then 2 is added to the pmot values  and the value is 2. or 3.

Note that the above options were added only to the routines that thin the data.  A simplified version could be added to other read_ routines to eliminate obs that do not pass the read_* qc. to reduce the amount of data passed on to the other setup* routines.

A list of the routines which the pmot options were added. Except where noted, pmot is defined in convinfo
1. read_dbz_nc.f90 (pmot_dbz hardwired to 2 in obsmod)
2. read_fl_hdob.f90
3. read_goesimgr_skycover.f90
4. read_l2bufr_mod.f90 
5. read_prepbufr.f90
6. read_radar.f90 (pmot_vr hardwired to 0 in obsmod)
7. read_radar_wind_ascii.f90 (pmot_vr hardwired to 0 in obsmod)
8. read_rapidscat.f90
9. read_satmar.f90
10. read_satwnd.f90
11. read_sfcwnd.f90
12. read_wcpbufr.f90

After making these changes, it was noted that the regression tests did not pass exactly (same starting penalty and gradient with small differences in the stepsize and following iterations).  After significant investigation it was found that in some of the current versions of the above routines, the earlier reordering routines were not properly implemented and the data did not retain the same order as they were read.  I was able to modify both the current GSI and the updated GSI to produce exactly the same ordering and was able to get identical results in the regression tests. 

However, the updated GSI used to produce the same ordering uses more memory and requires more processing.  So instead of retaining the ordering in the input data file, the new code orders the data as read in except when there are entries in the convinfo file for data of that type.  When there are entries in the convinfo file, the output data is ordered so that first the data that does not have an entry in the convinfo is output, then the data is output in the order of the convinfo entries.  Within each convinfo type, the order that they are read in is retained.

In addition to the above changes, the following changes were made.

1. Changes to parallelization of control2state routines.
2. The combination of ensctl2state and ensctl2state_ad into a single ensctl2state module with the inclusion of a ensctl2state_set routine to define flags once.  This is done in a way that is consistent with what is done with control2state above and allows the flags to be calculated once rather than repeatedly every time the routines are called.
3. Deallocating arrays in read_* routines that were left allocated. (removed considerable memory)
4. Making some of the muse flags in setup routines dependent on qc mark as well as usage flag.
5. Removing repeated print lines in windht after 10 prints.  Number of times it would have been printed is then output (kcount).  Removes lots of output for one regression test.
6. Removal of code that does nothing.
7. Some changes to parallelization to improve efficiency.
8. Inclusion of some if-then-else's instead of repeated if-then's
9. Some reuse of arrays rather than defining new arrays.
10. Printing full double precision digits for the global norms.
11. Some minor changes to comments and indentation to make them more correct and consistent.

**Comment by RussTreadon-NOAA** [comment]
@jderber-NOAA , may this issue be closed?

**Comment by jderber-NOAA** [comment]
No.

**Comment by RussTreadon-NOAA** [comment]
No problem, we'll keep this issue open.  Thank you @jderber-NOAA for your reply.

**Comment by jderber-NOAA** [comment]
After the changes above were included in the code, it was run through regression testing.  Unfortunately they did not pass.  After considerable debugging, it was found that in many cases, the new code was correct, and the control (current head of trunk was wrong).  In several cases, the implementation of the re-sorting of the data to ensure that the order of the observations was not changed was not correct.  

To get identical regression results it was necessary to make the following changes to the head of the trunk.

diff --git a/src/gsi/read_fl_hdob.f90 b/src/gsi/read_fl_hdob.f90
index c7dc95f6..3dbd9299 100644
--- a/src/gsi/read_fl_hdob.f90
+++ b/src/gsi/read_fl_hdob.f90
@@ -132,12 +132,12 @@ subroutine read_fl_hdob(nread,ndata
      integer(i_kind) :: kk,klon1,klat1,klonp1,klatp1
      integer(i_kind) :: iuse
      integer(i_kind) :: nmind
-     integer(i_kind) :: nib
+     integer(i_kind) :: nib,icount,itx

      integer(i_kind) :: ibit(mxib)
      integer(i_kind) :: idate5(5)

-     integer(i_kind), allocatable,dimension(:) :: isort
+     integer(i_kind), allocatable,dimension(:) :: isort,iloc

 !    Real variables
      real(r_kind), parameter :: r0_001  =  0.001_r_kind
@@ -1156,13 +1156,27 @@ subroutine read_fl_hdob(nread,ndata,nodata,infile,obstype,
      endif

 !    Write header record and data to output file for further processing
+     allocate(iloc(ndata))
+     icount=0
+     do i=1,maxobs
+        if(isort(i) > 0)then
+           icount=icount+1
+           iloc(icount)=isort(i)
+        end if
+     end do
+     if(ndata /= icount)then
+        write(6,*) ' READ_HDOB_FL: mix up in read_hdob_fl ,ndata,icount ',ndata,icount
+        call stop2(49)
+     end if
        allocate(cdata_out(nreal,ndata))
      do i=1,ndata
+        itx=iloc(i)
         do k=1,nreal
-           cdata_out(k,i)=cdata_all(k,i)
+           cdata_out(k,i)=cdata_all(k,itx)
         end do
      end do
-     deallocate(cdata_all)
+     deallocate(iloc,isort,cdata_all)
+
 !     deallocate(etabl)

      call count_obs(ndata,nreal,ilat,ilon,cdata_out,nobs)
diff --git a/src/gsi/read_radar.f90 b/src/gsi/read_radar.f90
index 9ce156e7..5568a0d5 100644
--- a/src/gsi/read_radar.f90
+++ b/src/gsi/read_radar.f90
@@ -158,7 +158,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,
   integer(i_kind) nmrecs,ibadazm,ibadtilt,ibadrange,ibadwnd,ibaddist,ibadheight,ibadvad,kthin
   integer(i_kind) iyr,imo,idy,ihr,imn,isc,ithin
   integer(i_kind) ibadstaheight,ibaderror,notgood,idate,iheightbelowsta,ibadfit
-  integer(i_kind) notgood0
+  integer(i_kind) notgood0,itx,icount
   integer(i_kind) novadmatch,ioutofvadrange
   integer(i_kind) iy,im,idd,ihh,iret,levs,mincy,minobs,kx0,kxadd,kx
   integer(i_kind) nreal,nchanl,ilat,ilon,ikx
@@ -222,7 +222,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind


   real(r_kind),dimension(maxdat):: cdata
-  real(r_kind),allocatable,dimension(:,:):: cdata_all
+  real(r_kind),allocatable,dimension(:,:):: cdata_all,cdata_out

   real(r_double) rstation_id
   real(r_double),dimension(12):: hdr
@@ -271,7 +271,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind
   integer(i_kind) ntdrvr_thin2_foreswp,ntdrvr_thin2_aftswp
   integer(i_kind) maxout,maxdata
   integer(i_kind) kk,klon1,klat1,klonp1,klatp1
-  integer(i_kind),allocatable,dimension(:):: isort
+  integer(i_kind),allocatable,dimension(:):: isort,iloc

   real(r_single) elevmax,elevmin
   real(r_single) thisrange,thisazimuth,thistilt
@@ -317,6 +317,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,hgtl_fu
 !***********************************************************************************
   print_verbose=.false.
   if(verbose)print_verbose=.true.
+  icntpnt=0

 ! Check to see if radar wind files exist.  If none exist, exit this routine.
   inquire(file='radar_supobs_from_level2',exist=lexist1)
@@ -844,6 +845,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,
            nsuper2_kept=nsuper2_kept+1
            level2(ivad)=level2(ivad)+1
            nobs_box(irrr,iaaa,ivadz,ivad)=nobs_box(irrr,iaaa,ivadz,ivad)+1
+           icntpnt=icntpnt+1
            ndata    =min(ndata+1,maxobs)
            nodata   =min(nodata+1,maxobs)  !number of obs not used (no meaning here)
            usage = zero
@@ -886,6 +888,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,hgtl
               do i=1,maxdat
                  cdata_all(i,ndata)=cdata(i)
               end do
+              isort(icntpnt)=ndata
            END IF LEVEL_TWO_READ

         else
1277,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,
                          level3(ivad)=level3(ivad)+1
                       end if
                       nobs_box(irrr,iaaa,ivadz,ivad)=nobs_box(irrr,iaaa,ivadz,ivad)+1
+                      icntpnt=icntpnt+1
                       ndata  = min(ndata+1,maxobs)
                       nodata = min(nodata+1,maxobs)  !number of obs not used (no meaning here)
                       usage  = zero
@@ -1314,6 +1318,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind
                       do i=1,maxdat
                          cdata_all(i,ndata)=cdata(i)
                       end do
+                      isort(icntpnt)=ndata

                    else
                       notgood = notgood + 1
@@ -1946,6 +1951,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,
 !                     no vad and obs box counting for L2RWBUFR
 !                     (they are used for NCEP L2/2.5/3 radar obs, see code for those data)

+                        icntpnt=icntpnt+1
                         radartable_ndata_use(irdr_ptr) = radartable_ndata_use(irdr_ptr) + 1
                         ncolumntiltl2_kept=ncolumntiltl2_kept+1
                         if ( ndata+1 > maxobs ) then
@@ -1995,6 +2001,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,
                         do i=1,maxdat
                             cdata_all(i,ndata)=cdata(i)
                         end do
+                        isort(icntpnt)=ndata

                     else
                         notgood = notgood + 1
@@ -2165,7 +2172,6 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,
   maxdata=0
   nmissing=0
   subset_check(3)='NC006070'
-  icntpnt=0
   nswp=0
   nforeswp=0
   naftswp=0
@@ -2444,13 +2450,11 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis
                  if (ndata > ntmp) then
                     nodata=nodata+1
                  endif
-                 isort(icntpnt)=iout
               else
                  ndata =ndata+1
                  nodata=nodata+1
                  iout=ndata
-                 isort(icntpnt)=iout
               endif

               if(ndata > maxobs) then
@@ -2497,6 +2501,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,
               do j=1,maxdat
                  cdata_all(j,iout)=cdata(j)
               end do
+              isort(icntpnt)=iout
               jjj=jjj+1
            else
               notgood = notgood + 1
@@ -2970,13 +2975,11 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,
                        if (ndata > ntmp) then
                           nodata=nodata+1
                        endif
-                       isort(icntpnt)=iout

                     else
                        ndata =ndata+1
                        nodata=nodata+1
                        iout=ndata
-                       isort(icntpnt)=iout
                     endif

                     if(ndata > maxobs) then
@@ -3023,6 +3026,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,
                     do j=1,maxdat
                        cdata_all(j,iout)=cdata(j)
                     end do
+                    isort(icntpnt)=iout
                     if(foreswp)nfore=nfore+1
                     if(aftswp)naft=naft+1
                     jjj=jjj+1
@@ -3053,6 +3057,29 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,
      deallocate(zl_thin)
      call del3grids
   endif
+  allocate(iloc(ndata))
+  icount=0
+  write(499,*) icntpnt
+  do i=1,icntpnt
+     if(isort(i) > 0)then
+        icount=icount+1
+        iloc(icount)=isort(i)
+        write(499,*) ' icount ',i,isort(i),icount,iloc(icount)
+     end if
+  end do
+  if(ndata /= icount)then
+     write(6,*) ' READ_RADAR: mix up in read_radar ,ndata,icount ',ndata,icount
+     call stop2(49)
+  end if
+  allocate(cdata_out(maxdat,ndata))
+  do i=1,ndata
+     itx=iloc(i)
+     do k=1,maxdat
+        cdata_out(k,i)=cdata_all(k,itx)
+     end do
+  end do
   +  deallocate(iloc,isort,cdata_all)
+

   write(6,*)'READ_RADAR: # records(beams) read in nmrecs=', nmrecs
   write(6,*)'READ_RADAR: # records out of time window =', ntimeout
@@ -3086,10 +3113,10 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,
   write(6,*)'READ_RADAR: iimax =',iimax

 ! Write observation to scratch file
-  call count_obs(ndata,maxdat,ilat,ilon,cdata_all,nobs)
+  call count_obs(ndata,maxdat,ilat,ilon,cdata_out,nobs)
   write(lunout) obstype,sis,nreal,nchanl,ilat,ilon
-  write(lunout) ((cdata_all(k,i),k=1,maxdat),i=1,ndata)
-  deallocate(cdata_all)
+  write(lunout) ((cdata_out(k,i),k=1,maxdat),i=1,ndata)
+  deallocate(cdata_out)


   return
diff --git a/src/gsi/read_radar_wind_ascii.f90 b/src/gsi/read_radar_wind_ascii.f90
index 9d92699b..e8a56049 100644
--- a/src/gsi/read_radar_wind_ascii.f90
+++ b/src/gsi/read_radar_wind_ascii.f90real(r_kind), allocatable, dimension(:) :: zl_thin
   real(r_kind),dimension(nsig):: hges,zges
   real(r_kind) sin2,termg,termr,termrg,zobs,height
-  integer(i_kind) ntmp,iout,iiout,ntdrvr_thin2
+  integer(i_kind) ntmp,iout,iiout,itx,ntdrvr_thin2,icount
   real(r_kind) crit1,timedif
   real(r_kind),parameter:: r16000 = 16000.0_r_kind
   logical :: luse
   integer(i_kind) maxout,maxdata
-  integer(i_kind),allocatable,dimension(:):: isort
+  integer(i_kind),allocatable,dimension(:):: isort,iloc

 !--General declarations
   integer(i_kind) :: ierror,lunrad,i,j,k,v,na,nb,nelv,nvol, &
@@ -205,7 +205,7 @@ subroutine read_radar_wind_ascii(nread,ndata,nodata,infile,lunout,obstype,
   real(r_kind) :: azm,cosazm_earth,sinazm_earth,cosazm,sinazm
   real(r_kind) :: radartwindow
   real(r_kind) :: rmins_an,rmins_ob
-  real(r_kind),allocatable,dimension(:,:):: cdata_all
+  real(r_kind),allocatable,dimension(:,:):: cdata_all,cdata_out
   real(r_double) rstation_id

   character(8) cstaid
@@ -624,6 +624,27 @@ subroutine read_radar_wind_ascii(nread,ndata,nodata,infile,lunout,obstype,
      deallocate(zl_thin)
      call del3grids
   endif
+  allocate(iloc(ndata))
+  icount=0
+  do i=1,maxobs
+     if(isort(i) > 0)then
+        icount=icount+1
+        iloc(icount)=isort(i)
+     end if
+  end do
+  if(ndata /= icount)then
+     write(6,*) ' READ_ASCII_RADAR: mix up in read_satwnd ,ndata,icount ',ndata,icount
+     call stop2(49)
+  end if
+  allocate(cdata_out(maxdat,ndata))

+  do i=1,ndata
+     itx=iloc(i)
+     do k=1,maxdat
+        cdata_out(k,i)=cdata_all(k,itx)
+     end do
+  end do
+  deallocate(iloc,isort,cdata_all)
+
 !end modified for thinning

 !---all looping done now print diagnostic output
@@ -638,9 +659,9 @@ subroutine read_radar_wind_ascii(nread,ndata,nodata,infile,lunout,obstype,
   write(6,*)'READ_RADAR_WIND_ASCII: # bad azimuths                      =',ibadazm
 !---Write observation to scratch file---!

-  call count_obs(ndata,maxdat,ilat,ilon,cdata_all,nobs)
+  call count_obs(ndata,maxdat,ilat,ilon,cdata_out,nobs)
   write(lunout) obstype,sis,maxdat,nchanl,ilat,ilon
-  write(lunout) ((cdata_all(k,i),k=1,maxdat),i=1,ndata)
+  write(lunout) ((cdata_out(k,i),k=1,maxdat),i=1,ndata)


   !---------------DEALLOCATE ARRAYS-------------!

**Comment by jderber-NOAA** [comment]
Run times:

Note that the New (pmot = 0.) should pass on to the setup routines the same observations as the Control.  The New(pmot=2.) should pass on fewer observations.  The New(pmot=1.) will pass on more observations (the thinned observations) and should be used only for diagnostic runs.  The New(pmot=3.) will pass on the the thinned observations, but not the qc'ed obs so it will be less that pmot=1., but usually more than pmot=2.  pmot=3. should probably only be used for diagnostic runs and may not be that useful.

 
Global

               Control          New (pmot = 0.)    New (pmot=2.)
                 1996.                1895.                    1969.
                 2037.                1900.                    1925.
                 1885.                1915.                    1884.
                 1987.                1951.                    1913.
                 1825.                2092.                    2016.
                 1995.                1889.                    1799.

Unfortunately, the run times do not reflect the expected speed up in the new code.  Most of the runs were executed during the day time and the interaction with other jobs made the times inconsistent.  The final test was run at night and one can speculate that this test may reflect the true run times.  However, it is clear that the new code did not slow the global runs.

It was planned to run a regional case as well.  There appears to be a problem with my script and the regional case will not properly execute.  However, there is no reason to expect the regional runs to be slower.

At this point, it was necessary for me to end this ticket and try to get these changes into the trunk.  More changes were planned, but I was unable to complete them.
