### ISSUE TITLE
HAFS related ENKF changes to support the self-cycled ENSDA capability

### ISSUE THREAD

**Issue by BinLiu-NOAA** [NOAA-EMC/GSI#610]
Bring in the HAFS related ENKF changes to support the self-cycled ENSDA capability. The changes mainly developed and leveraged from Ting Lei (EMC).

## Related to (optional)
- Addressed by NOAA-EMC/GSI/pull/pr#

**Comment by RussTreadon-NOAA** [comment]
@BinLiu-NOAA , may this issue be closed?

**Comment by BinLiu-NOAA** [comment]
@RussTreadon-NOAA, according to our previous discussions, we working with @TingLei-daprediction to create a PR for this issue soon. Thanks!

**Comment by RussTreadon-NOAA** [comment]
Thank you for the updated.   Please reference this issue in the upcoming PR.

**Comment by RussTreadon-NOAA** [comment]
This issue will be closed in six weeks (January 23, 2024) if it remains inactive at that time.

**Comment by RussTreadon-NOAA** [comment]
This issue is closed along with PR #667.
