### ISSUE TITLE
Adding the capability to assimilate HDOBs in the V16 branch 

### ISSUE THREAD

**Issue by lbi2018** [NOAA-EMC/GSI#64]
This new issue is to include the capability to assimilate HDOBs in the V16 based on Xingren's HDOBs parallel experiments. 

GSI code changes: read_fl_hdob.f90

gsiparm change: exglobal_analysis_fv3gfs.sh.ecf

global_convinfo.txt and error table changes are also applied.

**Comment by MichaelLueken-NOAA** [comment]
These changes have been merged to the NOAA-EMC/GSI master.  Closing issue.
