### ISSUE TITLE
Add ensemble-based B for RRFS-SD DA

### ISSUE THREAD

**Issue by hongli-wang** [NOAA-EMC/GSI#641]
Current GSI analysis of smoke and dust for the RRFS-SD model only support use of a static/climatological background error matrix B. This work develops GSI to use an ensemble forecast of smoke and dust to model the follow-dependent B. This development also makes GSI have the capability to do the coupled air composition/meteorological DA for the RRFS-SD model. 

The modification will include but not limited to:

1. Read smoke/dust tracers from ensemble forecasts ( restart phy files)
2. Modified control variable transform to include smoke dust variables. 
3. Other related codes. For example, to work well alone with dbz and lightning DA. 

The smoke/dust assimilation should work independently or along with radar dbz, and the lightning assimilation. A reviewer who developed or knows well dbz EnVar assimilation is recommended to involve in the review process.

**Comment by RussTreadon-NOAA** [comment]
The GSI Handling Review team is going through open GSI issues.  Please update this issue with current status.  Inactive issues will be closed.

**Comment by hongli-wang** [comment]
I will close the issue. Thanks for the reminder.
