### ISSUE TITLE
a fix for setuprad.f90 on use of undefined variable by restoring lost initialization of raterr2 from previous version

### ISSUE THREAD

**Issue by TingLei-NOAA** [NOAA-EMC/GSI#648]
In our RRFS runs, it was found, the process in the setuprad.f90 in the current EMC GSI would cause a NaN value of raterr2 to be used in the calculation of the diagnostic parameter. Theoretically, it would not affect the optimization results but affect a certain monitoring statics.  
Specifically, for current EMC starting, for calculation of raterr2, 
 from line 1783
https://github.com/NOAA-EMC/GSI/blob/f76d872859257bfa614d6f6395132700ca6b1b77/src/gsi/setuprad.f90#L1783
`        diagadd=zero
        account_for_corr_obs = .false.
        varinv0=zero
!$omp parallel do  schedule(dynamic,1) private(ii,m,k,asum)
        do ii=1,nchanl
           m=ich(ii)
           if (varinv(ii)>tiny_r_kind .and. iuse_rad(m)>=1) then
             varinv0(ii)=varinv(ii)
             raterr2(ii)=error0(ii)**2*varinv0(ii)` 
For use of raterr2, n the following, raterr2 could be used as , from line 1836:
https://github.com/NOAA-EMC/GSI/blob/f76d872859257bfa614d6f6395132700ca6b1b77/src/gsi/setuprad.f90#L1836
` if (varinv(i) > tiny_r_kind ) then
........
stats(7,m)  = stats(7,m) -two*raterr2(i)*term !line 1867

`  
Because, in the line 1836 (to use of raterr2), only varinv > tiny_r_kind  is used while in its calculation part, extra condition (isue_rad(m)>=1) is used.  Hence, A nan value was generated when iuse_rad is <1. 
A fix is to add iuse_rad condition in the use of raterr2 part, this is what I did with my local branch. 
But I happen to find , in the GSI of older version ,  the raterr2 is first initialized to zeror
as shown in the master branch of @hongli-wang 's GSI fork 
 https://github.com/hongli-wang/GSI/blob/3defae9df07f07fe1ea871aed10e7810dc072277/src/gsi/setuprad.f90#L1736
`        tbc0=tbc
        tb_obs0=tb_obs
        varinv0 = varinv
        raterr2 = zero
        err2 = one/error0**2
        wgtjo= varinv     ! weight used in Jo term
        account_for_corr_obs = .false.`
So, I would suggest to restore that line (adding back that line to the current setuprad.f90 at, say, inserting it to line 1811.

**Comment by RussTreadon-NOAA** [comment]
@TingLei-NOAA , may this issue be closed?

**Comment by TingLei-NOAA** [comment]
@RussTreadon-NOAA  I thought this issue could be taken of by a satellite DA colleague.  Could the GSI codebase managing team has this assigned to an expert on this and he/she could decide how to proceed?

**Comment by RussTreadon-NOAA** [comment]
Sorry @TingLei-NOAA , we no longer have a GSI code manager. The GSI Handling Review team does not function as a codebase managing team.  Changes to the GSI repository originate from developers.  Please reach out to regional or global satellite DA colleagues to discuss and develop a fix.

**Comment by TingLei-NOAA** [comment]
@RussTreadon-NOAA  Got it! I will contact colleagues to see how it is going!

**Comment by TingLei-NOAA** [comment]
@xyzemc  Would you please have a look at this issue which you had help with when I traced to the cause.  If you think this should be fixed, would you take care of this issue and the PR?  Or you agree a fix is needed but I can do it, please let me know!.  Thanks!

**Comment by RussTreadon-NOAA** [comment]
Please reference this issue in any PRs which address the concerns raised in this issue.  

GSI development is winding down as we pivot to JEDI.  Please see the [Note](https://github.com/NOAA-EMC/GSI/wiki#note) on the [main GSI wiki](https://github.com/NOAA-EMC/GSI/wiki) page.  The GSI handling review team is closing issues not aligned with the stated policy.

**Comment by RussTreadon-NOAA** [comment]
This issue will be closed in six weeks (January 23, 2024) if it remains inactive at that time.

**Comment by xyzemc** [comment]
I will take care of this issue to fix the bug, and will open a PR shortly.

**Comment by RussTreadon-NOAA** [comment]
Thank you, @xyzemc .

**Comment by xyzemc** [comment]
Opened the PR to fix this issue: https://github.com/NOAA-EMC/GSI/pull/668
