### ISSUE TITLE
A indexing out of bounds issue shown in the global_4denvar regression test in setuprad.f90

### ISSUE THREAD

**Issue by TingLei-NOAA** [NOAA-EMC/GSI#676]
When trying to run various regression tests for a PR using debug mode GSI, an issue within the current EMC GSI is found.  in the global_4denvar regression test,  there are error messages:
```
forrtl: severe (408): fort: (2): Subscript #1 of the array ABI2KM_BC has value 4 which is greater than the upper bound of 3

Image              PC                Routine            Line        Source
gsi.x              0000000007AA763F  Unknown               Unknown  Unknown
gsi.x              00000000054E656A  rad_setup_mp_setu        1108  setuprad.f90
gsi.x              0000000003F6488C  gsi_radoper_mp_se         100  gsi_radOper.F90
gsi.x              00000000025FC8CC  setuprhsall_              491  setuprhsall.f90
....
```
The L1108 in setuprad.f90 is 
```
      abi2km_bc = zero
       abi2km_bc(2) = 233.5_r_kind
        abi2km_bc(3) = 241.7_r_kind
        abi2km_bc(4) = 250.5_r_kind   !L1108
      ````
      The abi2km_bc is declared as "real(r_kind),dimension(nchanl) :: abi2km_bc".  
      so seems when nchanl is less than 4, the error would occur as in this regression test. 
A quick fix for considering the actual value of nchanl  is needed

**Comment by wx20jjung** [comment]
Is it possible to track down the original author of this code?  It seems to start and end in setuprad.f90.  Without more history, it is difficult to determine its purpose.

The current ABI instruments have 16 channels.  The current ABI subsets contain 10 infrared channels.  The code seems to expect 3 channels (2, 3, 4?). This will conflict with the current use of ABI data.  Does anyone know what version of the satinfo file and the corresponding CRTM files this code requires?

The logic for a bias correction seems odd.  Normally, I would expect a bias correction with respect to the (regional) model.  Only the observation and a static value are used to compute a correction.  This implies a calibration adjustment to the specific channels. 

To me, this code seems orphaned and obsolete.

**Comment by TingLei-NOAA** [comment]
@wx20jjung Thanks for the explanation and clarification.  By, for example, "git blame -L 1105,1108 setuprad.f90", those lines 
```
         abi2km_bc = zero
        abi2km_bc(2) = 233.5_r_kind
        abi2km_bc(3) = 241.7_r_kind
        abi2km_bc(4) = 250.5_r_kind
```  were "technically" from the PR at Dec. 4,2023  ( abi2km =.false. is hardwired in setuprad.f90 and all abi2km_bc part are not supposed to have actual impacts ).    I am wondering maybe the developers have some plan for this part and leave them like a place holder for future plans.   So, I would prefer to keeping them and adding a certain test  conditions to avoid indexing error.
