### ISSUE TITLE
Switching from assimilating microwave antenna temperatures to brightness temperatures

### ISSUE THREAD

**Issue by ScottSieron-NOAA** [NOAA-EMC/GSI#68]
This is to switch from assimilating satellite microwave antenna temperature observations to brightness temperatures.

As it is now, the bias between the observed antenna temperature and the simulated brightness temperature is being handled by the variational bias correction. For the platforms and feeds which have only antenna temperature, an accurate formula for converting antenna temperatures to brightness temperatures will be used. Doing this and assimilating brightness temperatures removes a burden of the variational bias correction.

Many (or all) other centers are assimilating brightness temperatures.

**Comment by ScottSieron-NOAA** [comment]
Plotted are assimilated brightness temperatures that were converted from antenna temperatures (AMSU-A).

![normal_converted_ch09](https://user-images.githubusercontent.com/70583461/97907147-d4b23e00-1d12-11eb-983f-14b47ac17e85.png)

**Comment by ScottSieron-NOAA** [comment]
Antenna temperature conversion appears to be working. Will verify for other satellites, sensors, channels. Will investigate outliers.
![n19_amsua_ch01_convEars-convNorm_line](https://user-images.githubusercontent.com/70583461/100010982-162c8b00-2d9f-11eb-923f-7220737846c2.png)

**Comment by ScottSieron-NOAA** [comment]
Issues have been found with metop-a AMSU-A (figure 1). Strings of swaths have extreme differences between native and converted antenna/brightness temperatures. These observations are clumped in the same swath, in consecutive swaths, and exhibit a scan/zenith angle dependence of the exact difference. 
![metop-a_amsua_ch12_convNorm-convEars_qc_map](https://user-images.githubusercontent.com/70583461/102925429-598f1d80-4461-11eb-896d-946b2308349b.png)

The scan/zenith angle dependence resembles the pattern of the difference between antenna and brightness temperatures from ATMS, which provides both. (figure 2)
![npp_atms_ch12_convNorm-origNorm_qc_map](https://user-images.githubusercontent.com/70583461/102928242-619d8c00-4466-11eb-82c6-b3339b146dd4.png)

The working theory is that there are errors in the reporting of satellite and sensor parameter values used in the conversion between antenna and brightness temperature.

**Comment by ScottSieron-NOAA** [comment]
This is to expound upon the previous comment.

In the one 6-hour period we have investigated, there are instances of a significant inconsistency between co-located observations across the EARS direct broadcast and the normal feed, exclusively for amsua-a on metop-a (all other amsu-a/-b, mhs and atms appear fine in this 6-hour period). These inconsistencies exist whether we convert the normal feed antenna temperature to brightness temperature (figure 1; channel 11), or convert the EARS direct broadcast brightness temperature to antenna temperature.
![metop-a_amsua_ch11_convNorm-convEars_map](https://user-images.githubusercontent.com/70583461/103665643-a5ea5b00-4f41-11eb-9538-001c3bf4cd84.png)

There are patterns to which observations have the significant inconsistency. The vast majority of observations are in a swath in which all other observations have the inconsistency. The vast majority of swaths with inconsistent observations are adjacent to other such swaths.

There is also a distinct pattern of the magnitude of the inconsistency relating to the field of view or scan angle; at least for channel 11, they are higher at the the moderate scan angles.

It was this that prompted experimenting with messing with the FOV in the conversion from normal feed antenna temperature to brightness temperature. We set the FOV index to always be 1 instead of the actual value. This of course changes the cold space, earth view, and platform efficiency values used in the antenna/brightness temperature conversion. The results are shown in the figure below (channel 11). Looking at southern Indonesia, Australia, and the Pacific Ocean as areas which were showing inconsistencies, we see that the magnitude of the inconsistencies are substantially reduced across the observations at moderate scan angle, generally between -0.1 K and 0.1 K.
![metop-a_amsua_ch11_convNormFOV1-convEars_map](https://user-images.githubusercontent.com/70583461/103665605-99660280-4f41-11eb-8a8a-59c666f048e2.png)

We hope that these results would help with any efforts in identifying a cause of the problem.

**Comment by ScottSieron-NOAA** [comment]
O minus B suggest that there is an with the EARS direct broadcast.

In the aforementioned regions where the EARS brightness temperatures are greater than the normal feed converted brightness temperatures, there is an overall average positive O-B (figure below).
![metop-a_amsua_ch11_convEars_map](https://user-images.githubusercontent.com/70583461/103679352-bd7e0f80-4f52-11eb-8164-3aad47338e41.png)

This feature is not present with the normal feed observations that have been converted in the GSI to brightness temperature (figure below).
![metop-a_amsua_ch11_convNorm_map](https://user-images.githubusercontent.com/70583461/103679530-ef8f7180-4f52-11eb-9744-553bf225e493.png)

**Comment by ScottSieron-NOAA** [comment]
![Uploading metop-a_amsua_ch11_convNorm-convEars_line.png…]()

**Comment by ScottSieron-NOAA** [comment]
![metop-a_amsua_ch11_convNorm-convEars_line](https://user-images.githubusercontent.com/70583461/103693848-f2489180-4f67-11eb-87d3-20b3b4179d52.png)

**Comment by ScottSieron-NOAA** [comment]
Metop-A AMSU-A disparities have been confirmed to be due to v1/v2 satellite antenna correction versions. The value of BUFR mnemonic SACV has been used to decide whether to use v1 coefficients from CRTM SpcCoeff file and v2 coefficients (for channel 11, which were hard-coded) for a given observation. The read_bufrtovs subroutine has been modified to support to read and store multiple sets of antenna correction patterns from respective SpcCoeff files, using naming convention <Sensor_ID>.SpcCoeff.bin and <Sensor_ID>_v#.SpcCoeff.bin with # able to range from 2 to 9 (though only a version 2 is ever likely). The functionality of reading multiple files been tested successfully except actually having a unique <Sensor_ID>_v#.SpcCoeff.bin file.

![metop-a_amsua_ch11_origEarsSACV-origNorm_map](https://user-images.githubusercontent.com/70583461/109501863-35a21680-7a66-11eb-9580-bef3818ab7e7.png)

**Comment by ScottSieron-NOAA** [comment]
We are awaiting SpcCoeff files from JCSDA to complete the assessment and proceed with a parallel experiment

**Comment by ScottSieron-NOAA** [comment]
The metop-a amsua SpcCoeff version 2 file from JCSDA was delivered on 13 April 2021. The GSI has been successfully modified to read and use multiple versions of the SpcCoeff file as appropriate. Normal feed observations are converted to brightness temperature with the latest version of antenna correction coefficients. Direct broadcast observations with SACV not of the latest version are converted to antenna temperature with the SACV version of ACCs, and then converted back to brightness temperature with the latest version of ACCs.

As an example, shown are channel 9 brightness temperature differences between converted normal feed observations and direct broadcast observations.
![metop-a_amsua_ch09_convNormV2All-convEarsV2All_map](https://user-images.githubusercontent.com/70583461/114923466-df611b00-9dfa-11eb-8a27-1f5f56a40fae.png)

**Comment by ScottSieron-NOAA** [comment]
The parallel experiment is near completion. There are some short-term forecast degradation in upper-level winds shown in the "sanity check" plots, but longer term forecasts show improvement.
![gsistat_uvtq_RMSE](https://user-images.githubusercontent.com/70583461/124134095-7def3680-da50-11eb-84a6-161bdfe9bb19.png)

**Comment by ScottSieron-NOAA** [comment]
The original TaTb experiment was extended to mid-October. The upper-level wind degradation has been lessened somewhat as well as the 8- to 10-day height anomaly correlation improvement.

![gsistat_uvtq_RMSE](https://user-images.githubusercontent.com/70583461/127890673-28fba325-bc89-4077-9754-f168d7c5585c.png)

A new experiment has been started with resetting the bias correction coefficients of all satellite sensors to 0, and using CRTM v2.4.0. Compared to the original experiment, results so far are distinctly different and mixed in improvement/degradation
![gsistat_uvtq_RMSE](https://user-images.githubusercontent.com/70583461/127890926-84b913ab-a29c-4377-ba9b-3a7d007103f6.png)
.

**Comment by ScottSieron-NOAA** [comment]
The parallel experiment with bias correction coefficients of all satellite sensors to 0, and using CRTM v2.4.0, is near completion. Compared to the original experiment, results are distinctly different and mixed in improvement/degradation, though perhaps more improvement.
![gsistat_uvtq_RMSE](https://user-images.githubusercontent.com/70583461/131848152-300ec1b5-d867-4dc1-82b9-73128ecbabb6.png)

**Comment by ScottSieron-NOAA** [comment]
The CRTM 2.4.0 experiment also has overall reduced biases, especially in temperature.
![gsistat_uvtq_Bias](https://user-images.githubusercontent.com/70583461/131852242-4e7e835e-3762-4f00-b0f7-16402a9fd2f8.png)

**Comment by ScottSieron-NOAA** [comment]
The experiment with resetting the bias correction coefficients of all satellite sensors to 0, and using CRTM v2.4.0 (TaTb4b_240) was stopped on October 2. Fit-to-obs show neutral to positive results in Z (pictured), W, Q and T. 

In TaTb4b_240, the GFDL cloud fraction was calculated and input into the CRTM. Especially without the inclusion of precipitation in this experiment, these cloud fractions are generally small. We have begun a new experiment in which CRTM 240 is used, but all clouds with water content greater than zero have the cloud fractions set to one.
![z500 gl adp](https://user-images.githubusercontent.com/70583461/135655749-2c94e46b-8b49-4044-8a30-f44022184b5c.png)
![zb500 gl adp](https://user-images.githubusercontent.com/70583461/135655750-a8626e3d-44d1-4b0d-9eee-17151e17240a.png)
![n19_amsua_ch08_CFmap](https://user-images.githubusercontent.com/70583461/135655772-db27e2ce-52ec-46f1-b3cf-145ad1f2a069.png)

**Comment by ScottSieron-NOAA** [comment]
An experiment was run in which CRTM 240 is used, but all clouds with water content greater than zero have the cloud fractions set to one. Results as shown by the sanity check plots are similar to using the calculated cloud fractions. The experiment was shortened to just a few days.

![gsistat_uvtq_RMSE](https://user-images.githubusercontent.com/70583461/140073045-c62f7c9f-2a04-4587-b366-68fbcc0c2c04.png)

**Comment by ScottSieron-NOAA** [comment]
We await results from experiments which built-upon these methods to implement this into v16.x.

**Comment by ScottSieron-NOAA** [comment]
Regression test results:

Test project /scratch1/NCEPDEV/da/Scott.Sieron/GDAS/GSI/build
      Start  1: global_T62
      Start  2: global_T62_ozonly
      Start  3: global_4dvar_T62
      Start  4: global_4denvar_T126
      Start  5: global_fv3_4denvar_T126
      Start  6: global_fv3_4denvar_C192
      Start  7: global_lanczos_T62
      Start  8: arw_netcdf
      Start  9: arw_binary
      Start 10: nmm_binary
      Start 11: nmm_netcdf
      Start 12: nmmb_nems_4denvar
      Start 13: hwrf_nmm_d2
      Start 18: global_C96_fv3aero
      Start 19: global_C96_fv3aerorad
      Start 14: hwrf_nmm_d3
 1/19 Test  #2: global_T62_ozonly ................   Passed  362.84 sec
      Start 15: rtma
 2/19 Test  #8: arw_netcdf .......................***Failed  602.62 sec
      Start 16: global_enkf_T62
 3/19 Test #11: nmm_netcdf .......................***Failed  662.47 sec
      Start 17: netcdf_fv3_regional
 4/19 Test #18: global_C96_fv3aero ...............***Failed  670.03 sec
 5/19 Test  #9: arw_binary .......................***Failed  723.12 sec
 6/19 Test  #3: global_4dvar_T62 .................***Failed  1146.58 sec
 7/19 Test #16: global_enkf_T62 ..................   Passed  666.29 sec
 8/19 Test #17: netcdf_fv3_regional ..............   Passed  784.30 sec
 9/19 Test #10: nmm_binary .......................***Failed  1517.91 sec
10/19 Test #14: hwrf_nmm_d3 ......................   Passed  1760.62 sec
11/19 Test #13: hwrf_nmm_d2 ......................***Failed  1809.49 sec
12/19 Test #15: rtma .............................   Passed  2774.66 sec
13/19 Test  #7: global_lanczos_T62 ...............***Failed  3245.72 sec
14/19 Test  #4: global_4denvar_T126 ..............***Failed  3486.70 sec
15/19 Test  #1: global_T62 .......................***Failed  3547.61 sec
16/19 Test #19: global_C96_fv3aerorad ............   Passed  3548.14 sec
17/19 Test #12: nmmb_nems_4denvar ................***Failed  3552.21 sec
18/19 Test  #6: global_fv3_4denvar_C192 ..........***Failed  3747.71 sec
19/19 Test  #5: global_fv3_4denvar_T126 ..........***Failed  4509.45 sec

32% tests passed, 13 tests failed out of 19

Total Test time (real) = 4509.56 sec

The following tests FAILED:
          1 - global_T62 (Failed)
          3 - global_4dvar_T62 (Failed)
          4 - global_4denvar_T126 (Failed)
          5 - global_fv3_4denvar_T126 (Failed)
          6 - global_fv3_4denvar_C192 (Failed)
          7 - global_lanczos_T62 (Failed)
          8 - arw_netcdf (Failed)
          9 - arw_binary (Failed)
         10 - nmm_binary (Failed)
         11 - nmm_netcdf (Failed)
         12 - nmmb_nems_4denvar (Failed)
         13 - hwrf_nmm_d2 (Failed)
         18 - global_C96_fv3aero (Failed)
Errors while running CTest

**Comment by ADCollard** [comment]
@ScottSieron-NOAA , do we understand why these failures occurred?  I assume these are because we expect the results to change for the microwave sounders (and only the microwave sounders), but can you confirm that the differences are as expected?

**Comment by MichaelLueken** [comment]
Hi @ScottSieron-NOAA.  Since these changes were merged to the authoritative repository at [c13361c](https://github.com/NOAA-EMC/GSI/commit/c13361c587503298907480d14ef5c92ecb0be3f7) with PR #350, I am checking to see if it is alright to close this issue.

**Comment by ADCollard** [comment]
@MichaelLueken-NOAA, @ScottSieron-NOAA is not longer with EMC.  Please feel free to close this issue.

**Comment by MichaelLueken** [comment]
@ADCollard Thanks for the update.  Closing issue now.
