### ISSUE TITLE
Port to Gaea-C5

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/GSI#696]
The GSI should be ported to Gaea-C5.  Some support is available for the decommissioned C4 cluster, which can be used as a template.  An initial crack at this port was done in the branch https://github.com/DavidHuber-NOAA/GSI/tree/feature/gaea, but the regression tests are crashing.

**Comment by DavidHuber-NOAA** [comment]
FYI @jswhit.

**Comment by RussTreadon-NOAA** [comment]
@DavidHuber-NOAA , what is the status of this issue?

**Comment by DavidHuber-NOAA** [comment]
@RussTreadon-NOAA I believe this work will be handled by EPIC.  Is that correct, @davidburrows-nco?

**Comment by DavidBurrows-NCO** [comment]
@RussTreadon-NOAA @DavidHuber-NOAA @aerorahul 
That is correct, Dave. I'll add this issue to my tracker sheet for EPIC for when we begin working on GSI. Thanks for pointing this towards us.

**Comment by RussTreadon-NOAA** [comment]
Thanks you @DavidHuber-NOAA for reaching out to @DavidBurrows-NCO .  Thank you @DavidBurrows-NCO for the update.  I will assign this issue to @DavidBurrows-NCO .
