### ISSUE TITLE
Update RDHPCS Hera to Rocky-8 compliance

### ISSUE THREAD

**Issue by HenryRWinterbottom** [NOAA-EMC/GSI#711]
**Description**

RDHPCS Hera is being upgraded to Linux [Rocky version 8](https://rockylinux.org/). As a result all build applications, namely module files must be updated accordingly.

**Required Functionality**

A UFS based applications used by the UFS global-workflow must be updated to Rocky-8.

**Proposed Solution**

Update all UFS global-workflow applications to Rocky-8 compatability.

**Definition of Completion**

The global-workflow and the associated UFS applications reproduce RHEL 8 instances. Further, all unit-tests pass with success.

**Related Issues**

Global workflow issue [#2329](https://github.com/NOAA-EMC/global-workflow/issues/2329)

**Comment by RussTreadon-NOAA** [comment]
Two items:
1. @hu5970 opened GSI issue [#710](https://github.com/NOAA-EMC/GSI/issues/710) to document the same need.  We only need one issue.   Which one shall we close?
2. [`RussTreadon-NOAA:feature/rocky8`](https://github.com/RussTreadon-NOAA/GSI/tree/feature/rocky8) at ab59b2e0 contains the Hera modulefile update needed to build `gsi.x` and `enkf.x` on Hera Rocky-8 nodes.
