### ISSUE TITLE
Thinning of ATMS

### ISSUE THREAD

**Issue by ADCollard** [NOAA-EMC/GSI#731]
There are two minor annoyances with thinning that need to be addressed.

In the `makegrids` subroutine (line 405)
of [satthin.F90](https://github.com/NOAA-EMC/GSI/blob/develop/src/gsi/satthin.F90), `itxmax` is set to 1.e9 if thinning is turned off.   This is way too large for most satellites and invariably results in insufficient memory issues when used.   This needs to be reset to 1.e7.

In [read_atms.f90](https://github.com/NOAA-EMC/GSI/blob/develop/src/gsi/read_atms.f90) at line 547, a kludge was put in place to mitigate the effect of correlated errors in the SNPP ATMS obs.  It was only ever marginally successful and should be removed:

```
! Just use every fifth scan position and scanline (and make sure that we have
! position 48 as we need it for scan bias)
     if (5*NINT(REAL(IScan(Iob))/5_r_kind) /= IScan(IOb) .OR. &
          5*NINT(REAL(IFov-3)/5_r_kind) /= IFOV -3 ) CYCLE ObsLoop 
```

**Comment by ADCollard** [comment]
The impact of the second change is to slightly increase counts bit should have a minimal effect on other statistics.   Here is a snapshot for the 2024032418 cycle for NOAA-21 ATMS:
<img width="929" alt="Screenshot 2024-03-29 at 17 21 27" src="https://github.com/NOAA-EMC/GSI/assets/40322596/4f9a1601-814e-4a50-9392-0b463409e3fe">
<img width="940" alt="Screenshot 2024-03-29 at 17 23 46" src="https://github.com/NOAA-EMC/GSI/assets/40322596/e33723d9-43ca-444d-a14f-c00bd56eccd1">

**Comment by RussTreadon-NOAA** [comment]
PR #734 merged into `develop`.  Closing issue.
