### ISSUE TITLE
nread bug in read_radar.f90

### ISSUE THREAD

**Issue by ShunLiu-NOAA** [NOAA-EMC/GSI#737]
1. nread is zero after reading-in radar level2 data. The value of nread should be nsuper2_kept.
2. when processing tail Doppler radar data, nread shouldn't be reset as zero.

**Comment by RussTreadon-NOAA** [comment]
PR #738 merged into `develop` at [a3a2633](https://github.com/NOAA-EMC/GSI/commit/a3a26336dcf4de3bac4afe8fbe790947e51af4db)

Close issue.
