### ISSUE TITLE
GSI for RRFS does not build without warning prints

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/GSI#751]
NCO has been getting stricter about codes compiling cleanly, without warnings.  I see warning prints, but limited to a single routine (src/enkf/observer_fv3reg.f90), that are of this type:

```
/lfs/h2/emc/lam/noscrub/Matthew.Pyle/rrfs-workflow_warnings/sorc/gsi/src/enkf/observer_fv3reg.f90(24): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [IX]
subroutine setup_linhx(rlat, rlon, time, ix, delx, ixp, delxp, iy, dely,  &
-----------------------------------------^
```

Would like to see this item cleaned up well ahead of code delivery for the RRFS - hopefully a straightforward item to correct.

**Comment by ShunLiu-NOAA** [comment]
@MatthewPyle-NOAA I will take a look at this issue.

**Comment by MatthewPyle-NOAA** [comment]
Thanks @ShunLiu-NOAA

**Comment by RussTreadon-NOAA** [comment]
@ShunLiu-NOAA , what is the status of this issue?

**Comment by ShunLiu-NOAA** [comment]
I will work on regression test and update my PR.

**Comment by RussTreadon-NOAA** [comment]
Thank you, @ShunLiu-NOAA
