### ISSUE TITLE
Turn on SDL in global_4denvar ctest

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GSI#756]
GFS v17 will run `gsi.x` with scale dependent localization (SDL) on.  GFS v17 will use three bands. Two bands is sufficient for the ctest.  the following will be added to the global_4denvar namelist `HYBRID_ENSEMBLE `
```
  s_ens_h=1000.0,300.0,685.0,s_ens_v=-0.5,-0.5,0.0,
  readin_localization=.false.,global_spectral_filter_sd=.false.,
  r_ensloccov4scl=1,nsclgrp=2,naensloc=3,
```

This issue is opened to document the addition of SDL to the global_4denvar ctest.

**Comment by RussTreadon-NOAA** [comment]
@CatherineThomas-NOAA  & @TravisElless-NOAA - here's the GSI issue for turning on SDL in the global_4denvar ctest.

**Comment by RussTreadon-NOAA** [comment]
This work will be done in [RussTreadon-NOAA:feature/sdl](https://github.com/RussTreadon-NOAA/GSI/tree/feature/sdl).

**Comment by RussTreadon-NOAA** [comment]
Install `feature/sdl` on Dogwood.  Build `gsi.x` and `enkf.x`. Repeat using current head of `develop`.  Since this PR only alters the global_4denvar ctest, run this test alone with the following results
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/sdl/build
    Start 1: global_4denvar
1/1 Test #1: global_4denvar ...................   Passed  1746.68 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 1746.79 sec
```
This is an expected result since this PR does not alter `gsi.x`.  It only activates SDL.  The same `global_4denvar.sh` script and global_4denvar namelist is used for the _updat_ (`feature/sdl`) and _contrl_ (`develop`).

Rerun `global_4denvar` ctest with SDL inactive (previous configuration).  Interestingly activating SDL does not significantly alter `gsi.x` wall times.

**SDL inactive**
```
global_4denvar_hiproc_contrl/stdout:The total amount of wall time                        = 303.004111
global_4denvar_hiproc_updat/stdout:The total amount of wall time                        = 334.221672
global_4denvar_loproc_contrl/stdout:The total amount of wall time                        = 402.752918
global_4denvar_loproc_updat/stdout:The total amount of wall time                        = 404.935394
```

**SDL active**
```
global_4denvar_hiproc_contrl/stdout:The total amount of wall time                        = 361.189617
global_4denvar_hiproc_updat/stdout:The total amount of wall time                        = 303.603790
global_4denvar_loproc_contrl/stdout:The total amount of wall time                        = 404.951925
global_4denvar_loproc_updat/stdout:The total amount of wall time                        = 406.083618
```

The _loproc_ wall times with SDL active are about 2 seconds more than with SDL inactive.  

The _hiproc_ wall times show system variability.  With SDL inactive the _updat_ wall time is 31 seconds greater than the _contrl_.  With SDL active the _contrl_ wall time is 58 seconds greater than the _updat_.  These differences likely represent system variability and not SDL wall time impact.

**Comment by CatherineThomas-NOAA** [comment]
I also ran the regression tests both with and without SDL on, this time on Hera:
```
SDL OFF
runtime.global_4denvar_hiproc_contrl.txt:The total amount of wall time                    	= 443.950552
runtime.global_4denvar_hiproc_updat.txt:The total amount of wall time                    	= 364.692203
runtime.global_4denvar_loproc_contrl.txt:The total amount of wall time                    	= 460.127669
runtime.global_4denvar_loproc_updat.txt:The total amount of wall time                    	= 461.715467

SDL ON
runtime.global_4denvar_hiproc_contrl.txt:The total amount of wall time                    	= 370.524879
runtime.global_4denvar_hiproc_updat.txt:The total amount of wall time                    	= 372.944092
runtime.global_4denvar_loproc_contrl.txt:The total amount of wall time                    	= 475.502710
runtime.global_4denvar_loproc_updat.txt:The total amount of wall time                    	= 485.123373
```

Except for the SDL OFF hiproc control case, the other 3 cases are slightly longer (8-24 seconds) with SDL ON, which is expected.  Hera is known for its machine variability, so the extra 70 seconds for hiproc control SDL OFF is likely due to that, given that the other 3 cases performed reasonably.

**Comment by RussTreadon-NOAA** [comment]
**Hera and Hercules ctests**

Install `feature/sdl` on Hera and Hercules.  Run `global_4denvar` ctest on each machine.  Test passed on each machine.

**Hera**
```
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/sdl/build
    Start 1: global_4denvar
1/1 Test #1: global_4denvar ...................   Passed  2586.52 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 2586.68 sec
```

**Hercules**
```
Test project /work/noaa/da/rtreadon/git/gsi/sdl/build
    Start 1: global_4denvar
1/1 Test #1: global_4denvar ...................   Passed  1840.71 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 1840.74 sec
```
