### ISSUE TITLE
Ctest failure on Jet

### ISSUE THREAD

**Issue by wx20jjung** [NOAA-EMC/GSI#768]
In running the ctests on Jet, the rrfs tests fail for both the develop and update.  Here is the failure line from one of them:

forrtl: severe (24): end-of-file during read, unit 24, file /mnt/lfs5/HFIP/hfv3gfs/Jim.Jung/ptmp/tmpreg_rrfs_3denvar_rdasens/rrfs_3denvar_rdasens_loproc_u
pdat/coupler.res

**Comment by RussTreadon-NOAA** [comment]
Tagging @ShunLiu-NOAA and @hu5970 .   Have we confirmed that the rrfs ctest works on Jet?

**Comment by ShunLiu-NOAA** [comment]
Ming will test it on JET once he returns his leave.

**Comment by RussTreadon-NOAA** [comment]
@wx20jjung , has this issue been resolved or does it still persist on Jet?

**Comment by wx20jjung** [comment]
I tried the ctest again on jet.  Same file missing error
forrtl: severe (24): end-of-file during read, unit 24, file
/mnt/lfs4/NESDIS/nesdis-rdo1/Jim.Jung/ptmp/tmpreg_rrfs_3denvar_rdasens/rrfs_3denvar_rdasens_loproc_updat/coupler.res

**Comment by RussTreadon-NOAA** [comment]
@hu5970 , can we fix the rrfs test on Jet?

**Comment by RussTreadon-NOAA** [comment]
While working on PR #787 find that the problem Jim reports still exists on Jet  

Attempts to run rrfs_3denvar_rdasens fail in job rrfs_3denvar_rdasens_loproc_updat with the error message
```
forrtl: severe (24): end-of-file during read, unit 24, file /mnt/lfs5/HFIP/hfv3gfs/Russ.Treadon/ptmp/tmpreg_rrfs_3denvar_rdasens/rrfs_3denvar_rdasens_loproc_updat/coupler.res
Image              PC                Routine            Line        Source
gsi.x              0000000005A04A08  Unknown               Unknown  Unknown
gsi.x              0000000005A3BB8A  Unknown               Unknown  Unknown
gsi.x              0000000000A7DEAA  gsi_rfv3io_mod_mp         323  gsi_rfv3io_mod.f90
gsi.x              00000000006CF2A3  convert_fv3_regio          37  fv3_regional_interface.f90
gsi.x              00000000004233E3  gsimod_mp_gsimain        2349  gsimod.F90
gsi.x              0000000000414C35  MAIN__                    620  gsimain.f90
```

The working copy of coupler.res in the run directory is zero length.   Script `rrfs_3denvar_rdasens.sh` copies this file into the working directory as follows
```
# update times in coupler.res to current cycle time
cp ${bkpath}/fv3_coupler.res          coupler.res
sed -i "s/yyyy/${YYYY}/" coupler.res
sed -i "s/mm/${MM}/"     coupler.res
sed -i "s/dd/${DD}/"     coupler.res
sed -i "s/hh/${HH}/"     coupler.res
```
A check of `rrfs_3denvar_rdasens_loproc_updat.out` shows
```
bkpath=/lfs5/NESDIS/nesdis-rdo2/David.Huber/save/CASES/regtest/regional/rrfs/2023061012/ges
```
This directory does not exist
```
/lfs5/HFIP/hfv3gfs/Russ.Treadon/git/gsi/tmp/develop/build$ ls /lfs5/NESDIS/nesdis-rdo2/David.Huber/save/CASES/regtest/regional/rrfs/2023061012
ls: cannot access '/lfs5/NESDIS/nesdis-rdo2/David.Huber/save/CASES/regtest/regional/rrfs/2023061012': No such file or directory
/lfs5/HFIP/hfv3gfs/Russ.Treadon/git/gsi/tmp/develop/build$ ls -l /lfs5/NESDIS/nesdis-rdo2/David.Huber/save/CASES/regtest/regional/rrfs/
total 4
drwxr-sr-x 5 David.Huber nesdis-rdo2 4096 Jan  5  2023 2021072518
```

Tagging @DavidHuber-NOAA and @InnocentSouopgui-NOAA for awareness.

**Comment by DavidHuber-NOAA** [comment]
Thanks for looking into this, @RussTreadon-NOAA.  I'll perform an rsync from Hera and get this data updated.

**Comment by DavidHuber-NOAA** [comment]
The regression test data has been updated on Jet.  I will create a nightly rsync check against Hera to prevent this from happening again.

**Comment by RussTreadon-NOAA** [comment]
rrfs_3denvar_rdasens now runs on Jet as reported in PR #787.

Close this issue.
