### ISSUE TITLE
format changes for metop-sg-a1 and iasi-ng

### ISSUE THREAD

**Issue by wx20jjung** [NOAA-EMC/GSI#770]
I have run into 2 format issues with IASI-NG_metop-sg-a1.  

1) The number of channels is an order of magnitude larger than the output will allow.  There are instances where formatted writes are I4 but need to be I5.  
2) The satellite name "metop-sg-a1 is 11 characters but the gsi code is setup for only 10.

**Comment by RussTreadon-NOAA** [comment]
See discussion [#769](https://github.com/NOAA-EMC/GSI/discussions/769) for additional information.
